.TH sass 1 "December 18, 2008"
.SH NAME
restclient -  simple REST client for Ruby
.SH SYNOPSIS
.B restclient
[options] [username] [password]
.SH DESCRIPTION
This library provides a simple way to access RESTful web services in Ruby.
.SH OPTIONS
.TP 8
.B get  url|name 
To get the single information.
.TP 8
.B  put url|name 
To put the single information.
.TP 8
.B post url|name 
To put multipart information.
.TP 8
.B  delete url|name 
To delete.
.SH SEE ALSO
This program is shipped as part of the librestclient-ruby1.8 library
package, you can check its corresponding documentation can be found in
the librestclient-ruby-doc package.
.SH AUTHOR
This manual page was written by Deepak Tripathi <apenguinlinux@gmail.com>, based
on the command-line output of this program, for the Debian GNU/Linux
system (but may be freely used by others).
