#!/bin/sh
# postinst script for foreman-*
#
# see: dh_installdeb(1)

if [ ! -z "${DEBUG}" ]; then
  set -x
else
  set -e
fi

. /usr/share/debconf/confmodule

LOGFILE='/var/log/foreman-install.log'

# if this script aborts with an error dpkg can
# hang if daemons have been started
trap db_stop EXIT

# Update gems
cd /usr/share/foreman
if [ ! -z "${DEBUG}" ]; then
  bundle update foreman_chef
else
  bundle update foreman_chef 2>&1 >> $LOGFILE
fi

# Own all the core files
chown -Rf foreman:foreman '/usr/share/foreman'

#DEBHELPER#

exit 0
