# template: default
%global gem_name logger

Name: rubygem-%{gem_name}
Version: 1.7.0
Release: 1%{?dist}
Summary: Provides a simple logging utility for outputting messages
License: Ruby and BSD
URL: https://github.com/ruby/logger
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: ruby >= 2.5.0
BuildRequires: ruby >= 2.5.0
BuildRequires: rubygems-devel
BuildArch: noarch
# end specfile generated dependencies

%description
Provides a simple logging utility for outputting messages.


%package doc
Summary: Documentation for %{name}
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.

%prep
%setup -q -n  %{gem_name}-%{version}

%build
# Create the gem as gem install only works on a gem file
gem build ../%{gem_name}-%{version}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

%files
%dir %{gem_instdir}
%{gem_instdir}/BSDL
%license %{gem_instdir}/COPYING
%{gem_libdir}
%exclude %{gem_cache}
%{gem_spec}

%files doc
%doc %{gem_docdir}
%doc %{gem_instdir}/.document
%doc %{gem_instdir}/.rdoc_options
%doc %{gem_instdir}/README.md

%changelog
* Tue Feb 17 2026 Ondřej Gajdušek <ogajduse@redhat.com> 1.7.0-1
- Add rubygem-logger generated by gem2rpm using the default template

