# Generated from posix-spawn-0.3.13.gem by gem2rpm -*- rpm-spec -*-
# template: nonscl
%global gem_name posix-spawn

#%define rubyabi 1.8

Name: rubygem-%{gem_name}
Version: 0.3.13
Release: 1%{?dist}
Summary: posix_spawnp(2) for ruby
Group: Development/Languages
License: MIT
URL: https://github.com/rtomayko/posix-spawn
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

%if 0%{?el6}
Requires: ruby(abi)
BuildRequires: ruby(abi)
%else
Requires: ruby(release)
BuildRequires: ruby(release)
%endif

Requires: ruby(rubygems)

BuildRequires: ruby(rubygems)
BuildRequires: rubygems-devel
BuildRequires: ruby-devel

Provides: rubygem(%{gem_name}) = %{version}

%description
posix-spawn uses posix_spawnp(2) for faster process spawning.


%package doc
Summary: Documentation for %{name}
Group: Documentation
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.

%prep
gem unpack %{SOURCE0}

%setup -q -D -T -n  %{gem_name}-%{version}

gem spec %{SOURCE0} -l --ruby > %{gem_name}.gemspec

%build
# Create the gem as gem install only works on a gem file
gem build %{gem_name}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

mkdir -p %{buildroot}%{gem_extdir_mri}/lib

mv %{buildroot}%{gem_libdir}/posix_spawn_ext.so \
    %{buildroot}%{gem_extdir_mri}/lib/

#cp -a ./%{gem_extdir_mri}/* %{buildroot}%{gem_extdir_mri}/

# Prevent dangling symlink in -debuginfo (rhbz#878863).
rm -rf %{buildroot}%{gem_instdir}/ext/

mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
        %{buildroot}%{_bindir}/
find %{buildroot}%{gem_instdir}/bin -type f | xargs chmod a+x

%files
%dir %{gem_instdir}
%{_bindir}/posix-spawn-benchmark
%exclude %{gem_instdir}/.gitignore
%{gem_instdir}/bin
%{gem_libdir}
%exclude %{gem_cache}
%{gem_spec}
#%{gem_extdir_mri}

%files doc
%doc %{gem_docdir}
%{gem_instdir}/Gemfile
%doc %{gem_instdir}/README.md
%doc %{gem_instdir}/COPYING
%doc %{gem_instdir}/HACKING
%doc %{gem_instdir}/TODO
%{gem_instdir}/Rakefile
%{gem_instdir}/posix-spawn.gemspec
%exclude %{gem_instdir}/test

%changelog
* Mon Nov 26 2018 Ondřej Pražák <oprazak@redhat.com> 0.3.13-1
- Add rubygem-posix-spawn generated by gem2rpm using the nonscl template

