%global npm_name @spice-project/spice-html5

Name: nodejs-spice-project-spice-html5
Version: 0.2.1
Release: 2%{?dist}
Summary: Spice Javascript client
License: LGPL-3.0-or-later
URL: https://www.spice-space.org
Source0: https://registry.npmjs.org/@spice-project/spice-html5/-/spice-html5-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Makefile %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr TODO %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr apache.conf.sample %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json.in %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr spice-html5.spec.in %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr spice.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr spice.html %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr spice_auto.html %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license COPYING
%license COPYING.LESSER
%doc README

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 0.2.1-2
- Update to 0.2.1

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 0.2.1-1
- Add nodejs-spice-project-spice-html5 generated by npm2rpm using the single strategy

