%global npm_name follow-redirects

Name: nodejs-follow-redirects
Version: 1.16.0
Release: 2%{?dist}
Summary: HTTP and HTTPS modules that follow redirects
License: MIT
URL: https://github.com/follow-redirects/follow-redirects
Source0: https://registry.npmjs.org/follow-redirects/-/follow-redirects-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr debug.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr http.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr https.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 1.16.0-2
- Update to 1.16.0

* Thu Apr 23 2026 Foreman Packaging Automation <packaging@theforeman.org> 1.16.0-1
- Update to 1.16.0

* Sun Aug 03 2025 Foreman Packaging Automation <packaging@theforeman.org> 1.15.11-1
- Update to 1.15.11

* Tue Jul 08 2025 root <root> 1.15.9-1
- Add nodejs-follow-redirects generated by npm2rpm using the single strategy

