%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name follow-redirects

Name: %{?scl_prefix}nodejs-follow-redirects
Version: 1.15.11
Release: 1%{?dist}
Summary: HTTP and HTTPS modules that follow redirects
License: MIT
Group: Development/Libraries
URL: https://github.com/follow-redirects/follow-redirects
Source0: https://registry.npmjs.org/follow-redirects/-/follow-redirects-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr debug.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr http.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr https.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Sun Aug 03 2025 Foreman Packaging Automation <packaging@theforeman.org> 1.15.11-1
- Update to 1.15.11

* Tue Jul 08 2025 root <root> 1.15.9-1
- Add nodejs-follow-redirects generated by npm2rpm using the single strategy

