%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name react-bootstrap-typeahead

Name: %{?scl_prefix}nodejs-react-bootstrap-typeahead
Version: 3.4.1
Release: 2%{?dist}
Summary: React typeahead with Bootstrap styling
License: MIT
Group: Development/Libraries
URL: https://github.com/ericgio/react-bootstrap-typeahead#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
%if 0%{?scl:1}
BuildRequires: %{?scl_prefix_nodejs}npm
%else
BuildRequires: nodejs-packaging
%endif
Requires: %{?scl_prefix}npm(classnames) >= 2.2.0
Requires: %{?scl_prefix}npm(classnames) < 3.0.0
Requires: %{?scl_prefix}npm(create-react-context) >= 0.2.3
Requires: %{?scl_prefix}npm(create-react-context) < 0.3.0
Requires: %{?scl_prefix}npm(escape-string-regexp) >= 1.0.5
Requires: %{?scl_prefix}npm(escape-string-regexp) < 2.0.0
Requires: %{?scl_prefix}npm(invariant) >= 2.2.1
Requires: %{?scl_prefix}npm(invariant) < 3.0.0
Requires: %{?scl_prefix}npm(lodash) >= 4.17.2
Requires: %{?scl_prefix}npm(lodash) < 5.0.0
Requires: %{?scl_prefix}npm(prop-types) >= 15.5.8
Requires: %{?scl_prefix}npm(prop-types) < 16.0.0
Requires: %{?scl_prefix}npm(prop-types-extra) >= 1.0.1
Requires: %{?scl_prefix}npm(prop-types-extra) < 2.0.0
Requires: %{?scl_prefix}npm(react-overlays) >= 0.8.1
Requires: %{?scl_prefix}npm(react-overlays) < 0.9.0
Requires: %{?scl_prefix}npm(react-popper) >= 1.0.0
Requires: %{?scl_prefix}npm(react-popper) < 2.0.0
Requires: %{?scl_prefix}npm(warning) >= 4.0.1
Requires: %{?scl_prefix}npm(warning) < 5.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc CHANGELOG.md
%doc README.md
%doc docs

%changelog
* Fri Oct 04 2019 Eric D. Helms <ericdhelms@gmail.com> - 3.4.1-2
- Update specs to handle SCL

* Tue Mar 19 2019 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 3.4.1-1
- Update to 3.4.1

* Wed Oct 10 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 3.2.3-1
- Add nodejs-react-bootstrap-typeahead generated by npm2rpm using the single strategy
