%global npm_name react-bootstrap-typeahead

Name: nodejs-react-bootstrap-typeahead
Version: 3.2.3
Release: 1%{?dist}
Summary: React typeahead with Bootstrap styling
License: MIT
Group: Development/Libraries
URL: https://github.com/ericgio/react-bootstrap-typeahead#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
Requires: npm(classnames) >= 2.2.0
Requires: npm(classnames) < 3.0.0
Requires: npm(escape-string-regexp) >= 1.0.5
Requires: npm(escape-string-regexp) < 2.0.0
Requires: npm(invariant) >= 2.2.1
Requires: npm(invariant) < 3.0.0
Requires: npm(lodash) >= 4.17.2
Requires: npm(lodash) < 5.0.0
Requires: npm(prop-types) >= 15.5.8
Requires: npm(prop-types) < 16.0.0
Requires: npm(prop-types-extra) >= 1.0.1
Requires: npm(prop-types-extra) < 2.0.0
Requires: npm(react-onclickoutside) >= 6.1.1
Requires: npm(react-onclickoutside) < 7.0.0
Requires: npm(react-overlays) >= 0.8.1
Requires: npm(react-overlays) < 1.0.0
Requires: npm(react-popper) >= 1.0.0
Requires: npm(react-popper) < 2.0.0
Requires: npm(warning) >= 4.0.1
Requires: npm(warning) < 5.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc CHANGELOG.md
%doc README.md
%doc docs

%changelog
* Wed Oct 10 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 3.2.3-1
- Add nodejs-react-bootstrap-typeahead generated by npm2rpm using the single strategy

