%global npm_name react-ace

Name: nodejs-react-ace
Version: 9.5.0
Release: 2%{?dist}
Summary: A react component for Ace Editor
License: MIT
Group: Development/Libraries
URL: https://github.com/securingsincity/react-ace#readme
Source0: https://registry.npmjs.org/ace-builds/-/ace-builds-1.44.0.tgz
Source1: https://registry.npmjs.org/diff-match-patch/-/diff-match-patch-1.0.5.tgz
Source2: https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz
Source3: https://registry.npmjs.org/lodash.get/-/lodash.get-4.4.2.tgz
Source4: https://registry.npmjs.org/lodash.isequal/-/lodash.isequal-4.5.0.tgz
Source5: https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz
Source6: https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz
Source7: https://registry.npmjs.org/prop-types/-/prop-types-15.8.1.tgz
Source8: https://registry.npmjs.org/react-ace/-/react-ace-9.5.0.tgz
Source9: https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz
Source10: nodejs-react-ace-%{version}-package-lock.json
BuildRequires: npm >= 7
BuildRequires: nodejs-packaging
# The prep section runs node directly, so this is needed unconditionally. It
# also works around https://issues.redhat.com/browse/RHEL-137712 on RHEL 10
# before 10.3, where the nodejs major version macro does not resolve without
# node in the buildroot.
BuildRequires: /usr/bin/node
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

Provides: npm(%{npm_name}) = %{version}
Provides: bundled(npm(ace-builds)) = 1.44.0
Provides: bundled(npm(diff-match-patch)) = 1.0.5
Provides: bundled(npm(js-tokens)) = 4.0.0
Provides: bundled(npm(lodash.get)) = 4.4.2
Provides: bundled(npm(lodash.isequal)) = 4.5.0
Provides: bundled(npm(loose-envify)) = 1.4.0
Provides: bundled(npm(object-assign)) = 4.1.1
Provides: bundled(npm(prop-types)) = 15.8.1
Provides: bundled(npm(react-ace)) = 9.5.0
Provides: bundled(npm(react-is)) = 16.13.1
AutoReq: no
AutoProv: no

%define npm_cache_dir npm_cache_%{name}-%{version}-%{release}

%description
%{summary}

%prep
mkdir -p %{npm_cache_dir}
# npm ci installs the tree recorded in the lockfile: every entry carries a
# resolved URL and an integrity hash, and npm serves the tarballs from the
# cache primed here by content hash. No registry access is needed.
for src in %{sources}; do
  case "$src" in
    *.tgz) npm cache add --cache %{npm_cache_dir} "$src" ;;
    *-package-lock.json) cp "$src" package-lock.json ;;
  esac
done

# Derive package.json from the lockfile so the two cannot disagree.
node -e '
const fs = require("fs");
const lock = JSON.parse(fs.readFileSync("package-lock.json"));
fs.writeFileSync("package.json", JSON.stringify({
  name: lock.name,
  version: lock.version,
  dependencies: lock.packages[""].dependencies
}, null, 2) + "\n");
'

%build
npm ci --legacy-peer-deps --offline --cache %{_builddir}/%{npm_cache_dir} --omit optional

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
# npm creates a scope directory for every scope named in the lockfile, including
# scopes whose packages were all omitted, which leaves empty dirs behind.
# -delete implies -depth, so nested empties go bottom-up in a single pass.
find %{buildroot}%{nodejs_sitelib}/%{npm_name} -type d -empty -delete
cp -pfr node_modules/%{npm_name}/dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/logo.png %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/src %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/tsconfig.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/tslint.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/types.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/webpack.config.base.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/webpack.config.development.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/webpack.config.example.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/webpack.config.production.js %{buildroot}%{nodejs_sitelib}/%{npm_name}

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%files
%{nodejs_sitelib}/%{npm_name}
%license node_modules/%{npm_name}/LICENSE
%doc node_modules/%{npm_name}/CHANGELOG.md
%doc node_modules/%{npm_name}/CODE_OF_CONDUCT.md
%doc node_modules/%{npm_name}/CONTRIBUTING.md
%doc node_modules/%{npm_name}/PULL_REQUEST_TEMPLATE.md
%doc node_modules/%{npm_name}/README.md
%doc node_modules/%{npm_name}/docs

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 9.5.0-2
- Update to 9.5.0

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 9.5.0-1
- Add nodejs-react-ace generated by npm2rpm using the bundle strategy

