%global npm_name react-ace

Name: nodejs-react-ace
Version: 6.4.0
Release: 1%{?dist}
Summary: A react component for Ace Editor
License: MIT
Group: Development/Libraries
URL: https://github.com/securingsincity/react-ace#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
Requires: npm(brace) >= 0.11.1
Requires: npm(brace) < 0.12.0
Requires: npm(diff-match-patch) >= 1.0.4
Requires: npm(diff-match-patch) < 2.0.0
Requires: npm(lodash.get) >= 4.4.2
Requires: npm(lodash.get) < 5.0.0
Requires: npm(lodash.isequal) >= 4.5.0
Requires: npm(lodash.isequal) < 5.0.0
Requires: npm(prop-types) >= 15.6.2
Requires: npm(prop-types) < 16.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr coverage %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr logo.png %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr tests %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr types.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr webpack.config.base.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr webpack.config.development.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr webpack.config.example.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr webpack.config.production.js %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc CODE_OF_CONDUCT.md
%doc CONTRIBUTING.md
%doc PULL_REQUEST_TEMPLATE.md
%doc README.md
%doc docs

%changelog
* Thu May 16 2019 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 6.4.0-1
- Add nodejs-react-ace generated by npm2rpm using the single strategy

