%global npm_name @types/react-redux

Name: nodejs-types-react-redux
Version: 7.1.34
Release: 1%{?dist}
Summary: TypeScript definitions for react-redux
License: MIT
Group: Development/Libraries
URL: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-redux
Source0: https://registry.npmjs.org/@babel/runtime/-/runtime-7.29.7.tgz
Source1: https://registry.npmjs.org/@types/hoist-non-react-statics/-/hoist-non-react-statics-3.3.7.tgz
Source2: https://registry.npmjs.org/@types/react/-/react-19.2.15.tgz
Source3: https://registry.npmjs.org/@types/react-redux/-/react-redux-7.1.34.tgz
Source4: https://registry.npmjs.org/csstype/-/csstype-3.2.3.tgz
Source5: https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-3.3.2.tgz
Source6: https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz
Source7: https://registry.npmjs.org/redux/-/redux-4.2.1.tgz
Source8: nodejs-types-react-redux-%{version}-registry.npmjs.org.tgz
BuildRequires: npm >= 7
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

Provides: npm(%{npm_name}) = %{version}
Provides: bundled(npm(@babel/runtime)) = 7.29.7
Provides: bundled(npm(@types/hoist-non-react-statics)) = 3.3.7
Provides: bundled(npm(@types/react)) = 19.2.15
Provides: bundled(npm(@types/react-redux)) = 7.1.34
Provides: bundled(npm(csstype)) = 3.2.3
Provides: bundled(npm(hoist-non-react-statics)) = 3.3.2
Provides: bundled(npm(react-is)) = 16.13.1
Provides: bundled(npm(redux)) = 4.2.1
AutoReq: no
AutoProv: no

%define npm_cache_dir npm_cache_%{name}-%{version}-%{release}

%description
%{summary}

%prep
mkdir -p %{npm_cache_dir}
for tgz in %{sources}; do
  echo $tgz | grep -q registry.npmjs.org || npm cache add --cache %{npm_cache_dir} $tgz
done

%setup -T -q -a 8 -D -n %{npm_cache_dir}

%build
npm install --legacy-peer-deps --offline --cache %{_builddir}/%{npm_cache_dir} --package-lock false --omit optional --install-strategy shallow %{npm_name}@%{version}

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/index.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%files
%{nodejs_sitelib}/%{npm_name}
%license node_modules/%{npm_name}/LICENSE
%doc node_modules/%{npm_name}/README.md

%changelog
* Wed May 27 2026 Nadja Heitmann <nadjah@atix.de> 7.1.34-1
- Add nodejs-types-react-redux generated by npm2rpm using the bundle strategy

