%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name axios

Name: %{?scl_prefix}nodejs-axios
Version: 0.21.4
Release: 1%{?dist}
Summary: Promise based HTTP client for the browser and node
License: MIT
Group: Development/Libraries
URL: https://axios-http.com
Source0: https://registry.npmjs.org/axios/-/axios-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
Requires: npm(follow-redirects) >= 1.14.0
Requires: npm(follow-redirects) < 2.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md
%doc SECURITY.md
%doc UPGRADE_GUIDE.md

%changelog
* Wed Jul 16 2025 Foreman Packaging Automation <packaging@theforeman.org> 0.21.4-1
- Update to 0.21.4

* Tue Jul 08 2025 root <root> 0.21.1-1
- Add nodejs-axios generated by npm2rpm using the single strategy

