%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name deep-diff

Name: %{?scl_prefix}nodejs-deep-diff
Version: 0.3.4
Release: 1%{?dist}
Summary: Javascript utility for calculating deep difference, capturing changes, and applying changes across objects; for nodejs and the browser
License: MIT
Group: Development/Libraries
URL: https://github.com/flitbit/diff#readme
Source0: https://registry.npmjs.org/deep-diff/-/deep-diff-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr releases %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc Readme.md

%changelog
* Thu Jul 03 2025 root <root> 0.3.4-1
- Add nodejs-deep-diff generated by npm2rpm using the single strategy

