%global npm_name deep-diff

Name: nodejs-deep-diff
Version: 0.3.4
Release: 2%{?dist}
Summary: Javascript utility for calculating deep difference, capturing changes, and applying changes across objects; for nodejs and the browser
License: MIT
URL: https://github.com/flitbit/diff#readme
Source0: https://registry.npmjs.org/deep-diff/-/deep-diff-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr releases %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc Readme.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 0.3.4-2
- Update to 0.3.4

* Thu Jul 03 2025 root <root> 0.3.4-1
- Add nodejs-deep-diff generated by npm2rpm using the single strategy

