%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name @novnc/novnc

Name: %{?scl_prefix}nodejs-novnc-novnc
Version: 1.3.0
Release: 1%{?dist}
Summary: An HTML5 VNC client
License: MPL-2.0
Group: Development/Libraries
URL: https://github.com/novnc/noVNC
Source0: https://registry.npmjs.org/@novnc/novnc/-/novnc-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr core %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr vendor %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.txt
%doc AUTHORS
%doc README.md
%doc docs

%changelog
* Thu Jun 26 2025 root <root> 1.3.0-1
- Add nodejs-novnc-novnc generated by npm2rpm using the single strategy

