%global npm_name @novnc/novnc

Name: nodejs-novnc-novnc
Version: 1.3.0
Release: 2%{?dist}
Summary: An HTML5 VNC client
License: MPL-2.0
URL: https://github.com/novnc/noVNC
Source0: https://registry.npmjs.org/@novnc/novnc/-/novnc-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr core %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr vendor %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.txt
%doc AUTHORS
%doc README.md
%doc docs

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 1.3.0-2
- Update to 1.3.0

* Thu Jun 26 2025 root <root> 1.3.0-1
- Add nodejs-novnc-novnc generated by npm2rpm using the single strategy

