%global npm_name react-helmet

Name: nodejs-%{npm_name}
Version: 5.2.0
Release: 1%{?dist}
Summary: A document head manager for React
License: MIT
Group: Development/Libraries
URL: https://github.com/nfl/react-helmet#readme
Source0: https://registry.npmjs.org/react-helmet/-/react-helmet-5.2.0.tgz
Source1: https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz
Source2: https://registry.npmjs.org/react-side-effect/-/react-side-effect-1.1.5.tgz
Source3: https://registry.npmjs.org/deep-equal/-/deep-equal-1.0.1.tgz
Source4: https://registry.npmjs.org/prop-types/-/prop-types-15.6.2.tgz
Source5: https://registry.npmjs.org/exenv/-/exenv-1.2.2.tgz
Source6: https://registry.npmjs.org/shallowequal/-/shallowequal-1.1.0.tgz
Source7: https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz
Source8: https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz
Source9: %{npm_name}-%{version}-registry.npmjs.org.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

Provides: npm(%{npm_name}) = %{version}
Provides: bundled(npm(deep-equal)) = 1.0.1
Provides: bundled(npm(exenv)) = 1.2.2
Provides: bundled(npm(js-tokens)) = 4.0.0
Provides: bundled(npm(loose-envify)) = 1.4.0
Provides: bundled(npm(object-assign)) = 4.1.1
Provides: bundled(npm(prop-types)) = 15.6.2
Provides: bundled(npm(react-helmet)) = 5.2.0
Provides: bundled(npm(react-side-effect)) = 1.1.5
Provides: bundled(npm(shallowequal)) = 1.1.0
AutoReq: no
AutoProv: no

%define npm_cache_dir /tmp/npm_cache_%{name}-%{version}-%{release}

%description
%{summary}

%prep
mkdir -p %{npm_cache_dir}
for tgz in %{sources}; do
  echo $tgz | grep -q registry.npmjs.org || npm cache add --cache %{npm_cache_dir} $tgz
done
%setup -T -q -a 9 -D -n %{npm_cache_dir}

%build
npm install --cache-min Infinity --cache %{npm_cache_dir} --no-shrinkwrap --no-optional --global-style true %{npm_name}@%{version}

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/es %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/test %{buildroot}%{nodejs_sitelib}/%{npm_name}

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%files
%{nodejs_sitelib}/%{npm_name}
%license node_modules/%{npm_name}/LICENSE
%doc node_modules/%{npm_name}/CHANGELOG.md
%doc node_modules/%{npm_name}/README.md

%changelog
* Mon Sep 10 2018 Eric D. Helms <ericdhelms@gmail.com> 5.2.0-1
- Add nodejs-react-helmet generated by npm2rpm using the bundle strategy

