%global npm_name unidiff

Name: nodejs-unidiff
Version: 1.0.4
Release: 2%{?dist}
Summary: diff with unified diff format handling
License: MIT
URL: https://github.com/mvoss9000/unidiff#readme
Source0: https://registry.npmjs.org/unidiff/-/unidiff-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
Requires: npm(diff) >= 5.1.0
Requires: npm(diff) < 6.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr hunk.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc readme.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 1.0.4-2
- Update to 1.0.4

* Wed Jul 09 2025 root <root> 1.0.4-1
- Add nodejs-unidiff generated by npm2rpm using the single strategy

