%global npm_name unidiff
%global enable_tests 1

Name: nodejs-%{npm_name}
Version: 0.0.4
Release: 1%{?dist}
Summary: diff with unified diff format handling
License: MIT
Group: Development/Libraries
URL: https://github.com/mvoss9000/unidiff#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
Requires: npm(diff) >= 2.2.2
Requires: npm(diff) < 4.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package
%nodejs_fixdep diff '>= 2.2.2 < 4.0.0'

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr hunk.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr test %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr unidiff.js %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%if 0%{?enable_tests}
%check
%{nodejs_symlink_deps} --check
%endif

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc readme.md

%changelog
* Wed Oct 31 2018 Ohad Levy <ohadlevy@gmail.com> 0.0.4-1
- Add nodejs-unidiff generated by npm2rpm using the single strategy

