%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name unidiff

Name: %{?scl_prefix}nodejs-unidiff
Version: 1.0.4
Release: 1%{?dist}
Summary: diff with unified diff format handling
License: MIT
Group: Development/Libraries
URL: https://github.com/mvoss9000/unidiff#readme
Source0: https://registry.npmjs.org/unidiff/-/unidiff-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
Requires: npm(diff) >= 5.1.0
Requires: npm(diff) < 6.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr hunk.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc readme.md

%changelog
* Wed Jul 09 2025 root <root> 1.0.4-1
- Add nodejs-unidiff generated by npm2rpm using the single strategy

