%global npm_name redux-thunk

Name: nodejs-redux-thunk
Version: 2.4.2
Release: 2%{?dist}
Summary: Thunk middleware for Redux
License: MIT
URL: https://github.com/reduxjs/redux-thunk
Source0: https://registry.npmjs.org/redux-thunk/-/redux-thunk-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr es %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr extend-redux.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc README.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 2.4.2-2
- Regenerate spec file

* Wed Aug 27 2025 Foreman Packaging Automation <packaging@theforeman.org> 2.4.2-1
- Update to 2.4.2

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 2.2.0-1
- Add nodejs-redux-thunk generated by npm2rpm using the single strategy

