%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name symbol-observable

Name: %{?scl_prefix}nodejs-symbol-observable
Version: 1.2.0
Release: 1%{?dist}
Summary: Symbol
License: MIT
Group: Development/Libraries
URL: https://github.com/blesh/symbol-observable#readme
Source0: https://registry.npmjs.org/symbol-observable/-/symbol-observable-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr es %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license license
%doc CHANGELOG.md
%doc readme.md

%changelog
* Thu Jul 03 2025 root <root> 1.2.0-1
- Add nodejs-symbol-observable generated by npm2rpm using the single strategy

