%global npm_name core-js
%global enable_tests 1

Name: nodejs-%{npm_name}
Version: 2.5.5
Release: 1%{?dist}
Summary: Standard library
License: MIT
Group: Development/Libraries
URL: https://github.com/zloirock/core-js#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr build %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr client %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr core %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr es5 %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr es6 %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr es7 %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr fn %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr library %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr shim.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr stage %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr web %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%if 0%{?enable_tests}
%check
%{nodejs_symlink_deps} --check
%endif

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Thu Apr 26 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 2.5.5-1
- Add nodejs-core-js generated by npm2rpm using the single strategy

