%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name unleash-proxy-client

Name: %{?scl_prefix}nodejs-unleash-proxy-client
Version: 3.7.8
Release: 1%{?dist}
Summary: A browser client that can be used together with Unleash Edge or the Unleash Frontend API
License: Apache-2.0
Group: Development/Libraries
URL: https://github.com/unleash/unleash-proxy-client-js#readme
Source0: https://registry.npmjs.org/tiny-emitter/-/tiny-emitter-2.1.0.tgz
Source1: https://registry.npmjs.org/unleash-proxy-client/-/unleash-proxy-client-3.7.8.tgz
Source2: https://registry.npmjs.org/uuid/-/uuid-9.0.1.tgz
Source3: nodejs-unleash-proxy-client-%{version}-registry.npmjs.org.tgz
BuildRequires: %{?scl_prefix_nodejs}npm
%if 0%{!?scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}
Provides: bundled(npm(tiny-emitter)) = 2.1.0
Provides: bundled(npm(unleash-proxy-client)) = 3.7.8
Provides: bundled(npm(uuid)) = 9.0.1
AutoReq: no
AutoProv: no

%if 0%{?scl:1}
%define npm_cache_dir npm_cache
%else
%define npm_cache_dir /tmp/npm_cache_%{name}-%{version}-%{release}
%endif

%description
%{summary}

%prep
mkdir -p %{npm_cache_dir}
%{?scl:scl enable %{?scl_nodejs} - << \end_of_scl}
for tgz in %{sources}; do
  echo $tgz | grep -q registry.npmjs.org || npm cache add --cache %{npm_cache_dir} $tgz
done
%{?scl:end_of_scl}

%setup -T -q -a 3 -D -n %{npm_cache_dir}

%build
%{?scl:scl enable %{?scl_nodejs} - << \end_of_scl}
npm install --legacy-peer-deps --cache-min Infinity --cache %{?scl:../}%{npm_cache_dir} --no-shrinkwrap --no-optional --global-style true %{npm_name}@%{version}
%{?scl:end_of_scl}

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/build %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/examples %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%files
%{nodejs_sitelib}/%{npm_name}
%license node_modules/%{npm_name}/LICENSE
%doc node_modules/%{npm_name}/README.md

%changelog
* Wed Aug 06 2025 Foreman Packaging Automation <packaging@theforeman.org> 3.7.8-1
- Update to 3.7.8

* Sun Aug 03 2025 Foreman Packaging Automation <packaging@theforeman.org> 3.7.7-1
- Update to 3.7.7

* Wed Jul 09 2025 root <root> 3.7.6-1
- Add nodejs-unleash-proxy-client generated by npm2rpm using the bundle strategy

