%global npm_name unleash-proxy-client

Name: nodejs-unleash-proxy-client
Version: 3.8.0
Release: 2%{?dist}
Summary: A browser client that can be used together with Unleash Edge or the Unleash Frontend API
License: Apache-2.0
URL: https://github.com/unleash/unleash-js-sdk#readme
Source0: https://registry.npmjs.org/unleash-proxy-client/-/unleash-proxy-client-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
Requires: npm(tiny-emitter) >= 2.1.0
Requires: npm(tiny-emitter) < 3.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr build %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr examples %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 3.8.0-2
- Update to 3.8.0

* Wed Apr 29 2026 Foreman Packaging Automation <packaging@theforeman.org> 3.8.0-1
- Update to 3.8.0

* Wed Aug 06 2025 Foreman Packaging Automation <packaging@theforeman.org> 3.7.8-1
- Update to 3.7.8

* Sun Aug 03 2025 Foreman Packaging Automation <packaging@theforeman.org> 3.7.7-1
- Update to 3.7.7

* Wed Jul 09 2025 root <root> 3.7.6-1
- Add nodejs-unleash-proxy-client generated by npm2rpm using the bundle strategy

