%global npm_name @patternfly/react-templates

Name: nodejs-patternfly-react-templates
Version: 1.1.16
Release: 2%{?dist}
Summary: This package provides wrapped component demos for ease of use
License: MIT
URL: https://github.com/patternfly/patternfly-react/tree/main/packages/react-templates#readme
Source0: https://registry.npmjs.org/@patternfly/react-templates/-/react-templates-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
Requires: npm(@patternfly/react-core) >= 5.4.14
Requires: npm(@patternfly/react-core) < 6.0.0
Requires: npm(@patternfly/react-icons) >= 5.4.2
Requires: npm(@patternfly/react-icons) < 6.0.0
Requires: npm(@patternfly/react-styles) >= 5.4.1
Requires: npm(@patternfly/react-styles) < 6.0.0
Requires: npm(@patternfly/react-tokens) >= 5.4.1
Requires: npm(@patternfly/react-tokens) < 6.0.0
Requires: npm(tslib) >= 2.7.0
Requires: npm(tslib) < 3.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr components %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr rollup.config.mjs %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr single-packages.config.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr subpaths.config.json %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 1.1.16-2
- Regenerate spec file

* Sun Jan 18 2026 Foreman Packaging Automation <packaging@theforeman.org> 1.1.16-1
- Update to 1.1.16

* Wed Jan 07 2026 MariaAga <mariaaga@redhat.com> 1.1.8-1
- Add nodejs-patternfly-react-templates generated by npm2rpm using the single strategy

