#!/bin/bash -e

GEM_NAME=$1
PACKAGE_NAME=rubygem-$GEM_NAME
TEMPLATE_NAME=$2
TEMPLATE=$(pwd)/gem2rpm/$TEMPLATE_NAME.spec.erb
TITO_TAG=$3
DISTRO=${TITO_TAG##*-}
PACKAGE_SUBDIR=$4
ROOT=$(git rev-parse --show-toplevel)

if [[ -z $PACKAGE_DIR ]] ; then
	if [[ $TITO_TAG == foreman-plugins-* ]] ; then
		PACKAGE_SUBDIR="plugins"
	elif [[ $TITO_TAG == katello-* ]] ; then
		PACKAGE_SUBDIR="katello"
	else
		PACKAGE_SUBDIR="foreman"
	fi
fi

PACKAGE_DIR=packages/$PACKAGE_SUBDIR/$PACKAGE_NAME

if [[ -f "${PACKAGE_DIR}/${PACKAGE_NAME}.spec" ]]; then
	echo "Detected update..."
	UPDATE=true
else
	UPDATE=false
fi

usage() {
	echo "Usage: $0 GEM_NAME TEMPLATE TITO_TAG [PACKAGE_SUBDIR]"
	echo "Valid templates: $(ls gem2rpm | sed 's/.spec.erb//' | tr '\n' ' ')"
	python -c "import ConfigParser ; c = ConfigParser.ConfigParser() ; c.read('rel-eng/tito.props') ; print 'Tito tags: ' + ' '.join(s for s in c.sections() if s not in ('requirements', 'buildconfig', 'builder'))"
	exit 1
}

generate_gem_package() {
	if [[ $UPDATE == true ]] ; then
		CHANGELOG=$(mktemp)
		sed -n '/%changelog/,$p' $PACKAGE_DIR/$PACKAGE_NAME.spec > $CHANGELOG
		git rm -r $PACKAGE_DIR
	fi
	mkdir $PACKAGE_DIR
	pushd $PACKAGE_DIR
	gem2rpm -o $PACKAGE_NAME.spec --fetch $GEM_NAME -t $TEMPLATE
	sed -i 's/\s\+$//' $PACKAGE_NAME.spec
	git annex add *.gem

	VERSION=$(rpmspec --srpm -q --queryformat="%{version}-%{release}" --undefine=dist $PACKAGE_NAME.spec)

	if [[ $UPDATE == true ]]; then
		cat $CHANGELOG >> $PACKAGE_NAME.spec
		sed -i '/^%changelog/,/^%changelog/{0,//!d}' $PACKAGE_NAME.spec
		rm $CHANGELOG
		CHANGELOG="- Update to $VERSION"
	else
		CHANGELOG="- Add $PACKAGE_NAME generated by gem2rpm using the $TEMPLATE_NAME template"
	fi
	echo "$CHANGELOG" | $ROOT/add_changelog.sh $PACKAGE_NAME.spec

	git add $PACKAGE_NAME.spec
	popd
}

add_to_tito_props() {
	# Get tito.props whitelists and add node package
	original_locale=$LC_COLLATE
	export LC_COLLATE=en_GB
	local current_whitelist=$(crudini --get rel-eng/tito.props $TITO_TAG whitelist)
	local whitelist=$(echo "$current_whitelist $PACKAGE_NAME" | tr " " "\n" | sort -u)
	crudini --set rel-eng/tito.props $TITO_TAG whitelist "$whitelist"
	export LC_COLLATE=$original_locale
	git add rel-eng/tito.props
}

add_gem_to_comps() {
	if [[ $TEMPLATE_NAME == "nonscl" ]] || [[ $TEMPLATE_NAME == "smart_proxy_plugin" ]] ; then
		local comps_scl="nonscl"
		local comps_package="${PACKAGE_NAME}"
	else
		local comps_scl=""
		local comps_package="tfm-${PACKAGE_NAME}"
	fi

	# TODO: figure this out for katello
	if [[ $TITO_TAG == foreman-plugins-* ]]; then
		local comps_file="foreman-plugins"
	else
		local comps_file="foreman"
	fi

	./add_to_comps.rb comps/comps-${comps_file}-${DISTRO}.xml $comps_package $comps_scl
	./comps_doc.sh
	git add comps/
}

# Main script

if [[ -z $GEM_NAME ]] || [[ -z $TEMPLATE_NAME ]] || [[ -z $TITO_TAG ]]; then
	usage
fi

if [[ ! -e $TEMPLATE ]] ; then
	echo "Template $TEMPLATE does not exist."
	usage
	exit 1
fi

generate_gem_package
if [[ $UPDATE == true ]] ; then
	VERSION=$(rpmspec --srpm -q --queryformat="%{version}-%{release}" --undefine=dist $PACKAGE_DIR/$PACKAGE_NAME.spec)
	git commit -m "Bump $PACKAGE_NAME to $VERSION"
else
	add_to_tito_props
	add_gem_to_comps
	git commit -m "Add $PACKAGE_NAME package"
fi
