#!/usr/bin/env python3

import yaml

try:
    from yaml import CLoader as Loader
except ImportError:
    from yaml import Loader

def main():
    with open('package_manifest.yaml') as f:
        manifest = yaml.load(f.read(), Loader=Loader)

    print(' '.join(manifest['all']['vars']['all_tags']))

if __name__ == '__main__':
    main()
