#!/usr/bin/env ruby

require "json"

dependencies = JSON.load_file('package-lock.json')['dependencies']

npm_module_name_version_map = dependencies.map do |name, metadata|
  {"name": name, "version": metadata['version']}
end

puts npm_module_name_version_map.to_json
