#!/bin/bash

set -e

PACKAGES=("$@")

remove_packages() {
	git rm -r ${PACKAGES[@]/#/packages\/*\/}
}

remove_from_manifest() {
	./remove_host "${PACKAGES[@]}"
}

remove_from_comps() {
	for comps in comps/comps-*.xml ; do
		./remove_from_comps "$comps" "${PACKAGES[@]}"
	done
}

remove_packages
remove_from_manifest
remove_from_comps
