%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name jquery-ujs

Name: %{?scl_prefix}nodejs-jquery-ujs
Version: 1.2.0
Release: 1%{?dist}
Summary: Ruby on Rails unobtrusive scripting adapter for jQuery, for npm
License: MIT
Group: Development/Libraries
URL: https://github.com/shakacode/jquery-ujs
Source0: https://registry.npmjs.org/jquery-ujs/-/jquery-ujs-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
Requires: npm(jquery) >= 1.8.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Gemfile.lock %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr script %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr test %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license MIT-LICENSE
%doc CONTRIBUTING.md
%doc README.md

%changelog
* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 1.2.0-1
- Add nodejs-jquery-ujs generated by npm2rpm using the single strategy

