%global npm_name jquery-ujs

Name: nodejs-jquery-ujs
Version: 1.2.3
Release: 2%{?dist}
Summary: Unobtrusive scripting adapter for jQuery
License: MIT
URL: https://github.com/rails/jquery-ujs#readme
Source0: https://registry.npmjs.org/jquery-ujs/-/jquery-ujs-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license MIT-LICENSE
%doc CONTRIBUTING.md
%doc README.md
%doc RELEASE.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 1.2.3-2
- Update to 1.2.3

* Sun Aug 31 2025 Foreman Packaging Automation <packaging@theforeman.org> 1.2.3-1
- Update to 1.2.3

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 1.2.0-1
- Add nodejs-jquery-ujs generated by npm2rpm using the single strategy

