%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name jquery-ujs

Name: %{?scl_prefix}nodejs-jquery-ujs
Version: 1.2.3
Release: 1%{?dist}
Summary: Unobtrusive scripting adapter for jQuery
License: MIT
Group: Development/Libraries
URL: https://github.com/rails/jquery-ujs#readme
Source0: https://registry.npmjs.org/jquery-ujs/-/jquery-ujs-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license MIT-LICENSE
%doc CONTRIBUTING.md
%doc README.md
%doc RELEASE.md

%changelog
* Sun Aug 31 2025 Foreman Packaging Automation <packaging@theforeman.org> 1.2.3-1
- Update to 1.2.3

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 1.2.0-1
- Add nodejs-jquery-ujs generated by npm2rpm using the single strategy

