# template: default
%global gem_name fugit

Name: rubygem-%{gem_name}
Version: 1.13.0
Release: 2%{?dist}
Summary: time tools for flor
License: MIT
URL: https://github.com/floraison/fugit
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: ruby
BuildRequires: ruby
BuildRequires: rubygems-devel
BuildArch: noarch
# end specfile generated dependencies

%description
Time tools for flor and the floraison project. Cron parsing and occurrence
computing. Timestamps and more.


%package doc
Summary: Documentation for %{name}
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.

%prep
%setup -q -n  %{gem_name}-%{version}

%build
# Create the gem as gem install only works on a gem file
gem build ../%{gem_name}-%{version}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

%files
%dir %{gem_instdir}
%license %{gem_instdir}/LICENSE.txt
%{gem_libdir}
%exclude %{gem_cache}
%{gem_spec}

%files doc
%doc %{gem_docdir}
%doc %{gem_instdir}/CREDITS.md
%doc %{gem_instdir}/CHANGELOG.md
%doc %{gem_instdir}/README.md
%exclude %{gem_instdir}/fugit.gemspec

%changelog
* Tue Jul 28 2026 Zach Huntington-Meath <zhunting@redhat.com> - 1.13.0-2
- Rebuild for EL10

* Sun Jul 12 2026 Foreman Packaging Automation <packaging@theforeman.org> - 1.13.0-1
- Update to 1.13.0

* Wed Jul 01 2026 Foreman Packaging Automation <packaging@theforeman.org> - 1.12.3-1
- Update to 1.12.3

* Mon Jun 29 2026 Foreman Packaging Automation <packaging@theforeman.org> - 1.12.2-1
- Update to 1.12.2

* Tue Mar 21 2023 Adam Ruzicka <aruzicka@redhat.com> 1.8.1-1
- Add rubygem-fugit generated by gem2rpm using the default template
