%global npm_name react-dnd

Name: nodejs-react-dnd
Version: 7.6.0
Release: 1%{?dist}
Summary: Drag and Drop for React
License: MIT
Group: Development/Libraries
URL: https://github.com/react-dnd/react-dnd#readme
Source0: https://registry.npmjs.org/react-dnd/-/react-dnd-7.6.0.tgz
Source1: https://registry.npmjs.org/@types/hoist-non-react-statics/-/@types/hoist-non-react-statics-3.3.1.tgz
Source2: https://registry.npmjs.org/dnd-core/-/dnd-core-7.6.0.tgz
Source3: https://registry.npmjs.org/invariant/-/invariant-2.2.4.tgz
Source4: https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-3.3.0.tgz
Source5: https://registry.npmjs.org/shallowequal/-/shallowequal-1.1.0.tgz
Source6: https://registry.npmjs.org/asap/-/asap-2.0.6.tgz
Source7: https://registry.npmjs.org/@types/react/-/@types/react-16.8.19.tgz
Source8: https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz
Source9: https://registry.npmjs.org/redux/-/redux-4.0.1.tgz
Source10: https://registry.npmjs.org/react-is/-/react-is-16.8.6.tgz
Source11: https://registry.npmjs.org/@types/prop-types/-/@types/prop-types-15.7.1.tgz
Source12: https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz
Source13: https://registry.npmjs.org/csstype/-/csstype-2.6.5.tgz
Source14: https://registry.npmjs.org/symbol-observable/-/symbol-observable-1.2.0.tgz
Source15: %{name}-%{version}-registry.npmjs.org.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

Provides: npm(%{npm_name}) = %{version}
Provides: bundled(npm(@types/hoist-non-react-statics)) = 3.3.1
Provides: bundled(npm(@types/prop-types)) = 15.7.1
Provides: bundled(npm(@types/react)) = 16.8.19
Provides: bundled(npm(asap)) = 2.0.6
Provides: bundled(npm(csstype)) = 2.6.5
Provides: bundled(npm(dnd-core)) = 7.6.0
Provides: bundled(npm(hoist-non-react-statics)) = 3.3.0
Provides: bundled(npm(invariant)) = 2.2.4
Provides: bundled(npm(js-tokens)) = 4.0.0
Provides: bundled(npm(loose-envify)) = 1.4.0
Provides: bundled(npm(react-dnd)) = 7.6.0
Provides: bundled(npm(react-is)) = 16.8.6
Provides: bundled(npm(redux)) = 4.0.1
Provides: bundled(npm(shallowequal)) = 1.1.0
Provides: bundled(npm(symbol-observable)) = 1.2.0
AutoReq: no
AutoProv: no

%define npm_cache_dir /tmp/npm_cache_%{name}-%{version}-%{release}

%description
%{summary}

%prep
mkdir -p %{npm_cache_dir}
for tgz in %{sources}; do
  echo $tgz | grep -q registry.npmjs.org || npm cache add --cache %{npm_cache_dir} $tgz
done
%setup -T -q -a 15 -D -n %{npm_cache_dir}

%build
npm install --cache-min Infinity --cache %{npm_cache_dir} --no-shrinkwrap --no-optional --global-style true %{npm_name}@%{version}

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/tsconfig.cjs.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/tsconfig.esm.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%files
%{nodejs_sitelib}/%{npm_name}
%license node_modules/%{npm_name}/LICENSE
%doc node_modules/%{npm_name}/README.md

%changelog
* Tue Jun 11 2019 Ondřej Ezr <oezr@redhat.com> 7.6.0-1
- Add nodejs-react-dnd generated by npm2rpm using the bundle strategy

