%global npm_name file-saver

Name: nodejs-file-saver
Version: 2.0.5
Release: 2%{?dist}
Summary: An HTML5 saveAs() FileSaver implementation
License: MIT
URL: https://github.com/eligrey/FileSaver.js#readme
Source0: https://registry.npmjs.org/file-saver/-/file-saver-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc CHANGELOG.md
%doc README.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 2.0.5-2
- Regenerate spec file

* Wed Jul 23 2025 Foreman Packaging Automation <packaging@theforeman.org> 2.0.5-1
- Update to 2.0.5

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 2.0.1-1
- Add nodejs-file-saver generated by npm2rpm using the single strategy

