%global npm_name typescript

Name: nodejs-typescript
Version: 5.8.2
Release: 1%{?dist}
Summary: TypeScript is a language for application scale JavaScript development
License: Apache-2.0
URL: https://www.typescriptlang.org/
Source0: https://registry.npmjs.org/typescript/-/typescript-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr bin %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

mkdir -p %{buildroot}%{_bindir}
chmod 0755 %{buildroot}%{nodejs_sitelib}/%{npm_name}/bin/tsc
ln -sf %{nodejs_sitelib}/%{npm_name}/bin/tsc %{buildroot}%{_bindir}/tsc
chmod 0755 %{buildroot}%{nodejs_sitelib}/%{npm_name}/bin/tsserver
ln -sf %{nodejs_sitelib}/%{npm_name}/bin/tsserver %{buildroot}%{_bindir}/tsserver

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%{_bindir}/tsc
%{_bindir}/tsserver
%license LICENSE.txt
%doc README.md
%doc SECURITY.md
%doc ThirdPartyNoticeText.txt

%changelog
* Mon Mar 23 2026 Nadja Heitmann <nadjah@atix.de> 5.8.2-1
- Add nodejs-typescript generated by npm2rpm using the single strategy

