%global npm_name react-router-dom
%global enable_tests 0

Name: nodejs-%{npm_name}
Version: 4.2.2
Release: 1%{?dist}
Summary: DOM bindings for React Router
License: MIT
Group: Development/Libraries
URL: FIXME
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch:  noarch
ExclusiveArch: %{nodejs_arches} noarch

%{?nodejs_find_provides_and_requires}

%define npm_cache_dir /tmp/npm_cache_%{name}-%{version}-%{release}
%description
%{summary}

%prep
%setup -q -n package

%build


%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr BrowserRouter.js HashRouter.js Link.js MemoryRouter.js NavLink.js Prompt.js README.md Redirect.js Route.js Router.js StaticRouter.js Switch.js es index.js matchPath.js package.json umd withRouter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}


%nodejs_symlink_deps

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%if 0%{?enable_tests}
%check
%{nodejs_symlink_deps} --check
%endif

%files
%{nodejs_sitelib}/%{npm_name}


%doc README.md

%changelog
* Thu Mar 22 2018 Walden Raines <walden@redhat.com> 4.2.2-1
- Add nodejs-react-router-dom generated by npm2rpm using the single strategy

* Thu Mar 22 2018 author@example.com <Author Name> - 4.2.2-1
- First release
