%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name react-router-dom

Name: %{?scl_prefix}nodejs-react-router-dom
Version: 5.1.2
Release: 1%{?dist}
Summary: DOM bindings for React Router
License: MIT
Group: Development/Libraries
URL: https://github.com/ReactTraining/react-router#readme
Source0: https://registry.npmjs.org/react-router-dom/-/react-router-dom-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
Requires: npm(@babel/runtime) >= 7.1.2
Requires: npm(@babel/runtime) < 8.0.0
Requires: npm(history) >= 4.9.0
Requires: npm(history) < 5.0.0
Requires: npm(loose-envify) >= 1.3.1
Requires: npm(loose-envify) < 2.0.0
Requires: npm(prop-types) >= 15.6.2
Requires: npm(prop-types) < 16.0.0
Requires: npm(react-router) = 5.1.2
Requires: npm(tiny-invariant) >= 1.0.2
Requires: npm(tiny-invariant) < 2.0.0
Requires: npm(tiny-warning) >= 1.0.0
Requires: npm(tiny-warning) < 2.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr BrowserRouter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr HashRouter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Link.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr MemoryRouter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr NavLink.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Prompt.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Redirect.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Route.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Router.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr StaticRouter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Switch.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr cjs %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr es %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr esm %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr generatePath.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr matchPath.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr umd %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr warnAboutDeprecatedCJSRequire.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr withRouter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 5.1.2-1
- Add nodejs-react-router-dom generated by npm2rpm using the single strategy

