#!/bin/sh
# postinst script for foreman-*
#
# see: dh_installdeb(1)

if [ ! -z "${DEBUG}" ]; then
  set -x
else
  set -e
fi

. /usr/share/debconf/confmodule

# if this script aborts with an error dpkg can
# hang if daemons have been started
trap db_stop EXIT

# Update gems
cd /usr/share/foreman
if [ ! -z "${DEBUG}" ]; then
  bundle update --local
else
  bundle update --local 2>&1 >/dev/null
fi

# Own all the core files
chown -Rf foreman:foreman '/usr/share/foreman'

#DEBHELPER#

exit 0
