%global npm_name path-browserify

Name: nodejs-path-browserify
Version: 1.0.1
Release: 2%{?dist}
Summary: the path module from node core for browsers
License: MIT
URL: https://github.com/browserify/path-browserify
Source0: https://registry.npmjs.org/path-browserify/-/path-browserify-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr test %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md
%doc security.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 1.0.1-2
- Update to 1.0.1

* Wed Dec 13 2023 Evgeni Golov 1.0.1-1
- Add nodejs-path-browserify generated by npm2rpm using the single strategy

