%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name path-browserify

Name: %{?scl_prefix}nodejs-path-browserify
Version: 1.0.1
Release: 1%{?dist}
Summary: the path module from node core for browsers
License: MIT
Group: Development/Libraries
URL: https://github.com/browserify/path-browserify
Source0: https://registry.npmjs.org/path-browserify/-/path-browserify-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr test %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md
%doc security.md

%changelog
* Wed Dec 13 2023 Evgeni Golov 1.0.1-1
- Add nodejs-path-browserify generated by npm2rpm using the single strategy

