%global npm_name react-debounce-input
%global enable_tests 1

Name: nodejs-%{npm_name}
Version: 3.2.0
Release: 1%{?dist}
Summary: React component that renders Input with debounced onChange
License: MIT
Group: Development/Libraries
URL: https://github.com/nkbt/react-debounce-input
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
Requires: npm(lodash.debounce) >= 4
Requires: npm(lodash.debounce) < 5
Requires: npm(prop-types) >= 15
Requires: npm(prop-types) < 16
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr build %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%if 0%{?enable_tests}
%check
%{nodejs_symlink_deps} --check
%endif

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Wed May 16 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 3.2.0-1
- Add nodejs-react-debounce-input generated by npm2rpm using the single strategy

