%global npm_name react-debounce-input

Name: nodejs-react-debounce-input
Version: 3.3.0
Release: 2%{?dist}
Summary: React component that renders Input with debounced onChange
License: MIT
URL: https://github.com/nkbt/react-debounce-input
Source0: https://registry.npmjs.org/react-debounce-input/-/react-debounce-input-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
Requires: npm(lodash.debounce) >= 4.0.0
Requires: npm(lodash.debounce) < 5.0.0
Requires: npm(prop-types) >= 15.8.1
Requires: npm(prop-types) < 16.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr build %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 3.3.0-2
- Update to 3.3.0

* Sun Aug 31 2025 Foreman Packaging Automation <packaging@theforeman.org> 3.3.0-1
- Update to 3.3.0

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 3.2.0-1
- Add nodejs-react-debounce-input generated by npm2rpm using the single strategy

