#!/usr/bin/env ruby

# check if production install
if __FILE__.include?('sbin')
  UTILS_PATH='/usr/share/katello'
else
  UTILS_PATH=File.expand_path('..', __FILE__)
end

require File.join(UTILS_PATH, 'restore.rb')

katello_restore = KatelloUtilities::Restore.new("foreman-proxy-content", "katello")

if katello_restore.accepted_scenarios.include? katello_restore.last_scenario
  katello_restore.run
else
  STDOUT.puts katello_restore.error_message
end
