%global npm_name @patternfly/react-styles

Name: nodejs-patternfly-react-styles
Version: 5.4.1
Release: 2%{?dist}
Summary: CSS-in-JS class maps and utilities for PatternFly
License: MIT
URL: https://www.npmjs.com/package/@patternfly/react-styles
Source0: https://registry.npmjs.org/@patternfly/react-styles/-/react-styles-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr __mocks__ %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr scripts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 5.4.1-2
- Regenerate spec file

* Wed Jul 23 2025 Foreman Packaging Automation <packaging@theforeman.org> 5.4.1-1
- Update to 5.4.1

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 5.2.0-1
- Add nodejs-patternfly-react-styles generated by npm2rpm using the single strategy

