%global npm_name bootstrap-select
%global enable_tests 0

Name: nodejs-%{npm_name}
Version: 1.12.2
Release: 1%{?dist}
Summary: Bootstrap-select is a jQuery plugin that utilizes Bootstrap's dropdown
License: MIT
Group: Development/Libraries
URL: http://silviomoreto.github.io/bootstrap-select
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch:  noarch
ExclusiveArch: %{nodejs_arches} noarch

%{?nodejs_find_provides_and_requires}

%define npm_cache_dir /tmp/npm_cache_%{name}-%{version}-%{release}
%description
%{summary}

%prep
%setup -q -n package

%build


%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr .github .npmignore CHANGELOG.md CONTRIBUTING.md Gruntfile.js LICENSE README.md bower.json composer.json dist docs js less nuget package.json sass test.html %{buildroot}%{nodejs_sitelib}/%{npm_name}


%nodejs_symlink_deps

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%if 0%{?enable_tests}
%check
%{nodejs_symlink_deps} --check
%endif

%files
%{nodejs_sitelib}/%{npm_name}

%license LICENSE
%doc CHANGELOG.md
%doc CONTRIBUTING.md
%doc README.md

%changelog
* Thu Mar 22 2018 Walden Raines <walden@redhat.com> 1.12.2-1
- Add nodejs-bootstrap-select generated by npm2rpm using the single strategy

* Thu Mar 22 2018 author@example.com <Author Name> - 1.12.2-1
- First release
