%global npm_name buffer

Name: nodejs-buffer
Version: 5.7.1
Release: 4%{?dist}
Summary: Node
License: MIT
URL: https://github.com/feross/buffer
Source0: https://registry.npmjs.org/buffer/-/buffer-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
Requires: npm(base64-js) >= 1.3.1
Requires: npm(base64-js) < 2.0.0
Requires: npm(ieee754) >= 1.1.13
Requires: npm(ieee754) < 2.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc AUTHORS.md
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 5.7.1-4
- Update to 5.7.1

* Fri Dec 19 2025 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 5.7.1-3
- Rewrite to use single style packaging

* Thu Feb 01 2024 Eric D. Helms <ericdhelms@gmail.com> - 5.7.1-2
- Use --legacy-peer-deps during npm install

* Mon Jan 29 2024 Evgeni Golov 5.7.1-1
- Add nodejs-buffer generated by npm2rpm using the bundle strategy
