# template: default
%global gem_name snaky_hash

Name: rubygem-%{gem_name}
Version: 2.0.7
Release: 2%{?dist}
Summary: A very snaky hash
License: MIT
URL: https://gitlab.com/oauth-xx/snaky_hash
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: ruby >= 2.2.0
BuildRequires: ruby >= 2.2.0
BuildRequires: rubygems-devel
BuildArch: noarch
# end specfile generated dependencies

%description
A Hashie::Mash joint to make #snakelife better.


%package doc
Summary: Documentation for %{name}
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.

%prep
%setup -q -n  %{gem_name}-%{version}

%build
# Create the gem as gem install only works on a gem file
gem build ../%{gem_name}-%{version}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

%files
%dir %{gem_instdir}
%{gem_instdir}/certs
%exclude %{gem_instdir}/CODE_OF_CONDUCT.md
%license %{gem_instdir}/LICENSE.md
%license %{gem_instdir}/MIT.md
%doc %{gem_instdir}/SECURITY.md
%{gem_libdir}
%{gem_instdir}/sig
%exclude %{gem_cache}
%{gem_spec}

%files doc
%doc %{gem_docdir}
%doc %{gem_instdir}/CHANGELOG.md
%doc %{gem_instdir}/CITATION.cff
%doc %{gem_instdir}/CONTRIBUTING.md
%doc %{gem_instdir}/FUNDING.md
%doc %{gem_instdir}/README.md
%doc %{gem_instdir}/RUBOCOP.md

%changelog
* Mon Jul 27 2026 Zach Huntington-Meath <zhunting@redhat.com> - 2.0.7-2
- rebuilt

* Sun Jul 19 2026 Foreman Packaging Automation <packaging@theforeman.org> - 2.0.7-1
- Update to 2.0.7

* Wed Jun 17 2026 Foreman Packaging Automation <packaging@theforeman.org> - 2.0.6-1
- Update to 2.0.6

* Wed Jun 10 2026 Foreman Packaging Automation <packaging@theforeman.org> - 2.0.5-1
- Update to 2.0.5

* Wed May 28 2025 Foreman Packaging Automation <packaging@theforeman.org> - 2.0.3-1
- Update to 2.0.3

* Mon Oct 31 2022 Eric D. Helms <ericdhelms@gmail.com> 2.0.1-1
- Add rubygem-snaky_hash generated by gem2rpm using the default template

