%global npm_name diff

Name: nodejs-diff
Version: 5.2.2
Release: 2%{?dist}
Summary: A JavaScript text diff implementation
License: BSD-3-Clause
URL: https://github.com/kpdecker/jsdiff#readme
Source0: https://registry.npmjs.org/diff/-/diff-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr runtime.js %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CONTRIBUTING.md
%doc README.md
%doc release-notes.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 5.2.2-2
- Regenerate spec file

* Tue Apr 14 2026 Zach Huntington-Meath <zhunting@redhat.com> 5.2.2-1
- Update to 5.2.2

* Wed Jul 09 2025 root <root> 5.2.0-1
- Update to 5.2.0

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 4.0.1-1
- Add nodejs-diff generated by npm2rpm using the single strategy

