%define rbname tzinfo
%define version 0.3.32
%define release 1

Summary: Daylight-savings aware timezone library
Name: rubygem-%{rbname}

Version: %{version}
Release: %{release}%{dist}
Group: Development/Ruby
License: Distributable
URL: http://tzinfo.rubyforge.org/
Source0: http://rubygems.org/downloads/%{rbname}-%{version}.gem
BuildRoot: %{_tmppath}/%{name}-%{version}-root
Requires: ruby 
Requires: rubygems >= 1.8.10
BuildRequires: ruby 
BuildRequires: rubygems >= 1.8.10
BuildArch: noarch
Provides: rubygem(tzinfo) = %{version}

%define gemdir /usr/lib/ruby/gems/1.8
%define gembuilddir %{buildroot}%{gemdir}

%description
TZInfo is a Ruby library that uses the standard tz (Olson) database to provide
daylight savings aware transformations between times in different time zones.


%prep
%setup -T -c

%build

%install
%{__rm} -rf %{buildroot}
mkdir -p %{gembuilddir}
gem install --local --install-dir %{gembuilddir} --force %{SOURCE0}

%clean
%{__rm} -rf %{buildroot}

%files
%defattr(-, root, root)
%doc %{gemdir}/gems/tzinfo-0.3.32/CHANGES
%{gemdir}/gems/tzinfo-0.3.32/LICENSE
%{gemdir}/gems/tzinfo-0.3.32/Rakefile
%doc %{gemdir}/gems/tzinfo-0.3.32/README
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/indexes/timezones.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/indexes/countries.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Ouagadougou.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/El_Aaiun.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Ndjamena.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Johannesburg.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Blantyre.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Lusaka.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Dakar.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Niamey.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Tripoli.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Porto__m__Novo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Brazzaville.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Algiers.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Bissau.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Libreville.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Freetown.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Khartoum.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Monrovia.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Lubumbashi.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Maseru.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Lome.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Bujumbura.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Cairo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Ceuta.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Luanda.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Maputo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Sao_Tome.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Windhoek.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Dar_es_Salaam.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Juba.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Nouakchott.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Mogadishu.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Nairobi.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Mbabane.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Abidjan.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Addis_Ababa.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Bamako.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Malabo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Gaborone.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Kigali.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Kinshasa.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Harare.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Tunis.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Asmara.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Timbuktu.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Lagos.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Douala.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Bangui.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Kampala.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Conakry.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Asmera.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Casablanca.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Djibouti.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Accra.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Africa/Banjul.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Broken_Hill.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Canberra.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Hobart.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Victoria.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/West.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Lord_Howe.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Perth.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Darwin.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Brisbane.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Lindeman.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Adelaide.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Queensland.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Melbourne.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Currie.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Eucla.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/North.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Tasmania.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Sydney.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/South.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/NSW.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/Yancowinna.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/ACT.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Australia/LHI.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/US/Pacific.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/US/Michigan.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/US/Samoa.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/US/Eastern.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/US/Aleutian.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/US/Pacific__m__New.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/US/Hawaii.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/US/Arizona.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/US/Central.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/US/Indiana__m__Starke.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/US/Mountain.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/US/East__m__Indiana.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/US/Alaska.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Guadalcanal.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Tarawa.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Fiji.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Funafuti.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Ponape.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Auckland.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Tahiti.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Easter.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Noumea.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Efate.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Truk.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Wake.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Guam.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Yap.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Nauru.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Midway.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Port_Moresby.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Rarotonga.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Majuro.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Enderbury.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Samoa.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Niue.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Tongatapu.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Palau.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Honolulu.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Chatham.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Kwajalein.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Gambier.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Fakaofo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Pitcairn.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Apia.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Norfolk.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Kiritimati.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Kosrae.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Wallis.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Pago_Pago.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Galapagos.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Marquesas.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Johnston.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Saipan.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Chuuk.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Pacific/Pohnpei.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Simferopol.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Dublin.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Kaliningrad.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Bucharest.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Minsk.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Istanbul.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Riga.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Tirane.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/San_Marino.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Volgograd.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Lisbon.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Andorra.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Copenhagen.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/London.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Vaduz.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Tiraspol.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Jersey.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Rome.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Stockholm.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Warsaw.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Belgrade.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Helsinki.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Gibraltar.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Isle_of_Man.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Budapest.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Moscow.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Amsterdam.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Oslo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Vienna.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Paris.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Bratislava.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Belfast.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Athens.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Prague.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Nicosia.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Vatican.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Luxembourg.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Vilnius.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Skopje.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Malta.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Kiev.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Madrid.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Mariehamn.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Guernsey.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Sofia.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Tallinn.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Uzhgorod.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Ljubljana.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Brussels.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Chisinau.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Samara.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Zurich.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Podgorica.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Sarajevo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Zagreb.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Zaporozhye.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Berlin.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Europe/Monaco.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Indian/Antananarivo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Indian/Christmas.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Indian/Comoro.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Indian/Reunion.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Indian/Kerguelen.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Indian/Mauritius.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Indian/Mayotte.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Indian/Chagos.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Indian/Maldives.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Indian/Cocos.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Indian/Mahe.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Canada/Newfoundland.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Canada/Pacific.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Canada/Atlantic.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Canada/Eastern.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Canada/Central.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Canada/Yukon.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Canada/East__m__Saskatchewan.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Canada/Saskatchewan.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Canada/Mountain.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__m__11.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__m__1.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__m__3.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__p__1.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__m__5.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__p__3.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__m__7.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__p__5.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__m__9.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__p__7.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/UCT.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__p__9.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__p__10.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__m__13.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__p__12.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__m__0.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__m__2.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__p__0.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__m__4.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__p__2.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__m__6.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__p__4.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__m__8.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__p__6.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/UTC.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__p__8.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/Zulu.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__m__10.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__m__12.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__m__14.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT__p__11.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/GMT0.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/Universal.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Etc/Greenwich.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Brazil/DeNoronha.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Brazil/West.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Brazil/Acre.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Brazil/East.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Chile/Continental.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Chile/EasterIsland.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Mexico/General.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Mexico/BajaNorte.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Mexico/BajaSur.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Mideast/Riyadh87.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Mideast/Riyadh88.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Mideast/Riyadh89.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Atlantic/Cape_Verde.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Atlantic/Canary.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Atlantic/South_Georgia.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Atlantic/Bermuda.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Atlantic/Reykjavik.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Atlantic/Stanley.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Atlantic/Faeroe.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Atlantic/Jan_Mayen.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Atlantic/Madeira.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Atlantic/St_Helena.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Atlantic/Azores.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Atlantic/Faroe.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Argentina/Buenos_Aires.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Argentina/Mendoza.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Argentina/San_Luis.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Argentina/Rio_Gallegos.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Argentina/San_Juan.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Argentina/Ushuaia.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Argentina/La_Rioja.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Argentina/Salta.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Argentina/Jujuy.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Argentina/ComodRivadavia.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Argentina/Cordoba.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Argentina/Catamarca.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Argentina/Tucuman.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Kentucky/Monticello.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Kentucky/Louisville.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Indiana/Winamac.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Indiana/Knox.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Indiana/Petersburg.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Indiana/Marengo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Indiana/Tell_City.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Indiana/Vincennes.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Indiana/Indianapolis.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Indiana/Vevay.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/North_Dakota/Beulah.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/North_Dakota/Center.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/North_Dakota/New_Salem.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Blanc__m__Sablon.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Rio_Branco.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Moncton.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Winnipeg.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Whitehorse.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Sao_Paulo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Denver.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Belem.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Fortaleza.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Los_Angeles.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Pangnirtung.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Swift_Current.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Adak.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Marigot.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/St_Lucia.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Dawson_Creek.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Boa_Vista.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Cancun.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Costa_Rica.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Godthab.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Danmarkshavn.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Barbados.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Cayenne.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Cuiaba.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Tegucigalpa.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Anchorage.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Antigua.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Mendoza.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Recife.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Montserrat.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Guayaquil.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Grenada.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Atikokan.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Nipigon.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/St_Kitts.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Goose_Bay.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Bogota.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Eirunepe.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Thule.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Montreal.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Shiprock.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Guyana.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Jamaica.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/St_Johns.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Louisville.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Grand_Turk.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/St_Thomas.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Resolute.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/La_Paz.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Managua.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Cordoba.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/St_Vincent.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Catamarca.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Paramaribo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Curacao.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Hermosillo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Atka.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Yellowknife.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Araguaina.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Sitka.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Rainy_River.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/El_Salvador.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Maceio.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/New_York.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Havana.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Guatemala.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Port__m__au__m__Prince.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Porto_Velho.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Noronha.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Jujuy.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Mazatlan.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Cambridge_Bay.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Detroit.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Menominee.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Buenos_Aires.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Asuncion.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Campo_Grande.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Scoresbysund.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Juneau.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Aruba.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Nassau.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Tijuana.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Nome.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Chihuahua.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Port_of_Spain.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Thunder_Bay.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Toronto.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Inuvik.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Glace_Bay.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Cayman.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Vancouver.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Montevideo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Rankin_Inlet.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Rosario.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Yakutat.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Coral_Harbour.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Edmonton.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Dominica.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Tortola.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Guadeloupe.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Chicago.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Virgin.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Boise.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/St_Barthelemy.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Regina.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Iqaluit.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Phoenix.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Santarem.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Mexico_City.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Fort_Wayne.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Ensenada.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Martinique.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Lima.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Manaus.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Miquelon.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Caracas.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Santiago.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Indianapolis.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Monterrey.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Puerto_Rico.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Dawson.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Anguilla.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Panama.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Porto_Acre.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Santo_Domingo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Merida.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Bahia.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Knox_IN.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Belize.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Halifax.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Ojinaga.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Santa_Isabel.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Matamoros.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Bahia_Banderas.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Metlakatla.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Lower_Princes.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Kralendijk.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/America/Creston.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Arctic/Longyearbyen.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Antarctica/DumontDUrville.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Antarctica/Palmer.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Antarctica/South_Pole.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Antarctica/Syowa.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Antarctica/Casey.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Antarctica/Mawson.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Antarctica/Rothera.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Antarctica/Vostok.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Antarctica/Davis.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Antarctica/McMurdo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Antarctica/Macquarie.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Choibalsan.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Chongqing.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Tehran.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Tashkent.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Shanghai.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Gaza.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Dubai.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Macau.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Seoul.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Beirut.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Dacca.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Riyadh88.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Calcutta.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Karachi.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Makassar.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Vladivostok.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Katmandu.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Bahrain.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Tokyo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Hebron.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Krasnoyarsk.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Qatar.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Dhaka.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Hong_Kong.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Ashgabat.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Taipei.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Yekaterinburg.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Thimphu.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Kashgar.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Kolkata.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Singapore.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Magadan.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Amman.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Muscat.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Riyadh87.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Hovd.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Damascus.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Ho_Chi_Minh.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Aden.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Yerevan.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Baghdad.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Aqtau.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Aqtobe.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Pyongyang.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Bangkok.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Chungking.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Jakarta.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Ujung_Pandang.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Macao.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Dili.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Istanbul.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Vientiane.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Urumqi.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Baku.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Brunei.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Kuching.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Sakhalin.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Yakutsk.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Phnom_Penh.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Irkutsk.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Oral.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Kabul.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Qyzylorda.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Ashkhabad.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Novosibirsk.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Omsk.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Tel_Aviv.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Anadyr.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Riyadh.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Bishkek.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Saigon.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Pontianak.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Kamchatka.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Nicosia.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Ulan_Bator.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Jerusalem.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Almaty.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Thimbu.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Dushanbe.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Colombo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Tbilisi.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Manila.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Kuala_Lumpur.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Riyadh89.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Samarkand.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Rangoon.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Harbin.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Kuwait.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Ulaanbaatar.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Kathmandu.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Jayapura.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Asia/Novokuznetsk.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/EST5EDT.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/EET.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/NZ__m__CHAT.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Navajo.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/ROC.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Eire.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/PRC.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Jamaica.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/MET.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/GMT.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/GB.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Egypt.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Iran.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/UCT.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/ROK.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/EST.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Portugal.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/WET.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/MST7MDT.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Iceland.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Kwajalein.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Libya.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/MST.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/GB__m__Eire.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/PST8PDT.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Poland.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Israel.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/GMT__m__0.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/GMT__p__0.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Turkey.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/NZ.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Singapore.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/W__m__SU.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Japan.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/UTC.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/HST.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Zulu.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Universal.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/GMT0.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Hongkong.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/CST6CDT.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Cuba.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/Greenwich.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/definitions/CET.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/linked_timezone_info.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/country_timezone.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/country_info.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/linked_timezone.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/timezone_transition_info.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/data_timezone.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/ruby_core_support.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/timezone.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/country.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/timezone_index_definition.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/timezone_proxy.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/data_timezone_info.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/timezone_period.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/country_index_definition.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/offset_rationals.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/timezone_definition.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/tzdataparser.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/info_timezone.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/timezone_info.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/time_or_datetime.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo/timezone_offset_info.rb
%{gemdir}/gems/tzinfo-0.3.32/lib/tzinfo.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_timezone.rb
%{gemdir}/gems/tzinfo-0.3.32/test/ts_all.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_timezone_index_definition.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_timezone_proxy.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_linked_timezone_info.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_timezone_period.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_data_timezone_info.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_timezone_melbourne.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_country_index_definition.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_offset_rationals.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_timezone_definition.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_timezone_london.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_country.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_timezone_utc.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_info_timezone.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_timezone_info.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_timezone_new_york.rb
%{gemdir}/gems/tzinfo-0.3.32/test/test_utils.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_time_or_datetime.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_timezone_offset_info.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_country_timezone.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_country_info.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_timezone_transition_info.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_linked_timezone.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_data_timezone.rb
%{gemdir}/gems/tzinfo-0.3.32/test/tc_ruby_core_support.rb


%doc %{gemdir}/doc/tzinfo-0.3.32
%{gemdir}/cache/tzinfo-0.3.32.gem
%{gemdir}/specifications/tzinfo-0.3.32.gemspec

%changelog
