%global npm_name @theforeman/vendor

Name: nodejs-theforeman-vendor
Version: 0.1.1
Release: 1%{?dist}
Summary: foreman supported 3rd-party node_modules
License: MIT
Group: Development/Libraries
URL: https://github.com/theforeman/foreman-js#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr scss %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license license
%doc readme.md

%changelog
* Tue Jul 23 2019 Evgeni Golov 0.1.1-1
- Update to 0.1.1

* Tue Jul 16 2019 Evgeni Golov 0.1.0-0.1.alpha.11
- Add nodejs-theforeman-vendor generated by npm2rpm using the single strategy
