# FIXME
# Remove nodejs_symlink_deps if installing bundled module with NPM

%global npm_name jed
%global enable_tests 0

%{?nodejs_find_provides_and_requires}

Name: nodejs-%{npm_name}
Version: 1.1.1
Release: 1%{?dist}
Summary: Gettext Style i18n for Modern JavaScript Apps
License: MIT
URL: https://SlexAxton@github.com/SlexAxton/Jed.git
Source0: http://registry.npmjs.org/jed/-/jed-1.1.1.tgz
Source1: jed-1.1.1-registry.npmjs.org.tgz
BuildRequires: nodejs-packaging
BuildArch:  noarch
ExclusiveArch: %{nodejs_arches} noarch

Provides: bundled-npm(jed) = 1.1.1
AutoReq: no 
AutoProv: no 


%description
%{summary}

%prep
mkdir npm_cache
for tgz in %{sources}; do
  echo $tgz | grep -q registry.npmjs.org || npm cache add --cache ./npm_cache $tgz
done

%setup -T -q -a 1 -D -n npm_cache

%build
npm install --cache-min Infinity --cache . --no-optional --global-style true %{npm_name}@%{version}

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cd node_modules/jed
cp -pfr .npmignore .travis.yml Makefile README.md jed.js package.json plurals.jison test node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pf README.md ../../
# If any binaries are included, symlink them to bindir here


%nodejs_symlink_deps

%if 0%{?enable_tests}
%check
%{nodejs_symlink_deps} --check
#$CHECK
%endif

%files
%{nodejs_sitelib}/%{npm_name}

%doc 
%doc README.md

%changelog
* ה' ספט 13 2018 Ohad Levy <ohadlevy@gmail.com> 1.1.1-1
- Add nodejs-jed generated by npm2rpm using the bundle strategy

