# template: default
%global gem_name rkerberos
%global gem_require_name %{gem_name}

Name: rubygem-%{gem_name}
Version: 0.2.3
Release: 2%{?dist}
Summary: A Ruby interface for the the Kerberos library
License: Artistic-2.0
URL: https://github.com/domcleal/rkerberos
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: ruby
BuildRequires: ruby-devel
BuildRequires: rubygems-devel
# Compiler is required for build of gem binary extension.
# https://fedoraproject.org/wiki/Packaging:C_and_C++#BuildRequires_and_Requires
BuildRequires: gcc
# end specfile generated dependencies

# Manual BuildRequires for native extensions
BuildRequires: krb5-devel
BuildRequires: rubygem(rake-compiler)

%description
The rkerberos library is an interface for the Kerberos 5 network
authentication protocol. It wraps the Kerberos C API.


%package doc
Summary: Documentation for %{name}
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.

%prep
%setup -q -n  %{gem_name}-%{version}

%build
# Create the gem as gem install only works on a gem file
gem build ../%{gem_name}-%{version}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

mkdir -p %{buildroot}%{gem_extdir_mri}
cp -a .%{gem_extdir_mri}/{gem.build_complete,*.so} %{buildroot}%{gem_extdir_mri}/

# rake-compiler isn't needed on the system itself
sed -i '/rake-compiler/ s/runtime/development/' %{buildroot}/%{gem_spec}

# Prevent dangling symlink in -debuginfo (rhbz#878863).
rm -rf %{buildroot}%{gem_instdir}/ext/

%check
# Ideally, this would be something like this:
# GEM_PATH="%{buildroot}%{gem_dir}:$GEM_PATH" ruby -e "require '%{gem_require_name}'"
# But that fails to find native extensions on EL8, so we fake the structure that ruby expects
mkdir gem_ext_test
cp -a %{buildroot}%{gem_dir} gem_ext_test/
mkdir -p gem_ext_test/gems/extensions/%{_arch}-%{_target_os}/$(ruby -r rbconfig -e 'print RbConfig::CONFIG["ruby_version"]')/
cp -a %{buildroot}%{gem_extdir_mri} gem_ext_test/gems/extensions/%{_arch}-%{_target_os}/$(ruby -r rbconfig -e 'print RbConfig::CONFIG["ruby_version"]')/
GEM_PATH="./gem_ext_test/gems:$GEM_PATH" ruby -e "require '%{gem_require_name}'"
rm -rf gem_ext_test

%files
%dir %{gem_instdir}
%{gem_extdir_mri}
%license %{gem_instdir}/LICENSE
%exclude %{gem_cache}
%{gem_spec}

%files doc
%doc %{gem_docdir}
%doc %{gem_instdir}/CHANGES.md
%doc %{gem_instdir}/MANIFEST.md
%{gem_instdir}/Gemfile
%doc %{gem_instdir}/README.md
%{gem_instdir}/Rakefile
%exclude %{gem_instdir}/rkerberos.gemspec
%{gem_instdir}/spec

%changelog
* Fri Jul 31 2026 Zach Huntington-Meath <zhunting@redhat.com> - 0.2.3-2
- Rebuild for EL10

* Wed Mar 11 2026 Foreman Packaging Automation <packaging@theforeman.org> - 0.2.3-1
- Update to 0.2.3

* Sun Feb 22 2026 Foreman Packaging Automation <packaging@theforeman.org> - 0.2.0-1
- Update to 0.2.0

* Sat Nov 22 2025 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> - 0.1.5-22
- Replace use of deprecated PatchN macro

* Mon Dec 18 2023 Evgeni Golov - 0.1.5-21
- Explicitly BuildRequire gcc

* Thu Mar 11 2021 Eric D. Helms <ericdhelms@gmail.com> - 0.1.5-20
- Rebuild against rh-ruby27

* Tue Dec 08 2020 Evgeni Golov - 0.1.5-19
- Rebuild against new libkadm5 in EL 8.3

* Thu Apr 16 2020 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> - 0.1.5-18
- Add check section to test native library
- Remove dependency on rake-compiler

* Wed Apr 08 2020 Zach Huntington-Meath <zhunting@redhat.com> - 0.1.5-17
- Bump release to build for el8

* Fri Sep 13 2019 Eric D. Helms <ericdhelms@gmail.com> 0.1.5-16
- Add rubygem-rkerberos generated by gem2rpm using the scl template

