%global npm_name invariant
%global enable_tests 1

Name: nodejs-%{npm_name}
Version: 2.2.4
Release: 1%{?dist}
Summary: invariant
License: MIT
Group: Development/Libraries
URL: https://github.com/zertosh/invariant#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
Requires: npm(loose-envify) >= 1.0.0
Requires: npm(loose-envify) < 2.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr browser.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr invariant.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr invariant.js.flow %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%if 0%{?enable_tests}
%check
%{nodejs_symlink_deps} --check
%endif

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Mon Apr 23 2018 Eric D. Helms <ericdhelms@gmail.com> 2.2.4-1
- Add nodejs-invariant generated by npm2rpm using the single strategy

