# template: foreman_plugin
%global gem_name foreman_opentofu
%global plugin_name opentofu
%global foreman_min_version 3.0

Name: rubygem-%{gem_name}
Version: 0.0.5
Release: 2%{?foremandist}%{?dist}
Summary: Plugin to provision host using opentofu
License: GPL-3.0-only
URL: https://github.com/ATIX-AG/foreman_opentofu
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: foreman >= %{foreman_min_version}
BuildRequires: foreman-assets >= %{foreman_min_version}
BuildRequires: foreman-plugin >= %{foreman_min_version}
Requires: ruby >= 2.7
Requires: ruby < 4
BuildRequires: ruby >= 2.7
BuildRequires: ruby < 4
BuildRequires: rubygems-devel
BuildRequires: rubygem(deface) < 2.0.0
BuildArch: noarch
Provides: foreman-plugin-%{plugin_name} = %{version}
# end specfile generated dependencies

Requires: (foreman-opentofu-selinux if selinux-policy-targeted)
BuildRequires: rubygem(deface) < 2.0
Recommends: tofu

%description
Plugin to provision host using opentofu with different compute resources.


%package doc
Summary: Documentation for %{name}
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.


###################################
%package -n foreman-opentofu-selinux
Summary: SELinux policy for %{name}
BuildArch: noarch
BuildRequires:  checkpolicy
BuildRequires:  selinux-policy-devel
BuildRequires:  policycoreutils
Requires:           foreman-selinux
Requires:           selinux-policy
Requires(post):     /usr/sbin/semodule
Requires(post):     /sbin/restorecon
Requires(post):     /usr/sbin/setsebool
Requires(post):     /usr/sbin/selinuxenabled
Requires(post):     /usr/sbin/semanage
Requires(post):     selinux-policy-targeted
Requires(postun):   /usr/sbin/semodule
Requires(postun):   /sbin/restorecon

%description -n foreman-opentofu-selinux
Documentation for the SELinux policy for %{name}.

%prep
%setup -q -n  %{gem_name}-%{version}

%build
# Create the gem as gem install only works on a gem file
gem build ../%{gem_name}-%{version}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

# build selinux
cd selinux
make clean && make all

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

# clean selinux source files from buildroot
find %{buildroot}%{gem_dir} -type d -name selinux | xargs rm -rf

%foreman_bundlerd_file

# Create these directories in which tofu will run and store files
mkdir -p %{buildroot}%{_localstatedir}/lib/foreman-opentofu/plugin-cache
mkdir -p %{buildroot}%{_localstatedir}/lib/foreman-opentofu/tmp

# install selinux
cd selinux
mkdir -p %{buildroot}/%{_datadir}/selinux/targeted/
install -m 0600 foreman_opentofu.pp %{buildroot}/%{_datadir}/selinux/targeted/

%files
%dir %{gem_instdir}
%license %{gem_instdir}/LICENSE
%{gem_instdir}/app
%{gem_instdir}/config
%{gem_instdir}/db
%{gem_libdir}
%{gem_instdir}/locale
%exclude %{gem_cache}
%{gem_spec}
%{foreman_bundlerd_plugin}
%dir %attr(0750,foreman,foreman) %{_localstatedir}/lib/foreman-opentofu/
%dir %attr(0750,foreman,foreman) %{_localstatedir}/lib/foreman-opentofu/plugin-cache
%dir %attr(0700,foreman,foreman) %{_localstatedir}/lib/foreman-opentofu/tmp

%files doc
%doc %{gem_docdir}
%doc %{gem_instdir}/README.md
%{gem_instdir}/Rakefile
%{gem_instdir}/test

%posttrans
%{foreman_plugin_log}

%posttrans -n foreman-opentofu-selinux
if /usr/sbin/selinuxenabled; then
  /usr/sbin/semodule -r foreman_opentofu 2>/dev/null || :
  /usr/sbin/semodule -i %{_datadir}/selinux/targeted/foreman_opentofu.pp
  /sbin/restorecon -ri %{_localstatedir}/lib/foreman-opentofu/
fi

%preun -n foreman-opentofu-selinux
if /usr/sbin/selinuxenabled; then
  /usr/sbin/semodule -r foreman_opentofu 2>/dev/null || :
  /sbin/restorecon -ri %{_localstatedir}/lib/foreman-opentofu/
fi

%files -n foreman-opentofu-selinux
%attr(0600,root,root) %{_datadir}/selinux/targeted/*.pp

%changelog
* Fri Jul 31 2026 Zach Huntington-Meath <zhunting@redhat.com> - 0.0.5-2
- Rebuild for EL10

* Fri May 29 2026 Foreman Packaging Automation <packaging@theforeman.org> - 0.0.5-1
- Update to 0.0.5

* Thu Apr 09 2026 Foreman Packaging Automation <packaging@theforeman.org> - 0.0.4-1
- Update to 0.0.4
- Setup directory for tofu and set correct permissions

* Wed Mar 25 2026 Foreman Packaging Automation <packaging@theforeman.org> - 0.0.3-1
- Update to 0.0.3

* Wed Feb 25 2026 Foreman Packaging Automation <packaging@theforeman.org> - 0.0.2-1
- Update to 0.0.2

* Fri Feb 06 2026 Markus Bucher <bucher@atix.de> 0.0.1-1
- Add rubygem-foreman_opentofu generated by gem2rpm using the foreman_plugin template

