%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name react-html-parser

Name: %{?scl_prefix}nodejs-react-html-parser
Version: 2.0.2
Release: 1%{?dist}
Summary: Parse HTML into React components
License: MIT
Group: Development/Libraries
URL: https://github.com/wrakky/react-html-parser#readme
Source0: https://registry.npmjs.org/react-html-parser/-/react-html-parser-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
Requires: %{?scl_prefix}npm(htmlparser2) >= 3.9.0
Requires: %{?scl_prefix}npm(htmlparser2) < 4.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr demo %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr scripts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc CHANGELOG.md
%doc README.md

%changelog
* Thu Feb 27 2020 Adam Ruzicka <aruzicka@redhat.com> 2.0.2-1
- Add nodejs-react-html-parser generated by npm2rpm using the single strategy

