# template: smart_proxy_plugin
%global gem_name smart_proxy_openbolt
%global plugin_name openbolt

%global foreman_proxy_min_version 1.24
%global foreman_proxy_dir %{_datadir}/foreman-proxy
%global foreman_proxy_statedir %{_sharedstatedir}/foreman-proxy
%global foreman_proxy_bundlerd_dir %{foreman_proxy_dir}/bundler.d
%global foreman_proxy_settingsd_dir %{_sysconfdir}/foreman-proxy/settings.d

Name: rubygem-%{gem_name}
Version: 1.2.0
Release: 2%{?foremandist}%{?dist}
Summary: Smart Proxy plugin for OpenBolt integration
License: GPL-3.0-only
URL: https://github.com/overlookinfra/smart_proxy_openbolt
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: foreman-proxy >= %{foreman_proxy_min_version}
Requires: ruby >= 3.0
BuildRequires: ruby >= 3.0
BuildRequires: rubygems-devel
BuildArch: noarch
Provides: foreman-proxy-plugin-%{plugin_name} = %{version}
# end specfile generated dependencies

%description
Uses the OpenBolt CLI tool to run tasks and plans in Foreman.


%package doc
Summary: Documentation for %{name}
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.

%prep
%setup -q -n  %{gem_name}-%{version}

%build
# Create the gem as gem install only works on a gem file
gem build ../%{gem_name}-%{version}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

# bundler file
mkdir -p %{buildroot}%{foreman_proxy_bundlerd_dir}
mv %{buildroot}%{gem_instdir}/bundler.d/%{plugin_name}.rb \
   %{buildroot}%{foreman_proxy_bundlerd_dir}

# sample config
mkdir -p %{buildroot}%{foreman_proxy_settingsd_dir}
mv %{buildroot}%{gem_instdir}/settings.d/openbolt.yml \
   %{buildroot}%{foreman_proxy_settingsd_dir}/openbolt.yml

%files
%dir %{gem_instdir}
%config(noreplace) %attr(0640, root, foreman-proxy) %{foreman_proxy_settingsd_dir}/openbolt.yml
%license %{gem_instdir}/LICENSE
%exclude %{gem_instdir}/bundler.d
%{gem_libdir}
%exclude %{gem_instdir}/settings.d
%{foreman_proxy_bundlerd_dir}/%{plugin_name}.rb
%exclude %{gem_cache}
%{gem_spec}

%files doc
%doc %{gem_docdir}
%doc %{gem_instdir}/README.md

%changelog
* Wed Jul 29 2026 Zach Huntington-Meath <zhunting@redhat.com> - 1.2.0-2
- Rebuild for EL10

* Fri May 01 2026 Foreman Packaging Automation <packaging@theforeman.org> - 1.2.0-1
- Update to 1.2.0

* Thu Apr 16 2026 Foreman Packaging Automation <packaging@theforeman.org> - 1.1.0-1
- Update to 1.1.0

* Tue Nov 25 2025 Foreman Packaging Automation <packaging@theforeman.org> - 0.1.1-1
- Update to 0.1.1

* Mon Nov 10 11:39:32 CET 2025 Tim Meusel <tim@bastelfreak.de> - 0.1.0-1
- Update to 0.1.0

* Fri Nov 07 2025 Tim Meusel <tim@bastelfreak.de> 0.0.1-1
- Add rubygem-smart_proxy_openbolt generated by gem2rpm using the smart_proxy_plugin template

