%global npm_name react-helmet

Name: nodejs-react-helmet
Version: 6.1.0
Release: 2%{?dist}
Summary: A document head manager for React
License: MIT
Group: Development/Libraries
URL: https://github.com/nfl/react-helmet#readme
Source0: https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz
Source1: https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz
Source2: https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz
Source3: https://registry.npmjs.org/prop-types/-/prop-types-15.8.1.tgz
Source4: https://registry.npmjs.org/react-fast-compare/-/react-fast-compare-3.2.2.tgz
Source5: https://registry.npmjs.org/react-helmet/-/react-helmet-6.1.0.tgz
Source6: https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz
Source7: https://registry.npmjs.org/react-side-effect/-/react-side-effect-2.1.2.tgz
Source8: nodejs-react-helmet-%{version}-registry.npmjs.org.tgz
BuildRequires: npm >= 7
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

Provides: npm(%{npm_name}) = %{version}
Provides: bundled(npm(js-tokens)) = 4.0.0
Provides: bundled(npm(loose-envify)) = 1.4.0
Provides: bundled(npm(object-assign)) = 4.1.1
Provides: bundled(npm(prop-types)) = 15.8.1
Provides: bundled(npm(react-fast-compare)) = 3.2.2
Provides: bundled(npm(react-helmet)) = 6.1.0
Provides: bundled(npm(react-is)) = 16.13.1
Provides: bundled(npm(react-side-effect)) = 2.1.2
AutoReq: no
AutoProv: no

%define npm_cache_dir npm_cache_%{name}-%{version}-%{release}

%description
%{summary}

%prep
mkdir -p %{npm_cache_dir}
for tgz in %{sources}; do
  echo $tgz | grep -q registry.npmjs.org || npm cache add --cache %{npm_cache_dir} $tgz
done

%setup -T -q -a 8 -D -n %{npm_cache_dir}

%build
npm install --legacy-peer-deps --offline --cache %{_builddir}/%{npm_cache_dir} --package-lock false --omit optional --install-strategy shallow %{npm_name}@%{version}

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/es %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%files
%{nodejs_sitelib}/%{npm_name}
%license node_modules/%{npm_name}/LICENSE
%doc node_modules/%{npm_name}/CHANGELOG.md
%doc node_modules/%{npm_name}/CODE_OF_CONDUCT.md
%doc node_modules/%{npm_name}/ISSUE_TEMPLATE.md
%doc node_modules/%{npm_name}/README.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 6.1.0-2
- Regenerate spec file

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 6.1.0-1
- Add nodejs-react-helmet generated by npm2rpm using the bundle strategy

