%global npm_name query-string

Name: nodejs-%{npm_name}
Version: 6.1.0
Release: 1%{?dist}
Summary: Parse and stringify URL query strings
License: MIT
Group: Development/Libraries
URL: https://github.com/sindresorhus/query-string#readme
Source0: https://registry.npmjs.org/query-string/-/query-string-6.1.0.tgz
Source1: https://registry.npmjs.org/decode-uri-component/-/decode-uri-component-0.2.0.tgz
Source2: https://registry.npmjs.org/strict-uri-encode/-/strict-uri-encode-2.0.0.tgz
Source3: %{npm_name}-%{version}-registry.npmjs.org.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

Provides: npm(%{npm_name}) = %{version}
Provides: bundled(npm(decode-uri-component)) = 0.2.0
Provides: bundled(npm(query-string)) = 6.1.0
Provides: bundled(npm(strict-uri-encode)) = 2.0.0
AutoReq: no
AutoProv: no

%define npm_cache_dir /tmp/npm_cache_%{name}-%{version}-%{release}

%description
%{summary}

%prep
mkdir -p %{npm_cache_dir}
for tgz in %{sources}; do
  echo $tgz | grep -q registry.npmjs.org || npm cache add --cache %{npm_cache_dir} $tgz
done
%setup -T -q -a 3 -D -n %{npm_cache_dir}

%build
npm install --cache-min Infinity --cache %{npm_cache_dir} --no-shrinkwrap --no-optional --global-style true %{npm_name}@%{version}

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%files
%{nodejs_sitelib}/%{npm_name}
%license node_modules/%{npm_name}/license
%doc node_modules/%{npm_name}/readme.md

%changelog
* Fri Sep 14 2018 Eric D. Helms <ericdhelms@gmail.com> 6.1.0-1
- Add nodejs-query-string generated by npm2rpm using the bundle strategy

