%global npm_name @types/react-router

Name: nodejs-types-react-router
Version: 5.1.20
Release: 1%{?dist}
Summary: TypeScript definitions for React Router
License: MIT
Group: Development/Libraries
URL: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-router
Source0: https://registry.npmjs.org/@types/history/-/history-4.7.11.tgz
Source1: https://registry.npmjs.org/@types/react/-/react-19.2.15.tgz
Source2: https://registry.npmjs.org/@types/react-router/-/react-router-5.1.20.tgz
Source3: https://registry.npmjs.org/csstype/-/csstype-3.2.3.tgz
Source4: nodejs-types-react-router-%{version}-registry.npmjs.org.tgz
BuildRequires: npm >= 7
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

Provides: npm(%{npm_name}) = %{version}
Provides: bundled(npm(@types/history)) = 4.7.11
Provides: bundled(npm(@types/react)) = 19.2.15
Provides: bundled(npm(@types/react-router)) = 5.1.20
Provides: bundled(npm(csstype)) = 3.2.3
AutoReq: no
AutoProv: no

%define npm_cache_dir npm_cache_%{name}-%{version}-%{release}

%description
%{summary}

%prep
mkdir -p %{npm_cache_dir}
for tgz in %{sources}; do
  echo $tgz | grep -q registry.npmjs.org || npm cache add --cache %{npm_cache_dir} $tgz
done

%setup -T -q -a 4 -D -n %{npm_cache_dir}

%build
npm install --legacy-peer-deps --offline --cache %{_builddir}/%{npm_cache_dir} --package-lock false --omit optional --install-strategy shallow %{npm_name}@%{version}

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/index.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/ts4.6 %{buildroot}%{nodejs_sitelib}/%{npm_name}

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%files
%{nodejs_sitelib}/%{npm_name}
%license node_modules/%{npm_name}/LICENSE
%doc node_modules/%{npm_name}/README.md

%changelog
* Wed May 27 2026 Nadja Heitmann <nadjah@atix.de> 5.1.20-1
- Add nodejs-types-react-router generated by npm2rpm using the bundle strategy

