%global npm_name ace-builds

Name: nodejs-ace-builds
Version: 1.44.0
Release: 2%{?dist}
Summary: Ace (Ajax
License: BSD-3-Clause
URL: https://github.com/ajaxorg/ace-builds
Source0: https://registry.npmjs.org/ace-builds/-/ace-builds-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr ace-modes.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr ace-modules.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr ace.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr editor.html %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr esm-resolver.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src-min %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src-min-noconflict %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src-noconflict %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr types %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr webpack-resolver.js %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc CODE_OF_CONDUCT.md
%doc CONTRIBUTING.md
%doc ChangeLog.txt
%doc README.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 1.44.0-2
- Regenerate spec file

* Sun May 17 2026 Foreman Packaging Automation <packaging@theforeman.org> 1.44.0-1
- Update to 1.44.0

* Sun Jan 25 2026 Foreman Packaging Automation <packaging@theforeman.org> 1.43.6-1
- Update to 1.43.6

* Wed Dec 10 2025 Foreman Packaging Automation <packaging@theforeman.org> 1.43.5-1
- Update to 1.43.5

* Wed Oct 22 2025 Foreman Packaging Automation <packaging@theforeman.org> 1.43.4-1
- Update to 1.43.4

* Wed Sep 03 2025 Foreman Packaging Automation <packaging@theforeman.org> 1.43.3-1
- Update to 1.43.3

* Thu Aug 28 2025 Foreman Packaging Automation <packaging@theforeman.org> 1.43.2-1
- Update to 1.43.2

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 1.4.13-1
- Add nodejs-ace-builds generated by npm2rpm using the single strategy

