%global npm_name datatables.net-dt

Name: nodejs-datatables.net-dt
Version: 1.13.5
Release: 2%{?dist}
Summary: DataTables for jQuery with styling for [DataTables](https://datatables
License: MIT
URL: https://datatables.net
Source0: https://registry.npmjs.org/datatables.net-dt/-/datatables.net-dt-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
Requires: npm(datatables.net) >= 1.13.4
Requires: npm(jquery) >= 1.7.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr images %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr types %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license License.txt
%doc Readme.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 1.13.5-2
- Regenerate spec file

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 1.13.5-1
- Add nodejs-datatables.net-dt generated by npm2rpm using the single strategy

