# template: foreman_plugin
%global gem_name foreman_ansible_director
%global plugin_name ansible_director
%global foreman_min_version 3.12.0

Name: rubygem-%{gem_name}
Version: 0.5.0
Release: 1%{?foremandist}%{?dist}
Summary: Advanced Ansible integration with Foreman and Katello
License: GPL-3.0-only
URL: https://github.com/ATIX-AG/foreman_ansible_director
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: foreman >= %{foreman_min_version}
BuildRequires: foreman-assets >= %{foreman_min_version}
BuildRequires: foreman-plugin >= %{foreman_min_version}
Requires: ruby >= 3.0
Requires: ruby < 4
BuildRequires: ruby >= 3.0
BuildRequires: ruby < 4
BuildRequires: rubygems-devel
BuildRequires: rubygem(dynflow) >= 1.6.1
BuildRequires: rubygem(foreman_remote_execution) >= 7.1.0
BuildRequires: rubygem(foreman-tasks) >= 9.1
BuildRequires: (rubygem(pulp_ansible_client) >= 0.28.0 with rubygem(pulp_ansible_client) < 0.29.0)
BuildRequires: (rubygem(pulpcore_client) >= 3.85.0 with rubygem(pulpcore_client) < 3.86.0)
BuildRequires: (rubygem(git) >= 1.18.0 with rubygem(git) < 3.0.0)
BuildArch: noarch
Provides: foreman-plugin-%{plugin_name} = %{version}
# end specfile generated dependencies

# start package.json devDependencies BuildRequires
BuildRequires: (npm(@babel/core) >= 7.7.0 with npm(@babel/core) < 8.0.0)
BuildRequires: (npm(@patternfly/react-core) >= 5.4.14 with npm(@patternfly/react-core) < 6.0.0)
BuildRequires: (npm(@patternfly/react-table) >= 5.4.14 with npm(@patternfly/react-table) < 6.0.0)
BuildRequires: (npm(@theforeman/builder) >= 15.0.1 with npm(@theforeman/builder) < 16.0.0)
BuildRequires: (npm(@types/node) >= 22.13.10 with npm(@types/node) < 23.0.0)
BuildRequires: (npm(@types/react) >= 16.14.0 with npm(@types/react) < 17.0.0)
BuildRequires: (npm(@types/react-dom) >= 16.9.25 with npm(@types/react-dom) < 17.0.0)
BuildRequires: (npm(@types/react-redux) >= 7.1.34 with npm(@types/react-redux) < 8.0.0)
BuildRequires: (npm(@types/react-router) >= 5.1.20 with npm(@types/react-router) < 6.0.0)
BuildRequires: (npm(@types/react-router-dom) >= 5.3.3 with npm(@types/react-router-dom) < 6.0.0)
BuildRequires: (npm(@typescript-eslint/eslint-plugin) >= 5.62.0 with npm(@typescript-eslint/eslint-plugin) < 6.0.0)
BuildRequires: (npm(@typescript-eslint/parser) >= 5.62.0 with npm(@typescript-eslint/parser) < 6.0.0)
BuildRequires: (npm(axios) >= 1.8.4 with npm(axios) < 2.0.0)
BuildRequires: (npm(react-router) >= 5.3.4 with npm(react-router) < 6.0.0)
BuildRequires: (npm(ts-jest) >= 29.0.0 with npm(ts-jest) < 30.0.0)
BuildRequires: (npm(ts-loader) >= 9.5.2 with npm(ts-loader) < 10.0.0)
BuildRequires: (npm(typescript) >= 5.8.2 with npm(typescript) < 6.0.0)
BuildRequires: (npm(webpack-cli) >= 6.0.1 with npm(webpack-cli) < 7.0.0)
# end package.json devDependencies BuildRequires

# start package.json dependencies BuildRequires
BuildRequires: (npm(@jest/globals) >= 30.2.0 with npm(@jest/globals) < 31.0.0)
BuildRequires: (npm(@xyflow/react) >= 12.8.5 with npm(@xyflow/react) < 13.0.0)
BuildRequires: (npm(react-ace) >= 9.5.0 with npm(react-ace) < 10.0.0)
BuildRequires: (npm(react-intl) >= 6.8.5 with npm(react-intl) < 7.0.0)
BuildRequires: (npm(react-use-websocket) >= 3.0.0 with npm(react-use-websocket) < 4.0.0)
# end package.json dependencies BuildRequires

%description
Ansible support with Execution Environments, different Ansible/Python versions
and traditional Ansible features.


%package doc
Summary: Documentation for %{name}
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.

%prep
%setup -q -n  %{gem_name}-%{version}

%build
# Create the gem as gem install only works on a gem file
gem build ../%{gem_name}-%{version}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

%foreman_bundlerd_file
%foreman_precompile_plugin -s

%files
%dir %{gem_instdir}
%license %{gem_instdir}/LICENSE
%{gem_instdir}/app
%{gem_instdir}/config
%{gem_instdir}/db
%{gem_libdir}
%{gem_instdir}/locale
%exclude %{gem_instdir}/package.json
%{gem_instdir}/tsconfig.json
%exclude %{gem_instdir}/webpack
%exclude %{gem_cache}
%{gem_spec}
%{foreman_bundlerd_plugin}
%{foreman_assets_plugin}
%{foreman_assets_foreman}
%{foreman_webpack_plugin}
%{foreman_webpack_foreman}

%files doc
%doc %{gem_docdir}
%doc %{gem_instdir}/README.md
%{gem_instdir}/Rakefile
%{gem_instdir}/test

%posttrans
%{foreman_plugin_log}

%changelog
* Wed May 27 2026 Nadja Heitmann <nadjah@atix.de> 0.5.0-1
- Add rubygem-foreman_ansible_director generated by gem2rpm using the foreman_plugin template

