%global npm_name humanize-duration

Name: nodejs-humanize-duration
Version: 3.27.0
Release: 2%{?dist}
Summary: Convert millisecond durations to English and many other languages
License: Unlicense
URL: https://github.com/EvanHahn/HumanizeDuration.js
Source0: https://registry.npmjs.org/humanize-duration/-/humanize-duration-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr humanize-duration.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.txt
%doc CONTRIBUTING.md
%doc HISTORY.md
%doc README.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 3.27.0-2
- Regenerate spec file

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 3.27.0-1
- Add nodejs-humanize-duration generated by npm2rpm using the single strategy

