%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name humanize-duration

Name: %{?scl_prefix}nodejs-humanize-duration
Version: 3.27.0
Release: 1%{?dist}
Summary: Convert millisecond durations to English and many other languages
License: Unlicense
Group: Development/Libraries
URL: https://github.com/EvanHahn/HumanizeDuration.js
Source0: https://registry.npmjs.org/humanize-duration/-/humanize-duration-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr humanize-duration.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.txt
%doc CONTRIBUTING.md
%doc HISTORY.md
%doc README.md

%changelog
* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 3.27.0-1
- Add nodejs-humanize-duration generated by npm2rpm using the single strategy

