%global npm_name react-popper

Name: nodejs-react-popper
Version: 1.0.2
Release: 1%{?dist}
Summary: React wrapper around Popper
License: MIT
Group: Development/Libraries
URL: https://github.com/souporserious/react-popper
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
Requires: npm(babel-runtime) >= 6.0.0
Requires: npm(babel-runtime) < 7.0.0
Requires: npm(create-react-context) >= 0.2.1
Requires: npm(create-react-context) < 1.0.0
Requires: npm(popper.js) >= 1.14.1
Requires: npm(popper.js) < 2.0.0
Requires: npm(prop-types) >= 15.6.1
Requires: npm(prop-types) < 16.0.0
Requires: npm(typed-styles) >= 0.0.5
Requires: npm(typed-styles) < 1.0.0
Requires: npm(warning) >= 4.0.0
Requires: npm(warning) < 5.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package
# https://github.com/FezVrasta/react-popper/issues/226
%nodejs_fixdep warning '^4.0.0'

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr typings %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Wed Oct 10 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 1.0.2-1
- Add nodejs-react-popper generated by npm2rpm using the single strategy

