%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name react-popper

Name: %{?scl_prefix}nodejs-react-popper
Version: 1.0.2
Release: 4%{?dist}
Summary: React wrapper around Popper
License: MIT
Group: Development/Libraries
URL: https://github.com/souporserious/react-popper
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
%if 0%{?scl:1}
BuildRequires: %{?scl_prefix_nodejs}npm
%else
BuildRequires: nodejs-packaging
BuildRequires: npm
%endif
Requires: %{?scl_prefix}npm(babel-runtime) >= 6.0.0
Requires: %{?scl_prefix}npm(babel-runtime) < 7.0.0
Requires: %{?scl_prefix}npm(create-react-context) >= 0.2.1
Requires: %{?scl_prefix}npm(create-react-context) < 0.3.0
Requires: %{?scl_prefix}npm(popper.js) >= 1.14.1
Requires: %{?scl_prefix}npm(popper.js) < 2.0.0
Requires: %{?scl_prefix}npm(prop-types) >= 15.6.1
Requires: %{?scl_prefix}npm(prop-types) < 16.0.0
Requires: %{?scl_prefix}npm(typed-styles) >= 0.0.5
Requires: %{?scl_prefix}npm(typed-styles) < 1.0.0
Requires: %{?scl_prefix}npm(warning) >= 4.0.0
Requires: %{?scl_prefix}npm(warning) < 5.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package
# https://github.com/FezVrasta/react-popper/issues/226
%nodejs_fixdep warning '^4.0.0'

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr typings %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Tue Mar 17 2020 Zach Huntington-Meath <zhunting@redhat.com> - 1.0.2-4
- Bump packages to build for el8

* Tue Oct 22 2019 Eric D. Helms <ericdhelms@gmail.com> - 1.0.2-3
- Build for SCL

* Fri Oct 04 2019 Eric D. Helms <ericdhelms@gmail.com> - 1.0.2-2
- Update specs to handle SCL

* Wed Oct 10 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 1.0.2-1
- Add nodejs-react-popper generated by npm2rpm using the single strategy
