%global npm_name @scalprum/core

Name: nodejs-scalprum-core
Version: 0.8.3
Release: 2%{?dist}
Summary: Includes core functions for scalprum scaffolding
License: Apache-2.0
URL: https://github.com/scalprum/scaffloding#readme
Source0: https://registry.npmjs.org/@scalprum/core/-/core-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
Requires: npm(@openshift/dynamic-plugin-sdk) >= 5.0.1
Requires: npm(@openshift/dynamic-plugin-sdk) < 6.0.0
Requires: npm(tslib) >= 2.6.2
Requires: npm(tslib) < 3.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr esm %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr warnDuplicatePkg.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr warnDuplicatePkg.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr warnDuplicatePkg.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%doc CHANGELOG.md
%doc README.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 0.8.3-2
- Regenerate spec file

* Wed Jul 09 2025 root <root> 0.8.3-1
- Add nodejs-scalprum-core generated by npm2rpm using the single strategy

