%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name loose-envify

Name: %{?scl_prefix}nodejs-loose-envify
Version: 1.4.0
Release: 1%{?dist}
Summary: Fast (and loose) selective `process
License: MIT
Group: Development/Libraries
URL: https://github.com/zertosh/loose-envify
Source0: https://registry.npmjs.org/loose-envify/-/loose-envify-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
Requires: npm(js-tokens)
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr cli.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr custom.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr loose-envify.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr replace.js %{buildroot}%{nodejs_sitelib}/%{npm_name}

mkdir -p %{buildroot}%{_bindir}
chmod 0755 %{buildroot}%{nodejs_sitelib}/%{npm_name}/cli.js
ln -sf %{nodejs_sitelib}/%{npm_name}/cli.js %{buildroot}%{_bindir}/loose-envify

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%{_bindir}/loose-envify
%license LICENSE
%doc README.md

%changelog
* Mon Jul 07 2025 root <root> 1.4.0-1
- Add nodejs-loose-envify generated by npm2rpm using the single strategy

