%global npm_name seamless-immutable

Name: nodejs-seamless-immutable
Version: 7.1.4
Release: 2%{?dist}
Summary: Immutable data structures for JavaScript which are backwards-compatible with normal JS Arrays and Objects
License: BSD-3-Clause
URL: https://github.com/rtfeldman/seamless-immutable
Source0: https://registry.npmjs.org/seamless-immutable/-/seamless-immutable-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr seamless-immutable.development.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr seamless-immutable.development.min.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr seamless-immutable.production.min.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 7.1.4-2
- Update to 7.1.4

* Wed Aug 27 2025 Foreman Packaging Automation <packaging@theforeman.org> 7.1.4-1
- Update to 7.1.4

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 7.1.2-1
- Add nodejs-seamless-immutable generated by npm2rpm using the single strategy

