%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name react-router-bootstrap

Name: %{?scl_prefix}nodejs-react-router-bootstrap
Version: 0.25.0
Release: 1%{?dist}
Summary: Integration between React Router and React-Bootstrap
License: Apache-2.0
Group: Development/Libraries
URL: https://github.com/react-bootstrap/react-router-bootstrap
Source0: https://registry.npmjs.org/react-router-bootstrap/-/react-router-bootstrap-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
Requires: npm(prop-types) >= 15.5.10
Requires: npm(prop-types) < 16.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Thu Jul 03 2025 root <root> 0.25.0-1
- Add nodejs-react-router-bootstrap generated by npm2rpm using the single strategy

