%global npm_name react-router-bootstrap
%global enable_tests 0

Name: nodejs-%{npm_name}
Version: 0.24.4
Release: 1%{?dist}
Summary: Integration between React Router and React-Bootstrap
License: Apache-2.0
Group: Development/Libraries
URL: https://github.com/react-bootstrap/react-router-bootstrap
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch:  noarch
ExclusiveArch: %{nodejs_arches} noarch

%{?nodejs_find_provides_and_requires}

%define npm_cache_dir /tmp/npm_cache_%{name}-%{version}-%{release}
%description
%{summary}

%prep
%setup -q -n package

%build


%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr CHANGELOG.md LICENSE README.md lib package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}


%nodejs_symlink_deps

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%if 0%{?enable_tests}
%check
%{nodejs_symlink_deps} --check
%endif

%files
%{nodejs_sitelib}/%{npm_name}

%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Thu Mar 22 2018 Walden Raines <walden@redhat.com> 0.24.4-1
- Add nodejs-react-router-bootstrap generated by npm2rpm using the single strategy

* Thu Mar 22 2018 author@example.com <Author Name> - 0.24.4-1
- First release
