%global npm_name datatables.net-bs

Name: nodejs-datatables.net-bs
Version: 1.13.5
Release: 3%{?dist}
Summary: DataTables for jQuery with styling for [Bootstrap](https://getbootstrap
License: MIT
URL: https://datatables.net
Source0: https://registry.npmjs.org/datatables.net-bs/-/datatables.net-bs-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
Requires: npm(datatables.net) >= 1.13.4
Requires: npm(jquery) >= 1.7.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr images %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr types %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license License.txt
%doc Readme.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 1.13.5-3
- Update to 1.13.5

* Mon Jul 07 2025 root <root> 1.13.5-2
- Update to 1.13.5 to use single strategy

* Fri Jun 13 2025 MariaAga <mariaaga@redhat.com> 1.13.5-1
- Add nodejs-datatables.net-bs generated by npm2rpm using the bundle strategy

