%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name @patternfly/react-tokens

Name: %{?scl_prefix}nodejs-patternfly-react-tokens
Version: 5.4.1
Release: 1%{?dist}
Summary: This library provides access to the design tokens of PatternFly 4 from JavaScript
License: MIT
Group: Development/Libraries
URL: https://github.com/patternfly/patternfly-react#readme
Source0: https://registry.npmjs.org/@patternfly/react-tokens/-/react-tokens-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr scripts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr tests %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Thu Aug 28 2025 Foreman Packaging Automation <packaging@theforeman.org> 5.4.1-1
- Update to 5.4.1

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 5.2.0-1
- Add nodejs-patternfly-react-tokens generated by npm2rpm using the single strategy

