%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name number_helpers

Name: %{?scl_prefix}nodejs-number_helpers
Version: 0.1.1
Release: 1%{?dist}
Summary: Rails like number helpers in JS
License: BSD-2-Clause
Group: Development/Libraries
URL: https://github.com/emcien/number-helpers-coffeescript#readme
Source0: https://registry.npmjs.org/number_helpers/-/number_helpers-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.html %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr jasmine-core %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr specs %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc README.md

%changelog
* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 0.1.1-1
- Add nodejs-number_helpers generated by npm2rpm using the single strategy

