%global npm_name prop-types-extra

Name: nodejs-prop-types-extra
Version: 1.1.0
Release: 1%{?dist}
Summary: React PropType Utilities
License: MIT
Group: Development/Libraries
URL: https://github.com/react-bootstrap/prop-types-extra#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
Requires: npm(react-is) >= 16.3.2
Requires: npm(react-is) < 17.0.0
Requires: npm(warning) >= 4.0.0
Requires: npm(warning) < 5.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package
# https://github.com/react-bootstrap/prop-types-extra/pull/6
%nodejs_fixdep warning '^4.0.0'

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Wed Oct 10 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 1.1.0-1
- Add nodejs-prop-types-extra generated by npm2rpm using the single strategy

