%global npm_name browser-update

Name: nodejs-browser-update
Version: 3.2.5
Release: 1%{?dist}
Summary: Remind users to update their browser in an unobtrusive way
License: MIT
Group: Development/Libraries
URL: http://browser-update.org
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr update.npm.full.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr update.npm.js %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.txt
%doc README.md
%doc changelog.txt

%changelog
* Sun Jun 02 2019 Ohad Levy <ohadlevy@gmail.com> 3.2.5-1
- Add nodejs-browser-update generated by npm2rpm using the single strategy

