%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name react-transition-group

Name: %{?scl_prefix}nodejs-react-transition-group
Version: 2.4.0
Release: 2%{?dist}
Summary: A react component toolset for managing animations
License: BSD-3-Clause
Group: Development/Libraries
URL: https://github.com/reactjs/react-transition-group#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
%if 0%{?scl:1}
BuildRequires: %{?scl_prefix_nodejs}npm
%else
BuildRequires: nodejs-packaging
%endif
Requires: %{?scl_prefix}npm(dom-helpers) >= 3.3.1
Requires: %{?scl_prefix}npm(dom-helpers) < 4.0.0
Requires: %{?scl_prefix}npm(loose-envify) >= 1.3.1
Requires: %{?scl_prefix}npm(loose-envify) < 2.0.0
Requires: %{?scl_prefix}npm(prop-types) >= 15.6.2
Requires: %{?scl_prefix}npm(prop-types) < 16.0.0
Requires: %{?scl_prefix}npm(react-lifecycles-compat) >= 3.0.4
Requires: %{?scl_prefix}npm(react-lifecycles-compat) < 4.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr CSSTransition.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr ReplaceTransition.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Transition.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr TransitionGroup.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr utils %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Fri Oct 04 2019 Eric D. Helms <ericdhelms@gmail.com> - 2.4.0-2
- Update specs to handle SCL

* Wed Oct 10 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 2.4.0-1
- Add nodejs-react-transition-group generated by npm2rpm using the single strategy
