#!/bin/sh
# postinst script for foreman-*
#
# see: dh_installdeb(1)

if [ ! -z "${DEBUG}" ]; then
  set -x
else
  set -e
fi

. /usr/share/debconf/confmodule
. /usr/share/foreman/foreman-plugin.postinst-lib

# if this script aborts with an error dpkg can
# hang if daemons have been started
trap db_stop EXIT

foreman_plugin_install "foreman_default_hostgroup" "$2" "false" "false"

#DEBHELPER#

exit 0
