%global npm_name dom-helpers

Name: nodejs-dom-helpers
Version: 3.3.1
Release: 1%{?dist}
Summary: tiny modular DOM lib for ie8+
License: MIT
Group: Development/Libraries
URL: https://github.com/jquense/dom-helpers#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr activeElement.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr class %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr events %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr ownerDocument.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr ownerWindow.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr query %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr style %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr transition %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr util %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%doc README.md

%changelog
* Wed Oct 10 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 3.3.1-1
- Add nodejs-dom-helpers generated by npm2rpm using the single strategy

