%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name @module-federation/utilities

Name: %{?scl_prefix}nodejs-module-federation-utilities
Version: 1.9.1
Release: 1%{?dist}
Summary: FIXME
License: MIT
Group: Development/Libraries
URL: https://github.com/module-federation/universe/tree/main/packages/utilities
Source0: https://registry.npmjs.org/@module-federation/utilities/-/utilities-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%doc CHANGELOG.md
%doc README.md

%changelog
* Wed Dec 13 2023 Evgeni Golov 1.9.1-1
- Add nodejs-module-federation-utilities generated by npm2rpm using the single strategy

