%global npm_name @module-federation/utilities

Name: nodejs-module-federation-utilities
Version: 1.9.1
Release: 2%{?dist}
Summary: FIXME
License: MIT
URL: https://github.com/module-federation/universe/tree/main#readme
Source0: https://registry.npmjs.org/@module-federation/utilities/-/utilities-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%doc CHANGELOG.md
%doc README.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 1.9.1-2
- Regenerate spec file

* Wed Dec 13 2023 Evgeni Golov 1.9.1-1
- Add nodejs-module-federation-utilities generated by npm2rpm using the single strategy

