%global npm_name react-onclickoutside

Name: nodejs-react-onclickoutside
Version: 6.13.2
Release: 2%{?dist}
Summary: An onClickOutside wrapper for React components
License: MIT
URL: https://github.com/Pomax/react-onclickoutside
Source0: https://registry.npmjs.org/react-onclickoutside/-/react-onclickoutside-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 6.13.2-2
- Update to 6.13.2

* Wed Aug 27 2025 Foreman Packaging Automation <packaging@theforeman.org> 6.13.2-1
- Update to 6.13.2

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 6.6.2-1
- Add nodejs-react-onclickoutside generated by npm2rpm using the single strategy

