# template: default
%global gem_name colorize

Name: rubygem-%{gem_name}
Version: 0.8.1
Release: 3%{?dist}
Summary: Ruby gem for colorizing text using ANSI escape sequences
License: GPL-2.0
URL: http://github.com/fazibear/colorize
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: ruby
BuildRequires: ruby
BuildRequires: rubygems-devel
BuildArch: noarch
# end specfile generated dependencies

%description
Extends String class or add a ColorizedString with methods to set text color,
background color and text effects.


%package doc
Summary: Documentation for %{name}
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.

%prep
%setup -q -n  %{gem_name}-%{version}

%build
# Create the gem as gem install only works on a gem file
gem build ../%{gem_name}-%{version}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

%files
%dir %{gem_instdir}
%license %{gem_instdir}/LICENSE
%{gem_libdir}
%exclude %{gem_cache}
%{gem_spec}

%files doc
%doc %{gem_docdir}
%doc %{gem_instdir}/CHANGELOG
%doc %{gem_instdir}/README.md
%{gem_instdir}/Rakefile
%{gem_instdir}/colorize.gemspec
%{gem_instdir}/test

%changelog
* Wed Jul 22 2026 Zach Huntington-Meath <zhunting@redhat.com> - 0.8.1-3
- Re-add package, convert from SCL to default template

* Thu Mar 11 2021 Eric D. Helms <ericdhelms@gmail.com> - 0.8.1-2
- Rebuild against rh-ruby27

* Mon Apr 13 2020 Eric D. Helms <ericdhelms@gmail.com> 0.8.1-1
- Add rubygem-colorize generated by gem2rpm using the scl template
