%global npm_name react-dnd-html5-backend

Name: nodejs-react-dnd-html5-backend
Version: 14.1.0
Release: 2%{?dist}
Summary: HTML5 backend for React DnD
License: MIT
URL: https://github.com/react-dnd/react-dnd#readme
Source0: https://registry.npmjs.org/react-dnd-html5-backend/-/react-dnd-html5-backend-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
Requires: npm(dnd-core) = 14.0.1
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 14.1.0-2
- Update to 14.1.0

* Wed Jul 16 2025 Foreman Packaging Automation <packaging@theforeman.org> 14.1.0-1
- Update to 14.1.0

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 14.0.0-1
- Add nodejs-react-dnd-html5-backend generated by npm2rpm using the single strategy

