%global npm_name angular

Name: nodejs-angular
Version: 1.8.2
Release: 2%{?dist}
Summary: HTML enhanced for web apps
License: MIT
URL: http://angularjs.org
Source0: https://registry.npmjs.org/angular/-/angular-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr angular-csp.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr angular.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr angular.min.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr angular.min.js.gzip %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr angular.min.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 1.8.2-2
- Update to 1.8.2

* Wed Feb 24 2021 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 1.8.2-1
- Update to 1.8.2

* Wed Apr 01 2020 Justin Sherrill <jsherril@redhat.com> 1.7.9-1
- Update to 1.7.9

* Sun Oct 06 2019 Eric D. Helms <ericdhelms@gmail.com> - 1.5.5-2
- Update to handle building for SCL

* Wed Jan 09 2019 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 1.5.5-1
- Add nodejs-angular generated by npm2rpm using the single strategy
