%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name angular

Name: %{?scl_prefix}nodejs-angular
Version: 1.5.5
Release: 2%{?dist}
Summary: HTML enhanced for web apps
License: MIT
Group: Development/Libraries
URL: http://angularjs.org
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
%if 0%{?scl:1}
BuildRequires: %{?scl_prefix_nodejs}npm
%else
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr angular-csp.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr angular.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr angular.min.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr angular.min.js.gzip %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr angular.min.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%doc README.md

%changelog
* Sun Oct 06 2019 Eric D. Helms <ericdhelms@gmail.com> - 1.5.5-2
- Update to handle building for SCL

* Wed Jan 09 2019 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 1.5.5-1
- Add nodejs-angular generated by npm2rpm using the single strategy
