%global npm_name angular

Name: nodejs-angular
Version: 1.5.5
Release: 1%{?dist}
Summary: HTML enhanced for web apps
License: MIT
Group: Development/Libraries
URL: http://angularjs.org
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr angular-csp.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr angular.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr angular.min.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr angular.min.js.gzip %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr angular.min.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%doc README.md

%changelog
* Wed Jan 09 2019 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 1.5.5-1
- Add nodejs-angular generated by npm2rpm using the single strategy

