%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name decode-uri-component

Name: %{?scl_prefix}nodejs-decode-uri-component
Version: 0.2.2
Release: 1%{?dist}
Summary: A better decodeURIComponent
License: MIT
Group: Development/Libraries
URL: https://github.com/SamVerschueren/decode-uri-component#readme
Source0: https://registry.npmjs.org/decode-uri-component/-/decode-uri-component-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license license
%doc readme.md

%changelog
* Sun Jan 28 2024 Foreman Packaging Automation <packaging@theforeman.org> 0.2.2-1
- Update to 0.2.2

* Tue Oct 22 2019 Eric D. Helms <ericdhelms@gmail.com> 0.2.0-1
- Add nodejs-decode-uri-component generated by npm2rpm using the single strategy

