#!/bin/sh
# postinst script for foreman-*
#
# see: dh_installdeb(1)

if [ ! -z "${DEBUG}" ]; then
  set -x
else
  set -e
fi

. /usr/share/debconf/confmodule

LOGFILE='/var/log/foreman-install.log'
PLUGIN='foreman_hooks'

# if this script aborts with an error dpkg can
# hang if daemons have been started
trap db_stop EXIT

BUNDLE=bundle
[ -h /usr/bin/foreman-ruby ] && BUNDLE="/usr/bin/foreman-ruby /usr/bin/bundle"

# Update gems
export HOME=/usr/share/foreman
cd /usr/share/foreman
if [ ! -z "${DEBUG}" ]; then
  if [ -n "$2" ] ; then
    $BUNDLE update $PLUGIN --local
  else
    $BUNDLE install --local --no-prune
  fi
else
  if [ -n "$2" ] ; then
    $BUNDLE update $PLUGIN --local 2>&1 >> $LOGFILE
  else
    $BUNDLE install --local --no-prune 2>&1 >> $LOGFILE
  fi
fi

# Own all the core files
chown -Rf foreman:foreman '/usr/share/foreman'

GEM_INSTDIR=$(find /usr/share/foreman/vendor/ruby/*/gems -mindepth 1 -maxdepth 1 -name foreman_hooks\* -printf '%T+ %p\n' | sort -r | head -n 1 | awk '{ print $NF }')
if [ -n "$GEM_INSTDIR" ]; then
  chmod +x "$GEM_INSTDIR/extra/foreman-debug.sh"
  mkdir -p /usr/share/foreman/script/foreman-debug.d
  ln -sf "$GEM_INSTDIR/extra/foreman-debug.sh" /usr/share/foreman/script/foreman-debug.d/50-foreman_hooks
fi

#DEBHELPER#

exit 0
