#!/bin/sh
# postinst script for foreman-*
#
# see: dh_installdeb(1)

if [ ! -z "${DEBUG}" ]; then
  set -x
else
  set -e
fi

. /usr/share/debconf/confmodule
. /usr/share/foreman/foreman-plugin.postinst-lib

# if this script aborts with an error dpkg can
# hang if daemons have been started
trap db_stop EXIT

foreman_plugin_install "foreman_hooks" "$2" "false" "false"

GEM_INSTDIR=$(find /usr/share/foreman/vendor/ruby/*/gems -mindepth 1 -maxdepth 1 -name foreman_hooks\* -printf '%T+ %p\n' | sort -r | head -n 1 | awk '{ print $NF }')
if [ -n "$GEM_INSTDIR" ]; then
  chmod +x "$GEM_INSTDIR/extra/foreman-debug.sh"
  mkdir -p /usr/share/foreman/script/foreman-debug.d
  ln -sf "$GEM_INSTDIR/extra/foreman-debug.sh" /usr/share/foreman/script/foreman-debug.d/50-foreman_hooks
fi

#DEBHELPER#

exit 0
