#!/bin/sh

[ -n "${DEBUG}" ] && set -x
set -e

. /usr/share/debconf/confmodule

#DEBHELPER#

if [ -h /usr/share/foreman/script/foreman-debug.d/50-foreman_hooks -a "x$1" = xremove ]; then
  rm -f /usr/share/foreman/script/foreman-debug.d/50-foreman_hooks
fi

exit 0
