%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name ngreact

Name: %{?scl_prefix}nodejs-ngreact
Version: 0.5.2
Release: 1%{?dist}
Summary: Use React Components in Angular
License: MIT
Group: Development/Libraries
URL: http://davidchang.github.io/ngReact/
Source0: https://registry.npmjs.org/ngreact/-/ngreact-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr examples %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr karma.config.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr ngReact.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr ngReact.min.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr tests %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc CHANGES.md
%doc README.md

%changelog
* Sun Jan 28 2024 Foreman Packaging Automation <packaging@theforeman.org> 0.5.2-1
- Update to 0.5.2

* Sun Oct 06 2019 Eric D. Helms <ericdhelms@gmail.com> - 0.5.1-2
- Update to handle building for SCL

* Wed Jan 09 2019 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 0.5.1-1
- Add nodejs-ngreact generated by npm2rpm using the single strategy
