%global npm_name ngreact

Name: nodejs-ngreact
Version: 0.5.1
Release: 1%{?dist}
Summary: Use React Components in Angular
License: MIT
Group: Development/Libraries
URL: http://davidchang.github.io/ngReact/
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr ngReact.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc CHANGES.md
%doc README.md
%doc examples

%changelog
* Wed Jan 09 2019 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 0.5.1-1
- Add nodejs-ngreact generated by npm2rpm using the single strategy

