%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name @webcomponents/webcomponentsjs

Name: %{?scl_prefix}nodejs-webcomponents-webcomponentsjs
Version: 2.2.10
Release: 1%{?dist}
Summary: Web Components Polyfills
License: BSD-3-Clause
Group: Development/Libraries
URL: https://webcomponents.org/polyfills
Source0: https://registry.npmjs.org/@webcomponents/webcomponentsjs/-/webcomponentsjs-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr bundles %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr custom-elements-es5-adapter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr entrypoints %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr webcomponents-bundle.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr webcomponents-bundle.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr webcomponents-loader.js %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc README.md

%changelog
* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 2.2.10-1
- Add nodejs-webcomponents-webcomponentsjs generated by npm2rpm using the single strategy

