%global npm_name @webcomponents/webcomponentsjs

Name: nodejs-webcomponents-webcomponentsjs
Version: 2.8.0
Release: 2%{?dist}
Summary: Web Components Polyfills
License: BSD-3-Clause
URL: https://github.com/webcomponents/polyfills/tree/master/packages/webcomponentsjs
Source0: https://registry.npmjs.org/@webcomponents/webcomponentsjs/-/webcomponentsjs-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr bundles %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr custom-elements-es5-adapter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr webcomponents-bundle.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr webcomponents-bundle.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr webcomponents-bundle.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr webcomponents-loader.js %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc CHANGELOG.md
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 2.8.0-2
- Update to 2.8.0

* Wed Aug 27 2025 Foreman Packaging Automation <packaging@theforeman.org> 2.8.0-1
- Update to 2.8.0

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 2.2.10-1
- Add nodejs-webcomponents-webcomponentsjs generated by npm2rpm using the single strategy

