%global npm_name argv-parse

Name: nodejs-argv-parse
Version: 1.0.1
Release: 5%{?dist}
Summary: Parse command line arguments
License: ISC
URL: https://github.com/paulcpederson/argv-parse
Source0: https://registry.npmjs.org/argv-parse/-/argv-parse-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr test %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 1.0.1-5
- Update to 1.0.1

* Tue Mar 17 2020 Zach Huntington-Meath <zhunting@redhat.com> - 1.0.1-4
- Bump packages to build for el8

* Mon Oct 21 2019 Eric D. Helms <ericdhelms@gmail.com> - 1.0.1-3
- Build for SCL

* Fri Oct 04 2019 Eric D. Helms <ericdhelms@gmail.com> - 1.0.1-2
- Update specs to handle SCL

* Wed Jan 09 2019 Ohad Levy <ohadlevy@gmail.com> 1.0.1-1
- Add nodejs-argv-parse generated by npm2rpm using the single strategy
