%global npm_name argv-parse
%global enable_tests 1

Name: nodejs-%{npm_name}
Version: 1.0.1
Release: 1%{?dist}
Summary: Parse command line arguments
License: ISC
Group: Development/Libraries
URL: https://github.com/paulcpederson/argv-parse
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr test %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%if 0%{?enable_tests}
%check
%{nodejs_symlink_deps} --check
%endif

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Wed Jan 09 2019 Ohad Levy <ohadlevy@gmail.com> 1.0.1-1
- Add nodejs-argv-parse generated by npm2rpm using the single strategy

