%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name redux-logger

Name: %{?scl_prefix}nodejs-redux-logger
Version: 2.10.2
Release: 1%{?dist}
Summary: Logger for Redux
License: MIT
Group: Development/Libraries
URL: https://github.com/theaqua/redux-logger#readme
Source0: https://registry.npmjs.org/redux-logger/-/redux-logger-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
Requires: npm(deep-diff) = 0.3.4
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Wed Jul 16 2025 Foreman Packaging Automation <packaging@theforeman.org> 2.10.2-1
- Update to 2.10.2

* Thu Jul 03 2025 root <root> 2.8.1-1
- Add nodejs-redux-logger generated by npm2rpm using the single strategy

