%global npm_name regenerator-runtime
%global enable_tests 1

Name: nodejs-%{npm_name}
Version: 0.11.1
Release: 1%{?dist}
Summary: Runtime for Regenerator-compiled generator and async functions
License: MIT
Group: Development/Libraries
URL: https://github.com/facebook/regenerator/tree/master/packages/regenerator-runtime
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr path.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr runtime-module.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr runtime.js %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%if 0%{?enable_tests}
%check
%{nodejs_symlink_deps} --check
%endif

%files
%{nodejs_sitelib}/%{npm_name}
%doc README.md

%changelog
* Thu Apr 26 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 0.11.1-1
- Add nodejs-regenerator-runtime generated by npm2rpm using the single strategy

