%global npm_name react-router-dom
%global enable_tests 1

Name: nodejs-%{npm_name}
Version: 4.3.1
Release: 1%{?dist}
Summary: DOM bindings for React Router
License: MIT
Group: Development/Libraries
URL: https://github.com/ReactTraining/react-router#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
Requires: npm(history) >= 4.7.2
Requires: npm(history) < 5.0.0
Requires: npm(invariant) >= 2.2.4
Requires: npm(invariant) < 3.0.0
Requires: npm(loose-envify) >= 1.3.1
Requires: npm(loose-envify) < 2.0.0
Requires: npm(prop-types) >= 15.6.1
Requires: npm(prop-types) < 16.0.0
Requires: npm(react-router) >= 4.3.1
Requires: npm(react-router) < 5.0.0
Requires: npm(warning) >= 4.0.1
Requires: npm(warning) < 5.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr BrowserRouter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr HashRouter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Link.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr MemoryRouter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr NavLink.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Prompt.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Redirect.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Route.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Router.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr StaticRouter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Switch.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr es %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr generatePath.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr matchPath.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr umd %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr withRouter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%if 0%{?enable_tests}
%check
%{nodejs_symlink_deps} --check
%endif

%files
%{nodejs_sitelib}/%{npm_name}
%doc README.md

%changelog
* Thu Jun 07 2018 Eric D. Helms <ericdhelms@gmail.com> 4.3.1-1
- Update to 4.3.1

* Thu Apr 19 2018 Eric D. Helms <ericdhelms@gmail.com> 4.2.2-1
- Add nodejs-react-router-dom generated by npm2rpm using the single strategy

