#!/usr/bin/foreman-ruby

foreman_root = "/usr/share/foreman"
require File.expand_path('./config/application', foreman_root)
ForemanTasks::Dynflow::Daemon.new.run_background(ARGV.last, :foreman_root => foreman_root)
