%global npm_name ts-loader

Name: nodejs-ts-loader
Version: 9.6.2
Release: 2%{?dist}
Summary: TypeScript loader for webpack
License: MIT
Group: Development/Libraries
URL: https://github.com/TypeStrong/ts-loader
Source0: https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz
Source1: https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz
Source2: https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz
Source3: https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz
Source4: https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz
Source5: https://registry.npmjs.org/picomatch/-/picomatch-4.0.5.tgz
Source6: https://registry.npmjs.org/source-map/-/source-map-0.7.6.tgz
Source7: https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz
Source8: https://registry.npmjs.org/ts-loader/-/ts-loader-9.6.2.tgz
Source9: nodejs-ts-loader-%{version}-package-lock.json
BuildRequires: npm >= 7
BuildRequires: nodejs-packaging
# The prep section runs node directly, so this is needed unconditionally. It
# also works around https://issues.redhat.com/browse/RHEL-137712 on RHEL 10
# before 10.3, where the nodejs major version macro does not resolve without
# node in the buildroot.
BuildRequires: /usr/bin/node
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

Provides: npm(%{npm_name}) = %{version}
Provides: bundled(npm(ansi-styles)) = 4.3.0
Provides: bundled(npm(chalk)) = 4.1.2
Provides: bundled(npm(color-convert)) = 2.0.1
Provides: bundled(npm(color-name)) = 1.1.4
Provides: bundled(npm(has-flag)) = 4.0.0
Provides: bundled(npm(picomatch)) = 4.0.5
Provides: bundled(npm(source-map)) = 0.7.6
Provides: bundled(npm(supports-color)) = 7.2.0
Provides: bundled(npm(ts-loader)) = 9.6.2
AutoReq: no
AutoProv: no

%define npm_cache_dir npm_cache_%{name}-%{version}-%{release}

%description
%{summary}

%prep
mkdir -p %{npm_cache_dir}
# npm ci installs the tree recorded in the lockfile: every entry carries a
# resolved URL and an integrity hash, and npm serves the tarballs from the
# cache primed here by content hash. No registry access is needed.
for src in %{sources}; do
  case "$src" in
    *.tgz) npm cache add --cache %{npm_cache_dir} "$src" ;;
    *-package-lock.json) cp "$src" package-lock.json ;;
  esac
done

# Derive package.json from the lockfile so the two cannot disagree.
node -e '
const fs = require("fs");
const lock = JSON.parse(fs.readFileSync("package-lock.json"));
fs.writeFileSync("package.json", JSON.stringify({
  name: lock.name,
  version: lock.version,
  dependencies: lock.packages[""].dependencies
}, null, 2) + "\n");
'

%build
npm ci --legacy-peer-deps --offline --cache %{_builddir}/%{npm_cache_dir} --omit optional

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
# npm creates a scope directory for every scope named in the lockfile, including
# scopes whose packages were all omitted, which leaves empty dirs behind.
# -delete implies -depth, so nested empties go bottom-up in a single pass.
find %{buildroot}%{nodejs_sitelib}/%{npm_name} -type d -empty -delete
cp -pfr node_modules/%{npm_name}/dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/eslint.config.mjs %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/renovate.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%files
%{nodejs_sitelib}/%{npm_name}
%license node_modules/%{npm_name}/LICENSE
%doc node_modules/%{npm_name}/AGENTS.md
%doc node_modules/%{npm_name}/CHANGELOG.md
%doc node_modules/%{npm_name}/CLAUDE.md
%doc node_modules/%{npm_name}/README.md
%doc node_modules/%{npm_name}/REFERENCES.md
%doc node_modules/%{npm_name}/SECURITY.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 9.6.2-2
- Update to 9.6.2

* Wed Jun 24 2026 Foreman Packaging Automation <packaging@theforeman.org> 9.6.2-1
- Update to 9.6.2

* Wed Jun 17 2026 Foreman Packaging Automation <packaging@theforeman.org> 9.6.1-1
- Update to 9.6.1

* Sun May 31 2026 Foreman Packaging Automation <packaging@theforeman.org> 9.6.0-1
- Update to 9.6.0

* Sun May 17 2026 Foreman Packaging Automation <packaging@theforeman.org> 9.5.7-1
- Update to 9.5.7

* Mon Mar 23 2026 Nadja Heitmann <nadjah@atix.de> 9.5.2-1
- Add nodejs-ts-loader generated by npm2rpm using the bundle strategy

