%global npm_name react-intl

Name: nodejs-react-intl
Version: 2.7.2
Release: 1%{?dist}
Summary: Internationalize React apps
License: BSD-3-Clause
Group: Development/Libraries
URL: https://github.com/yahoo/react-intl
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
Requires: npm(hoist-non-react-statics) >= 2.5.5
Requires: npm(hoist-non-react-statics) < 3.0.0
Requires: npm(intl-format-cache) >= 2.0.5
Requires: npm(intl-format-cache) < 3.0.0
Requires: npm(intl-messageformat) >= 2.1.0
Requires: npm(intl-messageformat) < 3.0.0
Requires: npm(intl-relativeformat) >= 2.1.0
Requires: npm(intl-relativeformat) < 3.0.0
Requires: npm(invariant) >= 2.1.1
Requires: npm(invariant) < 3.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr locale-data %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc CONTRIBUTING.md
%doc README.md

%changelog
* Wed Jan 09 2019 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 2.7.2-1
- Add nodejs-react-intl generated by npm2rpm using the single strategy

