%global npm_name graphql

Name: nodejs-graphql
Version: 15.10.3
Release: 1%{?dist}
Summary: A Query Language and Runtime which can target any service
License: MIT
URL: https://github.com/graphql/graphql-js
Source0: https://registry.npmjs.org/graphql/-/graphql-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr error %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr execution %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr graphql.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr graphql.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr graphql.js.flow %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr graphql.mjs %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js.flow %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.mjs %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr jsutils %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr language %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr polyfills %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr subscription %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr type %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr utilities %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr validation %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr version.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr version.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr version.js.flow %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr version.mjs %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Fri Sep 04 2026 Foreman Packaging Automation <packaging@theforeman.org> 15.10.3-1
- Update to 15.10.3

* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 15.10.2-2
- Update to 15.10.2

* Sun Apr 12 2026 Foreman Packaging Automation <packaging@theforeman.org> 15.10.2-1
- Update to 15.10.2

* Wed Jan 15 2025 Foreman Packaging Automation <packaging@theforeman.org> 15.10.1-1
- Update to 15.10.1

* Sun Jun 23 2024 Foreman Packaging Automation <packaging@theforeman.org> 15.9.0-1
- Update to 15.9.0

* Fri Aug 11 2023 Foreman Packaging Automation <packaging@theforeman.org> 15.8.0-1
- Update to 15.8.0

* Wed Jun 09 2021 Ondrej Prazak <oprazak@redhat.com> 15.5.0-1
- Add nodejs-graphql generated by npm2rpm using the single strategy

