# template: default
%global gem_name auth-sanitizer

Name: rubygem-%{gem_name}
Version: 0.2.2
Release: 1%{?dist}
Summary: Configurable KV output redaction
License: MIT
URL: https://github.com/ruby-oauth/auth-sanitizer
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: ruby >= 2.2.0
BuildRequires: ruby >= 2.2.0
BuildRequires: rubygems-devel
BuildArch: noarch
# end specfile generated dependencies

%description
Configurable KV output redaction. Sanitize and filter your secrets.


%package doc
Summary: Documentation for %{name}
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.

%prep
%setup -q -n  %{gem_name}-%{version}

%build
# Create the gem as gem install only works on a gem file
gem build ../%{gem_name}-%{version}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

%files
%dir %{gem_instdir}
%exclude %{gem_instdir}/CITATION.cff
%exclude %{gem_instdir}/certs
%license %{gem_instdir}/LICENSE.md
%{gem_libdir}
%exclude %{gem_instdir}/sig
%exclude %{gem_cache}
%{gem_spec}

%files doc
%doc %{gem_docdir}
%doc %{gem_instdir}/CHANGELOG.md
%doc %{gem_instdir}/CODE_OF_CONDUCT.md
%doc %{gem_instdir}/CONTRIBUTING.md
%doc %{gem_instdir}/FUNDING.md
%doc %{gem_instdir}/README.md
%doc %{gem_instdir}/RUBOCOP.md
%doc %{gem_instdir}/SECURITY.md

%changelog
* Tue Jun 23 2026 Foreman Packaging Automation <packaging@theforeman.org> - 0.2.2-1
- Update to 0.2.2

* Tue Jun 16 2026 Ondřej Gajdušek <ogajduse@redhat.com> 0.2.1-1
- Add rubygem-auth-sanitizer generated by gem2rpm using the default template
