%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name @scalprum/react-core

Name: %{?scl_prefix}nodejs-scalprum-react-core
Version: 0.9.5
Release: 1%{?dist}
Summary: React binding for @scalprum/core package
License: Apache-2.0
Group: Development/Libraries
URL: https://github.com/scalprum/scaffloding#readme
Source0: https://registry.npmjs.org/@scalprum/react-core/-/react-core-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
Requires: npm(@openshift/dynamic-plugin-sdk) >= 5.0.1
Requires: npm(@openshift/dynamic-plugin-sdk) < 6.0.0
Requires: npm(@scalprum/core) >= 0.8.3
Requires: npm(@scalprum/core) < 0.9.0
Requires: npm(lodash) >= 4.17.0
Requires: npm(lodash) < 5.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr TestComponent.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr TestComponent.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr TestComponent.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr async-loader.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr async-loader.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr async-loader.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr default-error-component.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr default-error-component.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr default-error-component.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr esm %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr prefetch-context.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr prefetch-context.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr prefetch-context.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr scalprum-component.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr scalprum-component.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr scalprum-component.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr scalprum-context.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr scalprum-context.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr scalprum-context.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr scalprum-provider.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr scalprum-provider.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr scalprum-provider.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr use-load-module.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr use-load-module.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr use-load-module.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr use-module.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr use-module.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr use-module.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr use-prefetch.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr use-prefetch.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr use-prefetch.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr use-scalprum.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr use-scalprum.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr use-scalprum.js.map %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%doc CHANGELOG.md
%doc README.md

%changelog
* Wed Jul 09 2025 root <root> 0.9.5-1
- Add nodejs-scalprum-react-core generated by npm2rpm using the single strategy

