#!/bin/sh
# postinst script for foreman-*
#
# see: dh_installdeb(1)

if [ ! -z "${DEBUG}" ]; then
  set -x
else
  set -e
fi

. /usr/share/debconf/confmodule

LOGFILE='/var/log/foreman-install.log'
PLUGIN='foreman_docker'

# if this script aborts with an error dpkg can
# hang if daemons have been started
trap db_stop EXIT

BUNDLE=bundle
[ -h /usr/bin/foreman-ruby ] && BUNDLE="/usr/bin/foreman-ruby /usr/bin/bundle"

# Update gems
cd /usr/share/foreman
if [ ! -z "${DEBUG}" ]; then
  if $BUNDLE show $PLUGIN >/dev/null 2>&1; then
    $BUNDLE update $PLUGIN --local
  else
    $BUNDLE install --local --no-prune
  fi
else
  if $BUNDLE show $PLUGIN >/dev/null 2>&1; then
    $BUNDLE update $PLUGIN --local 2>&1 >> $LOGFILE
  else
    $BUNDLE install --local --no-prune 2>&1 >> $LOGFILE
  fi
fi

# Own all the core files
chown -Rf foreman:foreman '/usr/share/foreman'

#DEBHELPER#

exit 0
