%global npm_name urijs

Name: nodejs-urijs
Version: 1.19.11
Release: 2%{?dist}
Summary: URI
License: MIT
URL: http://medialize.github.io/URI.js/
Source0: https://registry.npmjs.org/urijs/-/urijs-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.txt
%doc README.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 1.19.11-2
- Regenerate spec file

* Wed Jul 16 2025 Foreman Packaging Automation <packaging@theforeman.org> 1.19.11-1
- Update to 1.19.11

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 1.19.4-1
- Add nodejs-urijs generated by npm2rpm using the single strategy

