%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name urijs

Name: %{?scl_prefix}nodejs-urijs
Version: 1.19.4
Release: 1%{?dist}
Summary: URI
License: MIT
Group: Development/Libraries
URL: http://medialize.github.io/URI.js/
Source0: https://registry.npmjs.org/urijs/-/urijs-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.txt
%doc CHANGELOG.md
%doc README.md

%changelog
* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 1.19.4-1
- Add nodejs-urijs generated by npm2rpm using the single strategy

