%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name tslib

Name: %{?scl_prefix}nodejs-tslib
Version: 2.8.0
Release: 1%{?dist}
Summary: Runtime library for TypeScript helper functions
License: 0BSD
Group: Development/Libraries
URL: https://www.typescriptlang.org/
Source0: https://registry.npmjs.org/tslib/-/tslib-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr tslib.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr tslib.es6.html %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr tslib.es6.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr tslib.es6.mjs %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr tslib.html %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr tslib.js %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.txt
%doc CopyrightNotice.txt
%doc README.md
%doc SECURITY.md

%changelog
* Mon Oct 21 2024 Foreman Packaging Automation <packaging@theforeman.org> 2.8.0-1
- Update to 2.8.0

* Sun Sep 01 2024 Foreman Packaging Automation <packaging@theforeman.org> 2.7.0-1
- Update to 2.7.0

* Sun Jun 09 2024 Foreman Packaging Automation <packaging@theforeman.org> 2.6.3-1
- Update to 2.6.3

* Tue Sep 12 2023 Eric D. Helms <ericdhelms@gmail.com> 2.6.2-1
- Add nodejs-tslib generated by npm2rpm using the single strategy

