%global npm_name diff-match-patch

Name: nodejs-diff-match-patch
Version: 1.0.4
Release: 1%{?dist}
Summary: npm package for https://github
License: Apache-2.0
Group: Development/Libraries
URL: https://github.com/JackuB/diff-match-patch#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Mon Feb 25 2019 Ohad Levy <ohadlevy@gmail.com> 1.0.4-1
- Add nodejs-diff-match-patch generated by npm2rpm using the single strategy

