%global npm_name react-loading-skeleton

Name: nodejs-react-loading-skeleton
Version: 1.3.0
Release: 2%{?dist}
Summary: FIXME
License: MIT
URL: https://github.com/dvtng/react-loading-skeleton#readme
Source0: https://registry.npmjs.org/react-loading-skeleton/-/react-loading-skeleton-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
Requires: npm(emotion) >= 10.0.17
Requires: npm(emotion) < 11.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc README.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 1.3.0-2
- Regenerate spec file

* Thu Jul 03 2025 root <root> 1.3.0-1
- Add nodejs-react-loading-skeleton generated by npm2rpm using the single strategy

