%global npm_name create-react-context

Name: nodejs-create-react-context
Version: 0.2.3
Release: 1%{?dist}
Summary: Polyfill for the proposed React context API
License: MIT
Group: Development/Libraries
URL: https://github.com/thejameskyle/create-react-context#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
Requires: npm(fbjs) >= 0.8.0
Requires: npm(fbjs) < 1.0.0
Requires: npm(gud) >= 1.0.0
Requires: npm(gud) < 2.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Wed Oct 10 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 0.2.3-1
- Add nodejs-create-react-context generated by npm2rpm using the single strategy

