# template: scl
%{?scl:%scl_package rubygem-%{gem_name}}
%{!?scl:%global pkg_name %{name}}

%global gem_name gapic-common
%global gem_require_name %{gem_name}

Name: %{?scl_prefix}rubygem-%{gem_name}
Version: 0.9.0
Release: 1%{?dist}
Summary: Common code for GAPIC-generated API clients
Group: Development/Languages
License: Apache-2.0
URL: https://github.com/googleapis/gapic-generator-ruby
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: %{?scl_prefix_ruby}ruby(release)
Requires: %{?scl_prefix_ruby}ruby >= 2.5
Requires: %{?scl_prefix_ruby}ruby(rubygems)
Requires: %{?scl_prefix}rubygem(faraday) >= 1.3
Requires: %{?scl_prefix}rubygem(faraday) < 2
Requires: %{?scl_prefix}rubygem(googleapis-common-protos) >= 1.3.11
Requires: %{?scl_prefix}rubygem(googleapis-common-protos) < 2.a
Requires: %{?scl_prefix}rubygem(googleapis-common-protos-types) >= 1.0.6
Requires: %{?scl_prefix}rubygem(googleapis-common-protos-types) < 2.a
Requires: %{?scl_prefix}rubygem(googleauth) >= 0.17.0
Requires: %{?scl_prefix}rubygem(googleauth) < 2.a
Requires: %{?scl_prefix}rubygem(google-protobuf) >= 3.14
Requires: %{?scl_prefix}rubygem(google-protobuf) < 4
Requires: %{?scl_prefix}rubygem(grpc) >= 1.36
Requires: %{?scl_prefix}rubygem(grpc) < 2
BuildRequires: %{?scl_prefix_ruby}ruby(release)
BuildRequires: %{?scl_prefix_ruby}ruby >= 2.5
BuildRequires: %{?scl_prefix_ruby}rubygems-devel
BuildArch: noarch
Provides: %{?scl_prefix}rubygem(%{gem_name}) = %{version}
# end specfile generated dependencies

%description
Common code for GAPIC-generated API clients.


%package doc
Summary: Documentation for %{pkg_name}
Group: Documentation
Requires: %{?scl_prefix}%{pkg_name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{pkg_name}.

%prep
%{?scl:scl enable %{scl} - << \EOF}
gem unpack %{SOURCE0}
%{?scl:EOF}

%setup -q -D -T -n  %{gem_name}-%{version}

%{?scl:scl enable %{scl} - << \EOF}
gem spec %{SOURCE0} -l --ruby > %{gem_name}.gemspec
%{?scl:EOF}

%build
# Create the gem as gem install only works on a gem file
%{?scl:scl enable %{scl} - << \EOF}
gem build %{gem_name}.gemspec
%{?scl:EOF}

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%{?scl:scl enable %{scl} - << \EOF}
%gem_install
%{?scl:EOF}

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

%files
%dir %{gem_instdir}
%exclude %{gem_instdir}/.yardopts
%{gem_instdir}/CODE_OF_CONDUCT.md
%license %{gem_instdir}/LICENSE
%{gem_instdir}/RELEASING.md
%{gem_libdir}
%exclude %{gem_cache}
%{gem_spec}

%files doc
%doc %{gem_docdir}
%doc %{gem_instdir}/CHANGELOG.md
%doc %{gem_instdir}/CONTRIBUTING.md
%doc %{gem_instdir}/README.md

%changelog
* Tue May 24 2022 Leos Stejskal <lstejska@redhat.com> 0.9.0-1
- Add rubygem-gapic-common generated by gem2rpm using the scl template

