%global npm_name lodash.debounce

Name: nodejs-lodash.debounce
Version: 4.0.8
Release: 2%{?dist}
Summary: The lodash method `_
License: MIT
URL: https://lodash.com/
Source0: https://registry.npmjs.org/lodash.debounce/-/lodash.debounce-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 4.0.8-2
- Update to 4.0.8

* Tue Jul 08 2025 root <root> 4.0.8-1
- Add nodejs-lodash.debounce generated by npm2rpm using the single strategy

