%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name lodash.debounce

Name: %{?scl_prefix}nodejs-lodash.debounce
Version: 4.0.8
Release: 1%{?dist}
Summary: The lodash method `_
License: MIT
Group: Development/Libraries
URL: https://lodash.com/
Source0: https://registry.npmjs.org/lodash.debounce/-/lodash.debounce-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Tue Jul 08 2025 root <root> 4.0.8-1
- Add nodejs-lodash.debounce generated by npm2rpm using the single strategy

