%global npm_name dnd-core

Name: nodejs-dnd-core
Version: 14.0.1
Release: 2%{?dist}
Summary: Drag and drop sans the GUI
License: MIT
Group: Development/Libraries
URL: https://github.com/react-dnd/react-dnd#readme
Source0: https://registry.npmjs.org/@babel/runtime/-/runtime-7.29.7.tgz
Source1: https://registry.npmjs.org/@react-dnd/asap/-/asap-4.0.1.tgz
Source2: https://registry.npmjs.org/@react-dnd/invariant/-/invariant-2.0.0.tgz
Source3: https://registry.npmjs.org/dnd-core/-/dnd-core-14.0.1.tgz
Source4: https://registry.npmjs.org/redux/-/redux-4.2.1.tgz
Source5: nodejs-dnd-core-%{version}-registry.npmjs.org.tgz
BuildRequires: npm >= 7
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

Provides: npm(%{npm_name}) = %{version}
Provides: bundled(npm(@babel/runtime)) = 7.29.7
Provides: bundled(npm(@react-dnd/asap)) = 4.0.1
Provides: bundled(npm(@react-dnd/invariant)) = 2.0.0
Provides: bundled(npm(dnd-core)) = 14.0.1
Provides: bundled(npm(redux)) = 4.2.1
AutoReq: no
AutoProv: no

%define npm_cache_dir npm_cache_%{name}-%{version}-%{release}

%description
%{summary}

%prep
mkdir -p %{npm_cache_dir}
for tgz in %{sources}; do
  echo $tgz | grep -q registry.npmjs.org || npm cache add --cache %{npm_cache_dir} $tgz
done

%setup -T -q -a 5 -D -n %{npm_cache_dir}

%build
npm install --legacy-peer-deps --offline --cache %{_builddir}/%{npm_cache_dir} --package-lock false --omit optional --install-strategy shallow %{npm_name}@%{version}

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%files
%{nodejs_sitelib}/%{npm_name}
%license node_modules/%{npm_name}/LICENSE
%doc node_modules/%{npm_name}/README.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 14.0.1-2
- Regenerate spec file

* Wed Jul 16 2025 Foreman Packaging Automation <packaging@theforeman.org> 14.0.1-1
- Update to 14.0.1

* Tue Jul 08 2025 root <root> 14.0.0-1
- Add nodejs-dnd-core generated by npm2rpm using the bundle strategy

