%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name js-cookie

Name: %{?scl_prefix}nodejs-js-cookie
Version: 3.0.5
Release: 1%{?dist}
Summary: A simple, lightweight JavaScript API for handling cookies
License: MIT
Group: Development/Libraries
URL: https://github.com/js-cookie/js-cookie#readme
Source0: https://registry.npmjs.org/js-cookie/-/js-cookie-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Mon Jul 22 2024 MariaAga <mariaaga@redhat.com> 3.0.5-1
- Add nodejs-js-cookie generated by npm2rpm using the single strategy

