%global npm_name js-cookie

Name: nodejs-js-cookie
Version: 3.0.8
Release: 1%{?dist}
Summary: A simple, lightweight JavaScript API for handling cookies
License: MIT
URL: https://github.com/js-cookie/js-cookie#readme
Source0: https://registry.npmjs.org/js-cookie/-/js-cookie-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Sun Jun 07 2026 Foreman Packaging Automation <packaging@theforeman.org> 3.0.8-1
- Update to 3.0.8

* Mon Jul 22 2024 MariaAga <mariaaga@redhat.com> 3.0.5-1
- Add nodejs-js-cookie generated by npm2rpm using the single strategy

