%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name multiselect

Name: %{?scl_prefix}nodejs-multiselect
Version: 0.9.12
Release: 1%{?dist}
Summary: A user-friendlier drop-in replacement for the standard select with multiple attribute activated
License: WTFPL
Group: Development/Libraries
URL: https://www.npmjs.com/package/multiselect
Source0: https://registry.npmjs.org/multiselect/-/multiselect-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
Requires: npm(jquery) >= 1.7.1
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr img %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr multi-select.jquery.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr test %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.txt
%doc README.markdown

%changelog
* Fri Jun 13 2025 MariaAga <mariaaga@redhat.com> 0.9.12-1
- Add nodejs-multiselect generated by npm2rpm using the single strategy

