%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name downshift

Name: %{?scl_prefix}nodejs-downshift
Version: 5.4.7
Release: 1%{?dist}
Summary: A set of primitives to build simple, flexible, WAI-ARIA compliant React autocomplete components
License: MIT
Group: Development/Libraries
URL: https://github.com/downshift-js/downshift#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
%if 0%{?scl:1}
BuildRequires: %{?scl_prefix_nodejs}npm
%else
BuildRequires: nodejs-packaging
BuildRequires: npm
%endif
Requires: %{?scl_prefix}npm(babel/runtime) >= 7.10.2
Requires: %{?scl_prefix}npm(babel/runtime) < 8.0.0
Requires: %{?scl_prefix}npm(compute-scroll-into-view) >= 1.0.14
Requires: %{?scl_prefix}npm(compute-scroll-into-view) < 2.0.0
Requires: %{?scl_prefix}npm(prop-types) >= 15.7.2
Requires: %{?scl_prefix}npm(prop-types) < 16.0.0
Requires: %{?scl_prefix}npm(react-is) >= 16.13.1
Requires: %{?scl_prefix}npm(react-is) < 17.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package
%nodejs_fixdep -r @babel/runtime

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr flow-typed %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr typings %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Tue Jul 21 2020 John Mitsch <jomitsch@redhat.com> 5.4.7-1
- Update to 5.4.7

* Sun Oct 06 2019 Eric D. Helms <ericdhelms@gmail.com> - 1.31.15-2
- Update to handle building for SCL

* Thu Jun 07 2018 Eric D. Helms <ericdhelms@gmail.com> 1.31.15-1
- Update to 1.31.15

* Thu Apr 19 2018 Eric D. Helms <ericdhelms@gmail.com> 1.28.0-1
- Add nodejs-downshift generated by npm2rpm using the single strategy
