%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name downshift

Name: %{?scl_prefix}nodejs-downshift
Version: 1.31.15
Release: 2%{?dist}
Summary: A set of primitives to build simple, flexible, WAI-ARIA compliant React autocomplete components
License: MIT
Group: Development/Libraries
URL: https://github.com/paypal/downshift#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
%if 0%{?scl:1}
BuildRequires: %{?scl_prefix_nodejs}npm
%else
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr preact %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr typings %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Sun Oct 06 2019 Eric D. Helms <ericdhelms@gmail.com> - 1.31.15-2
- Update to handle building for SCL

* Thu Jun 07 2018 Eric D. Helms <ericdhelms@gmail.com> 1.31.15-1
- Update to 1.31.15

* Thu Apr 19 2018 Eric D. Helms <ericdhelms@gmail.com> 1.28.0-1
- Add nodejs-downshift generated by npm2rpm using the single strategy
