#!/bin/sh
# postinst script for foreman-*
#
# see: dh_installdeb(1)

if [ ! -z "${DEBUG}" ]; then
  set -x
else
  set -e
fi

. /usr/share/debconf/confmodule

LOGFILE='/var/log/foreman-install.log'
PLUGIN='foreman_bootdisk'

# if this script aborts with an error dpkg can
# hang if daemons have been started
trap db_stop EXIT

# Update gems
cd /usr/share/foreman
if [ ! -z "${DEBUG}" ]; then
  if bundle show $PLUGIN >/dev/null 2>&1; then
    bundle update $PLUGIN
  else
    bundle install
  fi
else
  if bundle show $PLUGIN >/dev/null 2>&1; then
    bundle update $PLUGIN 2>&1 >> $LOGFILE
  else
    bundle install 2>&1 >> $LOGFILE
  fi
fi

# DB migrate/seed after install
if [ -f /usr/share/foreman/config/database.yml ]; then
  if [ ! -z "${DEBUG}" ]; then
    /usr/sbin/foreman-rake db:migrate || true
    /usr/sbin/foreman-rake db:seed || true
  else
    /usr/sbin/foreman-rake db:migrate >> $LOGFILE 2>&1 || true
    /usr/sbin/foreman-rake db:seed >> $LOGFILE 2>&1 || true
  fi
fi

# Own all the core files
chown -Rf foreman:foreman '/usr/share/foreman'

#DEBHELPER#

exit 0
