%global npm_name linear-layout-vector

Name: nodejs-linear-layout-vector
Version: 0.0.1
Release: 1%{?dist}
Summary: A sparse array of sizes that represent items in a dimension
License: ISC
Group: Development/Libraries
URL: https://www.npmjs.com/package/linear-layout-vector
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}

%changelog
* Thu May 16 2019 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 0.0.1-1
- Add nodejs-linear-layout-vector generated by npm2rpm using the single strategy

