%global npm_name bootstrap-sass

Name: nodejs-bootstrap-sass
Version: 3.4.3
Release: 2%{?dist}
Summary: bootstrap-sass is a Sass-powered version of Bootstrap 3, ready to drop right into your Sass powered applications
License: MIT
URL: https://github.com/twbs/bootstrap-sass#readme
Source0: https://registry.npmjs.org/bootstrap-sass/-/bootstrap-sass-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr assets %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr eyeglass-exports.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 3.4.3-2
- Update to 3.4.3

* Mon Jun 16 2025 MariaAga <mariaaga@redhat.com> 3.4.3-1
- Add nodejs-bootstrap-sass generated by npm2rpm using the single strategy

