%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name @fortawesome/fontawesome-common-types

Name: %{?scl_prefix}nodejs-fortawesome-fontawesome-common-types
Version: 0.2.28
Release: 1%{?dist}
Summary: The iconic font, CSS, and SVG framework
License: MIT
Group: Development/Libraries
URL: https://fontawesome.com
Source0: https://registry.npmjs.org/@fortawesome/fontawesome-common-types/-/fontawesome-common-types-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.txt
%doc README.md

%changelog
* Thu May 07 2020 Evgeni Golov 0.2.28-1
- Add nodejs-fortawesome-fontawesome-common-types generated by npm2rpm using the single strategy

