%global npm_name @patternfly/react-icons

Name: nodejs-patternfly-react-icons
Version: 5.4.2
Release: 2%{?dist}
Summary: PatternFly 4 Icons as React Components
License: MIT
URL: https://github.com/patternfly/patternfly-react#readme
Source0: https://registry.npmjs.org/@patternfly/react-icons/-/react-icons-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr scripts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr single-packages.config.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 5.4.2-2
- Update to 5.4.2

* Wed Jul 23 2025 Foreman Packaging Automation <packaging@theforeman.org> 5.4.2-1
- Update to 5.4.2

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 5.2.0-1
- Add nodejs-patternfly-react-icons generated by npm2rpm using the single strategy

