%global npm_name datatables.net

Name: nodejs-datatables.net
Version: 1.13.5
Release: 2%{?dist}
Summary: jQuery DataTables
License: MIT
URL: https://datatables.net
Source0: https://registry.npmjs.org/datatables.net/-/datatables.net-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
Requires: npm(jquery) >= 1.7.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr types %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license License.txt
%doc Readme.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 1.13.5-2
- Update to 1.13.5

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 1.13.5-1
- Add nodejs-datatables.net generated by npm2rpm using the single strategy

