%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name @babel/runtime

Name: %{?scl_prefix}nodejs-babel-runtime
Version: 7.28.4
Release: 1%{?dist}
Summary: babel's modular runtime helpers
License: MIT
Group: Development/Libraries
URL: https://babel.dev/docs/en/next/babel-runtime
Source0: https://registry.npmjs.org/@babel/runtime/-/runtime-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr helpers %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr regenerator %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Tue Sep 16 2025 Foreman Packaging Automation <packaging@theforeman.org> 7.28.4-1
- Update to 7.28.4

* Tue Sep 02 2025 Evgeni Golov 7.28.3-1
- Add nodejs-babel-runtime generated by npm2rpm using the single strategy

