%global npm_name @babel/runtime

Name: nodejs-babel-runtime
Version: 7.29.7
Release: 1%{?dist}
Summary: babel's modular runtime helpers
License: MIT
URL: https://babel.dev/docs/en/next/babel-runtime
Source0: https://registry.npmjs.org/@babel/runtime/-/runtime-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr helpers %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr regenerator %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Sun Jun 07 2026 Foreman Packaging Automation <packaging@theforeman.org> 7.29.7-1
- Update to 7.29.7

* Wed Mar 18 2026 Foreman Packaging Automation <packaging@theforeman.org> 7.29.2-1
- Update to 7.29.2

* Sun Jan 18 2026 Foreman Packaging Automation <packaging@theforeman.org> 7.28.6-1
- Update to 7.28.6

* Tue Sep 16 2025 Foreman Packaging Automation <packaging@theforeman.org> 7.28.4-1
- Update to 7.28.4

* Tue Sep 02 2025 Evgeni Golov 7.28.3-1
- Add nodejs-babel-runtime generated by npm2rpm using the single strategy

