%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name babel-runtime

Name: %{?scl_prefix}nodejs-babel-runtime
Version: 6.26.0
Release: 3%{?dist}
Summary: babel selfContained runtime
License: MIT
Group: Development/Libraries
URL: https://github.com/babel/babel/tree/master/packages/babel-runtime
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
%if 0%{?scl:1}
BuildRequires: %{?scl_prefix_nodejs}npm
%else
BuildRequires: nodejs-packaging
%endif
Requires: %{?scl_prefix}npm(core-js) >= 2.4.0
Requires: %{?scl_prefix}npm(core-js) < 3.0.0
Requires: %{?scl_prefix}npm(regenerator-runtime) >= 0.11.0
Requires: %{?scl_prefix}npm(regenerator-runtime) < 0.12.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr core-js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr core-js.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr helpers %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr regenerator %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%doc README.md

%changelog
* Thu Oct 10 2019 Eric D. Helms <ericdhelms@gmail.com> - 6.26.0-3
- Update requires for SCL prefix

* Fri Oct 04 2019 Eric D. Helms <ericdhelms@gmail.com> - 6.26.0-2
- Update specs to handle SCL

* Thu Apr 26 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 6.26.0-1
- Add nodejs-babel-runtime generated by npm2rpm using the single strategy
