%global npm_name @patternfly/react-table

Name: nodejs-patternfly-react-table
Version: 5.4.16
Release: 2%{?dist}
Summary: This library provides a set of React table components for use with the PatternFly 4
License: MIT
URL: https://github.com/patternfly/patternfly-react/tree/main/packages/react-table#readme
Source0: https://registry.npmjs.org/@patternfly/react-table/-/react-table-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
Requires: npm(@patternfly/react-core) >= 5.4.14
Requires: npm(@patternfly/react-core) < 6.0.0
Requires: npm(@patternfly/react-icons) >= 5.4.2
Requires: npm(@patternfly/react-icons) < 6.0.0
Requires: npm(@patternfly/react-styles) >= 5.4.1
Requires: npm(@patternfly/react-styles) < 6.0.0
Requires: npm(@patternfly/react-tokens) >= 5.4.1
Requires: npm(@patternfly/react-tokens) < 6.0.0
Requires: npm(lodash) >= 4.17.21
Requires: npm(lodash) < 5.0.0
Requires: npm(tslib) >= 2.7.0
Requires: npm(tslib) < 3.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr components %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr deprecated %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr rollup.config.mjs %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr single-packages.config.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr subpaths.config.json %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> - 5.4.16-2
- Regenerate with correct npm2rpm strategy

* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 5.4.16-1
- Update to 5.4.16

* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 5.4.16-2
- Update to 5.4.16

* Sun Aug 31 2025 Foreman Packaging Automation <packaging@theforeman.org> 5.4.16-1
- Update to 5.4.16

* Sun Jun 29 2025 root <root> 5.2.0-1
- Add nodejs-patternfly-react-table generated by npm2rpm using the single strategy

