%global npm_name react-diff-view

Name: nodejs-react-diff-view
Version: 2.6.0
Release: 2%{?dist}
Summary: A git diff component to consume the git unified diff output
License: MIT
Group: Development/Libraries
URL: https://github.com/otakustay/react-diff-view#readme
Source0: https://registry.npmjs.org/classnames/-/classnames-2.5.1.tgz
Source1: https://registry.npmjs.org/diff-match-patch/-/diff-match-patch-1.0.5.tgz
Source2: https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz
Source3: https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz
Source4: https://registry.npmjs.org/react-diff-view/-/react-diff-view-2.6.0.tgz
Source5: https://registry.npmjs.org/shallow-equal/-/shallow-equal-3.1.0.tgz
Source6: https://registry.npmjs.org/warning/-/warning-4.0.3.tgz
Source7: nodejs-react-diff-view-%{version}-package-lock.json
BuildRequires: npm >= 7
BuildRequires: nodejs-packaging
# The prep section runs node directly, so this is needed unconditionally. It
# also works around https://issues.redhat.com/browse/RHEL-137712 on RHEL 10
# before 10.3, where the nodejs major version macro does not resolve without
# node in the buildroot.
BuildRequires: /usr/bin/node
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

Provides: npm(%{npm_name}) = %{version}
Provides: bundled(npm(classnames)) = 2.5.1
Provides: bundled(npm(diff-match-patch)) = 1.0.5
Provides: bundled(npm(js-tokens)) = 4.0.0
Provides: bundled(npm(loose-envify)) = 1.4.0
Provides: bundled(npm(react-diff-view)) = 2.6.0
Provides: bundled(npm(shallow-equal)) = 3.1.0
Provides: bundled(npm(warning)) = 4.0.3
AutoReq: no
AutoProv: no

%define npm_cache_dir npm_cache_%{name}-%{version}-%{release}

%description
%{summary}

%prep
mkdir -p %{npm_cache_dir}
# npm ci installs the tree recorded in the lockfile: every entry carries a
# resolved URL and an integrity hash, and npm serves the tarballs from the
# cache primed here by content hash. No registry access is needed.
for src in %{sources}; do
  case "$src" in
    *.tgz) npm cache add --cache %{npm_cache_dir} "$src" ;;
    *-package-lock.json) cp "$src" package-lock.json ;;
  esac
done

# Derive package.json from the lockfile so the two cannot disagree.
node -e '
const fs = require("fs");
const lock = JSON.parse(fs.readFileSync("package-lock.json"));
fs.writeFileSync("package.json", JSON.stringify({
  name: lock.name,
  version: lock.version,
  dependencies: lock.packages[""].dependencies
}, null, 2) + "\n");
'

%build
npm ci --legacy-peer-deps --offline --cache %{_builddir}/%{npm_cache_dir} --omit optional

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
# npm creates a scope directory for every scope named in the lockfile, including
# scopes whose packages were all omitted, which leaves empty dirs behind.
# -delete implies -depth, so nested empties go bottom-up in a single pass.
find %{buildroot}%{nodejs_sitelib}/%{npm_name} -type d -empty -delete
cp -pfr node_modules/%{npm_name}/cjs %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/es %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/style %{buildroot}%{nodejs_sitelib}/%{npm_name}

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%files
%{nodejs_sitelib}/%{npm_name}
%license node_modules/%{npm_name}/LICENSE
%doc node_modules/%{npm_name}/README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 2.6.0-2
- Update to 2.6.0

* Fri Jun 13 2025 MariaAga <mariaaga@redhat.com> 2.6.0-1
- Add nodejs-react-diff-view generated by npm2rpm using the bundle strategy

