%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name react-diff-view

Name: %{?scl_prefix}nodejs-react-diff-view
Version: 2.6.0
Release: 1%{?dist}
Summary: A git diff component to consume the git unified diff output
License: MIT
Group: Development/Libraries
URL: https://github.com/otakustay/react-diff-view#readme
Source0: https://registry.npmjs.org/classnames/-/classnames-2.5.1.tgz
Source1: https://registry.npmjs.org/diff-match-patch/-/diff-match-patch-1.0.5.tgz
Source2: https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz
Source3: https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz
Source4: https://registry.npmjs.org/react-diff-view/-/react-diff-view-2.6.0.tgz
Source5: https://registry.npmjs.org/shallow-equal/-/shallow-equal-3.1.0.tgz
Source6: https://registry.npmjs.org/warning/-/warning-4.0.3.tgz
Source7: nodejs-react-diff-view-%{version}-registry.npmjs.org.tgz
BuildRequires: %{?scl_prefix_nodejs}npm
%if 0%{!?scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}
Provides: bundled(npm(classnames)) = 2.5.1
Provides: bundled(npm(diff-match-patch)) = 1.0.5
Provides: bundled(npm(js-tokens)) = 4.0.0
Provides: bundled(npm(loose-envify)) = 1.4.0
Provides: bundled(npm(react-diff-view)) = 2.6.0
Provides: bundled(npm(shallow-equal)) = 3.1.0
Provides: bundled(npm(warning)) = 4.0.3
AutoReq: no
AutoProv: no

%if 0%{?scl:1}
%define npm_cache_dir npm_cache
%else
%define npm_cache_dir /tmp/npm_cache_%{name}-%{version}-%{release}
%endif

%description
%{summary}

%prep
mkdir -p %{npm_cache_dir}
%{?scl:scl enable %{?scl_nodejs} - << \end_of_scl}
for tgz in %{sources}; do
  echo $tgz | grep -q registry.npmjs.org || npm cache add --cache %{npm_cache_dir} $tgz
done
%{?scl:end_of_scl}

%setup -T -q -a 7 -D -n %{npm_cache_dir}

%build
%{?scl:scl enable %{?scl_nodejs} - << \end_of_scl}
npm install --legacy-peer-deps --cache-min Infinity --cache %{?scl:../}%{npm_cache_dir} --no-shrinkwrap --no-optional --global-style true %{npm_name}@%{version}
%{?scl:end_of_scl}

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/cjs %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/es %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/style %{buildroot}%{nodejs_sitelib}/%{npm_name}

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%files
%{nodejs_sitelib}/%{npm_name}
%license node_modules/%{npm_name}/LICENSE
%doc node_modules/%{npm_name}/README.md

%changelog
* Fri Jun 13 2025 MariaAga <mariaaga@redhat.com> 2.6.0-1
- Add nodejs-react-diff-view generated by npm2rpm using the bundle strategy

