%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name @fortawesome/free-brands-svg-icons

Name: %{?scl_prefix}nodejs-fortawesome-free-brands-svg-icons
Version: 5.13.0
Release: 1%{?dist}
Summary: The iconic font, CSS, and SVG framework
License: (CC-BY-4.0 AND MIT)
Group: Development/Libraries
URL: https://fontawesome.com
Source0: https://registry.npmjs.org/@fortawesome/free-brands-svg-icons/-/free-brands-svg-icons-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
Requires: npm(@fortawesome/fontawesome-common-types) >= 0.2.28
Requires: npm(@fortawesome/fontawesome-common-types) < 0.3.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr fa500px.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr fa500px.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAccessibleIcon.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAccessibleIcon.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAccusoft.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAccusoft.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAcquisitionsIncorporated.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAcquisitionsIncorporated.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAdn.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAdn.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAdobe.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAdobe.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAdversal.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAdversal.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAffiliatetheme.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAffiliatetheme.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAirbnb.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAirbnb.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAlgolia.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAlgolia.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAlipay.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAlipay.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAmazon.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAmazon.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAmazonPay.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAmazonPay.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAmilia.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAmilia.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAndroid.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAndroid.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAngellist.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAngellist.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAngrycreative.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAngrycreative.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAngular.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAngular.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAppStore.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAppStore.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAppStoreIos.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAppStoreIos.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faApper.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faApper.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faApple.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faApple.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faApplePay.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faApplePay.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faArtstation.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faArtstation.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAsymmetrik.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAsymmetrik.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAtlassian.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAtlassian.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAudible.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAudible.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAutoprefixer.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAutoprefixer.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAvianex.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAvianex.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAviato.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAviato.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAws.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faAws.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBandcamp.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBandcamp.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBattleNet.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBattleNet.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBehance.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBehance.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBehanceSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBehanceSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBimobject.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBimobject.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBitbucket.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBitbucket.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBitcoin.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBitcoin.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBity.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBity.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBlackTie.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBlackTie.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBlackberry.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBlackberry.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBlogger.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBlogger.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBloggerB.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBloggerB.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBluetooth.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBluetooth.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBluetoothB.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBluetoothB.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBootstrap.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBootstrap.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBtc.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBtc.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBuffer.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBuffer.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBuromobelexperte.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBuromobelexperte.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBuyNLarge.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBuyNLarge.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBuysellads.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faBuysellads.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCanadianMapleLeaf.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCanadianMapleLeaf.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcAmazonPay.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcAmazonPay.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcAmex.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcAmex.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcApplePay.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcApplePay.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcDinersClub.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcDinersClub.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcDiscover.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcDiscover.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcJcb.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcJcb.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcMastercard.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcMastercard.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcPaypal.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcPaypal.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcStripe.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcStripe.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcVisa.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCcVisa.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCentercode.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCentercode.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCentos.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCentos.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faChrome.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faChrome.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faChromecast.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faChromecast.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCloudscale.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCloudscale.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCloudsmith.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCloudsmith.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCloudversify.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCloudversify.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCodepen.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCodepen.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCodiepie.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCodiepie.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faConfluence.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faConfluence.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faConnectdevelop.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faConnectdevelop.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faContao.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faContao.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCottonBureau.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCottonBureau.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCpanel.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCpanel.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommons.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommons.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsBy.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsBy.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsNc.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsNc.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsNcEu.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsNcEu.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsNcJp.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsNcJp.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsNd.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsNd.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsPd.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsPd.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsPdAlt.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsPdAlt.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsRemix.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsRemix.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsSa.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsSa.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsSampling.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsSampling.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsSamplingPlus.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsSamplingPlus.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsShare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsShare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsZero.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCreativeCommonsZero.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCriticalRole.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCriticalRole.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCss3.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCss3.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCss3Alt.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCss3Alt.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCuttlefish.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faCuttlefish.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDAndD.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDAndD.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDAndDBeyond.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDAndDBeyond.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDailymotion.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDailymotion.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDashcube.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDashcube.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDelicious.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDelicious.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDeploydog.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDeploydog.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDeskpro.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDeskpro.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDev.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDev.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDeviantart.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDeviantart.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDhl.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDhl.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDiaspora.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDiaspora.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDigg.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDigg.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDigitalOcean.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDigitalOcean.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDiscord.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDiscord.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDiscourse.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDiscourse.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDochub.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDochub.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDocker.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDocker.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDraft2digital.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDraft2digital.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDribbble.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDribbble.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDribbbleSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDribbbleSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDropbox.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDropbox.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDrupal.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDrupal.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDyalog.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faDyalog.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEarlybirds.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEarlybirds.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEbay.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEbay.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEdge.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEdge.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faElementor.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faElementor.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEllo.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEllo.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEmber.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEmber.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEmpire.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEmpire.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEnvira.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEnvira.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faErlang.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faErlang.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEthereum.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEthereum.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEtsy.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEtsy.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEvernote.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faEvernote.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faExpeditedssl.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faExpeditedssl.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFacebook.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFacebook.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFacebookF.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFacebookF.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFacebookMessenger.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFacebookMessenger.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFacebookSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFacebookSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFantasyFlightGames.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFantasyFlightGames.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFedex.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFedex.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFedora.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFedora.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFigma.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFigma.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFirefox.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFirefox.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFirefoxBrowser.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFirefoxBrowser.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFirstOrder.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFirstOrder.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFirstOrderAlt.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFirstOrderAlt.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFirstdraft.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFirstdraft.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFlickr.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFlickr.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFlipboard.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFlipboard.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFly.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFly.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFontAwesome.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFontAwesome.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFontAwesomeAlt.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFontAwesomeAlt.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFontAwesomeFlag.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFontAwesomeFlag.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFontAwesomeLogoFull.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFontAwesomeLogoFull.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFonticons.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFonticons.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFonticonsFi.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFonticonsFi.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFortAwesome.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFortAwesome.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFortAwesomeAlt.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFortAwesomeAlt.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faForumbee.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faForumbee.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFoursquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFoursquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFreeCodeCamp.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFreeCodeCamp.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFreebsd.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFreebsd.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFulcrum.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faFulcrum.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGalacticRepublic.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGalacticRepublic.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGalacticSenate.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGalacticSenate.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGetPocket.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGetPocket.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGg.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGg.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGgCircle.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGgCircle.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGit.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGit.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGitAlt.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGitAlt.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGitSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGitSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGithub.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGithub.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGithubAlt.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGithubAlt.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGithubSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGithubSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGitkraken.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGitkraken.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGitlab.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGitlab.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGitter.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGitter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGlide.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGlide.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGlideG.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGlideG.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGofore.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGofore.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGoodreads.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGoodreads.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGoodreadsG.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGoodreadsG.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGoogle.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGoogle.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGoogleDrive.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGoogleDrive.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGooglePlay.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGooglePlay.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGooglePlus.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGooglePlus.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGooglePlusG.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGooglePlusG.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGooglePlusSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGooglePlusSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGoogleWallet.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGoogleWallet.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGratipay.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGratipay.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGrav.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGrav.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGripfire.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGripfire.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGrunt.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGrunt.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGulp.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faGulp.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHackerNews.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHackerNews.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHackerNewsSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHackerNewsSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHackerrank.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHackerrank.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHips.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHips.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHireAHelper.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHireAHelper.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHooli.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHooli.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHornbill.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHornbill.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHotjar.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHotjar.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHouzz.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHouzz.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHtml5.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHtml5.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHubspot.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faHubspot.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faIdeal.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faIdeal.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faImdb.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faImdb.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faInstagram.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faInstagram.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faInstagramSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faInstagramSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faIntercom.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faIntercom.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faInternetExplorer.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faInternetExplorer.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faInvision.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faInvision.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faIoxhost.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faIoxhost.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faItchIo.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faItchIo.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faItunes.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faItunes.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faItunesNote.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faItunesNote.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJava.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJava.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJediOrder.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJediOrder.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJenkins.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJenkins.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJira.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJira.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJoget.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJoget.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJoomla.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJoomla.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJs.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJs.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJsSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJsSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJsfiddle.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faJsfiddle.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faKaggle.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faKaggle.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faKeybase.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faKeybase.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faKeycdn.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faKeycdn.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faKickstarter.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faKickstarter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faKickstarterK.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faKickstarterK.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faKorvue.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faKorvue.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLaravel.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLaravel.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLastfm.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLastfm.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLastfmSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLastfmSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLeanpub.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLeanpub.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLess.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLess.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLine.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLine.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLinkedin.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLinkedin.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLinkedinIn.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLinkedinIn.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLinode.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLinode.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLinux.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLinux.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLyft.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faLyft.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMagento.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMagento.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMailchimp.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMailchimp.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMandalorian.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMandalorian.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMarkdown.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMarkdown.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMastodon.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMastodon.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMaxcdn.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMaxcdn.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMdb.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMdb.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMedapps.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMedapps.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMedium.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMedium.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMediumM.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMediumM.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMedrt.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMedrt.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMeetup.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMeetup.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMegaport.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMegaport.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMendeley.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMendeley.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMicroblog.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMicroblog.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMicrosoft.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMicrosoft.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMix.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMix.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMixcloud.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMixcloud.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMixer.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMixer.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMizuni.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMizuni.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faModx.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faModx.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMonero.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faMonero.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNapster.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNapster.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNeos.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNeos.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNimblr.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNimblr.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNode.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNode.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNodeJs.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNodeJs.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNpm.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNpm.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNs8.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNs8.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNutritionix.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faNutritionix.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOdnoklassniki.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOdnoklassniki.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOdnoklassnikiSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOdnoklassnikiSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOldRepublic.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOldRepublic.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOpencart.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOpencart.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOpenid.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOpenid.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOpera.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOpera.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOptinMonster.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOptinMonster.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOrcid.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOrcid.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOsi.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faOsi.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPage4.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPage4.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPagelines.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPagelines.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPalfed.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPalfed.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPatreon.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPatreon.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPaypal.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPaypal.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPennyArcade.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPennyArcade.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPeriscope.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPeriscope.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPhabricator.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPhabricator.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPhoenixFramework.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPhoenixFramework.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPhoenixSquadron.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPhoenixSquadron.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPhp.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPhp.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPiedPiper.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPiedPiper.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPiedPiperAlt.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPiedPiperAlt.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPiedPiperHat.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPiedPiperHat.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPiedPiperPp.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPiedPiperPp.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPiedPiperSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPiedPiperSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPinterest.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPinterest.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPinterestP.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPinterestP.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPinterestSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPinterestSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPlaystation.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPlaystation.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faProductHunt.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faProductHunt.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPushed.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPushed.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPython.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faPython.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faQq.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faQq.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faQuinscape.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faQuinscape.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faQuora.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faQuora.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRProject.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRProject.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRaspberryPi.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRaspberryPi.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRavelry.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRavelry.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faReact.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faReact.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faReacteurope.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faReacteurope.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRebel.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRebel.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRedRiver.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRedRiver.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faReddit.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faReddit.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRedditAlien.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRedditAlien.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRedditSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRedditSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRedhat.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRedhat.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRenren.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRenren.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faReplyd.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faReplyd.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faResearchgate.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faResearchgate.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faResolving.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faResolving.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRev.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRev.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRocketchat.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRocketchat.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRockrms.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faRockrms.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSafari.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSafari.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSalesforce.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSalesforce.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSass.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSass.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSchlix.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSchlix.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faScribd.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faScribd.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSearchengin.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSearchengin.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSellcast.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSellcast.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSellsy.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSellsy.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faServicestack.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faServicestack.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faShirtsinbulk.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faShirtsinbulk.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faShopify.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faShopify.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faShopware.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faShopware.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSimplybuilt.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSimplybuilt.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSistrix.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSistrix.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSith.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSith.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSketch.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSketch.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSkyatlas.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSkyatlas.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSkype.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSkype.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSlack.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSlack.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSlackHash.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSlackHash.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSlideshare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSlideshare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSnapchat.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSnapchat.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSnapchatGhost.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSnapchatGhost.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSnapchatSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSnapchatSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSoundcloud.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSoundcloud.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSourcetree.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSourcetree.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSpeakap.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSpeakap.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSpeakerDeck.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSpeakerDeck.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSpotify.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSpotify.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSquarespace.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSquarespace.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStackExchange.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStackExchange.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStackOverflow.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStackOverflow.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStackpath.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStackpath.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStaylinked.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStaylinked.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSteam.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSteam.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSteamSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSteamSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSteamSymbol.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSteamSymbol.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStickerMule.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStickerMule.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStrava.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStrava.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStripe.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStripe.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStripeS.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStripeS.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStudiovinari.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStudiovinari.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStumbleupon.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStumbleupon.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStumbleuponCircle.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faStumbleuponCircle.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSuperpowers.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSuperpowers.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSupple.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSupple.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSuse.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSuse.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSwift.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSwift.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSymfony.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faSymfony.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTeamspeak.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTeamspeak.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTelegram.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTelegram.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTelegramPlane.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTelegramPlane.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTencentWeibo.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTencentWeibo.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTheRedYeti.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTheRedYeti.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faThemeco.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faThemeco.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faThemeisle.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faThemeisle.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faThinkPeaks.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faThinkPeaks.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTradeFederation.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTradeFederation.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTrello.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTrello.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTripadvisor.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTripadvisor.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTumblr.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTumblr.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTumblrSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTumblrSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTwitch.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTwitch.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTwitter.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTwitter.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTwitterSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTwitterSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTypo3.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faTypo3.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUber.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUber.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUbuntu.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUbuntu.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUikit.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUikit.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUmbraco.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUmbraco.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUniregistry.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUniregistry.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUnity.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUnity.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUntappd.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUntappd.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUps.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUps.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUsb.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUsb.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUsps.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUsps.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUssunnah.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faUssunnah.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVaadin.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVaadin.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faViacoin.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faViacoin.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faViadeo.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faViadeo.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faViadeoSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faViadeoSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faViber.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faViber.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVimeo.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVimeo.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVimeoSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVimeoSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVimeoV.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVimeoV.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVine.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVine.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVk.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVk.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVnv.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVnv.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVuejs.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faVuejs.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWaze.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWaze.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWeebly.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWeebly.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWeibo.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWeibo.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWeixin.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWeixin.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWhatsapp.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWhatsapp.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWhatsappSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWhatsappSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWhmcs.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWhmcs.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWikipediaW.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWikipediaW.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWindows.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWindows.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWix.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWix.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWizardsOfTheCoast.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWizardsOfTheCoast.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWolfPackBattalion.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWolfPackBattalion.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWordpress.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWordpress.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWordpressSimple.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWordpressSimple.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWpbeginner.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWpbeginner.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWpexplorer.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWpexplorer.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWpforms.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWpforms.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWpressr.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faWpressr.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faXbox.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faXbox.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faXing.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faXing.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faXingSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faXingSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYCombinator.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYCombinator.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYahoo.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYahoo.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYammer.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYammer.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYandex.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYandex.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYandexInternational.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYandexInternational.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYarn.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYarn.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYelp.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYelp.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYoast.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYoast.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYoutube.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYoutube.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYoutubeSquare.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faYoutubeSquare.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faZhihu.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr faZhihu.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.es.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.txt
%doc README.md
%doc faReadme.d.ts
%doc faReadme.js

%changelog
* Thu May 07 2020 Evgeni Golov 5.13.0-1
- Add nodejs-fortawesome-free-brands-svg-icons generated by npm2rpm using the single strategy

