%global npm_name @novnc/novnc

Name: nodejs-novnc
Version: 1.0.0
Release: 1%{?dist}
Summary: An HTML5 VNC client
License: MPLv2.0
Group: Development/Libraries
URL: https://github.com/novnc/noVNC
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr core %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr vendor %{buildroot}%{nodejs_sitelib}/%{npm_name}

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.txt
%doc README.md
%doc docs

%changelog
* Wed Oct 03 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 1.0.0-1
- Add nodejs-novnc generated by npm2rpm using the single strategy
