%global npm_name classnames

Name: nodejs-classnames
Version: 2.5.1
Release: 2%{?dist}
Summary: A simple utility for conditionally joining classNames together
License: MIT
URL: https://github.com/JedWatson/classnames#readme
Source0: https://registry.npmjs.org/classnames/-/classnames-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr bind.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr bind.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dedupe.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dedupe.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc HISTORY.md
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 2.5.1-2
- Update to 2.5.1

* Thu Aug 28 2025 Foreman Packaging Automation <packaging@theforeman.org> 2.5.1-1
- Update to 2.5.1

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 2.2.5-1
- Add nodejs-classnames generated by npm2rpm using the single strategy

