%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name select2

Name: %{?scl_prefix}nodejs-select2
Version: 4.0.12
Release: 1%{?dist}
Summary: Select2 is a jQuery based replacement for select boxes
License: MIT
Group: Development/Libraries
URL: https://select2.org
Source0: https://registry.npmjs.org/select2/-/select2-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc CHANGELOG.md
%doc README.md

%changelog
* Mon Jun 16 2025 MariaAga <mariaaga@redhat.com> 4.0.12-1
- Add nodejs-select2 generated by npm2rpm using the single strategy

