%global npm_name select2

Name: nodejs-select2
Version: 4.0.12
Release: 2%{?dist}
Summary: Select2 is a jQuery based replacement for select boxes
License: MIT
URL: https://select2.org
Source0: https://registry.npmjs.org/select2/-/select2-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc CHANGELOG.md
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 4.0.12-2
- Update to 4.0.12

* Mon Jun 16 2025 MariaAga <mariaaga@redhat.com> 4.0.12-1
- Add nodejs-select2 generated by npm2rpm using the single strategy

