%global npm_name babel-runtime
%global enable_tests 1

Name: nodejs-%{npm_name}
Version: 6.26.0
Release: 1%{?dist}
Summary: babel selfContained runtime
License: MIT
Group: Development/Libraries
URL: https://github.com/babel/babel/tree/master/packages/babel-runtime
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
Requires: npm(core-js) >= 2.4.0
Requires: npm(core-js) < 3.0.0
Requires: npm(regenerator-runtime) >= 0.11.0
Requires: npm(regenerator-runtime) < 1.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr core-js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr core-js.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr helpers %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr regenerator %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%if 0%{?enable_tests}
%check
%{nodejs_symlink_deps} --check
%endif

%files
%{nodejs_sitelib}/%{npm_name}
%doc README.md

%changelog
* Thu Apr 26 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 6.26.0-1
- Add nodejs-babel-runtime generated by npm2rpm using the single strategy

