%global npm_name react-virtualized

Name: nodejs-react-virtualized
Version: 9.21.0
Release: 1%{?dist}
Summary: React components for efficiently rendering large, scrollable lists and tabular data
License: MIT
Group: Development/Libraries
URL: https://github.com/bvaughn/react-virtualized
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
Requires: npm(babel-runtime) >= 6.26.0
Requires: npm(babel-runtime) < 7.0.0
Requires: npm(classnames) >= 2.2.3
Requires: npm(classnames) < 3.0.0
Requires: npm(dom-helpers)
Requires: npm(loose-envify) >= 1.3.0
Requires: npm(loose-envify) < 2.0.0
Requires: npm(prop-types) >= 15.6.0
Requires: npm(prop-types) < 16.0.0
Requires: npm(react-lifecycles-compat) >= 3.0.4
Requires: npm(react-lifecycles-compat) < 4.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr source %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr styles.css %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Thu May 16 2019 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 9.21.0-1
- Add nodejs-react-virtualized generated by npm2rpm using the single strategy

