%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name ipaddr.js

Name: %{?scl_prefix}nodejs-ipaddr.js
Version: 1.2.0
Release: 1%{?dist}
Summary: A library for manipulating IPv4 and IPv6 addresses in JavaScript
License: MIT
Group: Development/Libraries
URL: https://github.com/whitequark/ipaddr.js#readme
Source0: https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Cakefile %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr ipaddr.min.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr test %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 1.2.0-1
- Add nodejs-ipaddr.js generated by npm2rpm using the single strategy

