# template: default
%global gem_name ruby2_keywords

Name: rubygem-%{gem_name}
Version: 0.0.5
Release: 1%{?dist}
Summary: Shim library for Ruby Module ruby2_keywords
License: Ruby and BSD-2-Clause
URL: https://github.com/ruby/ruby2_keywords
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: ruby >= 2.0.0
BuildRequires: ruby >= 2.0.0
BuildRequires: rubygems-devel
BuildArch: noarch
# end specfile generated dependencies

%description
Shim library for Ruby Module ruby2_keywords.


%package doc
Summary: Documentation for %{name}
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.

%prep
%setup -q -n  %{gem_name}-%{version}

%build
# Create the gem as gem install only works on a gem file
gem build ../%{gem_name}-%{version}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

%files
%dir %{gem_instdir}
%license %{gem_instdir}/LICENSE
%{gem_libdir}
%exclude %{gem_cache}
%{gem_spec}

%files doc
%doc %{gem_docdir}
%doc %{gem_instdir}/ChangeLog
%doc %{gem_instdir}/README.md
%doc %{gem_instdir}/logs

%changelog
* Sun Jul 24 2022 Foreman Packaging Automation <packaging@theforeman.org> 0.0.5-1
- Update to 0.0.5

* Wed May 05 2021 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 0.0.4-1
- Add rubygem-ruby2_keywords generated by gem2rpm using the scl template

