%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name history

Name: %{?scl_prefix}nodejs-history
Version: 4.7.2
Release: 1%{?dist}
Summary: Manage session history with JavaScript
License: MIT
Group: Development/Libraries
URL: https://github.com/ReactTraining/history#readme
Source0: https://registry.npmjs.org/history/-/history-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
Requires: npm(invariant) >= 2.2.1
Requires: npm(invariant) < 3.0.0
Requires: npm(loose-envify) >= 1.2.0
Requires: npm(loose-envify) < 2.0.0
Requires: npm(resolve-pathname) >= 2.2.0
Requires: npm(resolve-pathname) < 3.0.0
Requires: npm(value-equal) >= 0.4.0
Requires: npm(value-equal) < 0.5.0
Requires: npm(warning) >= 3.0.0
Requires: npm(warning) < 4.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr DOMUtils.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr LocationUtils.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr PathUtils.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr createBrowserHistory.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr createHashHistory.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr createMemoryHistory.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr createTransitionManager.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr es %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr umd %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc CHANGES.md
%doc README.md

%changelog
* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 4.7.2-1
- Add nodejs-history generated by npm2rpm using the single strategy

