# template: default
%global gem_name openfact

Name: rubygem-%{gem_name}
Version: 6.2.0
Release: 1%{?dist}
Summary: OpenFact, a system inventory tool
License: Apache-2.0
URL: https://github.com/OpenVoxProject/openfact/
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: ruby >= 3.0
BuildRequires: ruby >= 3.0
BuildRequires: rubygems-devel
BuildArch: noarch
# end specfile generated dependencies

Obsoletes: rubygem-facter < 6.2.0-1

%description
You can prove anything with facts!


%package doc
Summary: Documentation for %{name}
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.

%prep
%setup -q -n  %{gem_name}-%{version}

%build
# Create the gem as gem install only works on a gem file
gem build ../%{gem_name}-%{version}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

mkdir -p %{buildroot}%{_bindir}
cp -a .%{_bindir}/* \
        %{buildroot}%{_bindir}/

find %{buildroot}%{gem_instdir}/bin -type f | xargs chmod a+x

%files
%dir %{gem_instdir}
%{_bindir}/facter
%license %{gem_instdir}/LICENSE
%{gem_instdir}/bin
%{gem_libdir}
%exclude %{gem_cache}
%{gem_spec}

%files doc
%doc %{gem_docdir}

%changelog
* Wed Sep 23 2026 Jakub Duchek <jakduch@seznam.cz> 6.2.0-1
- Add rubygem-openfact generated by gem2rpm using the default template
