# template: default
%global gem_name anonymous_loader

Name: rubygem-%{gem_name}
Version: 0.1.1
Release: 1%{?dist}
Summary: Load Ruby source files inside anonymous namespaces
License: MIT
URL: https://github.com/ruby-oauth/anonymous_loader
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: ruby >= 2.2.0
Requires: (rubygem(version_gem) >= 1.1 with rubygem(version_gem) < 2)
BuildRequires: ruby >= 2.2.0
BuildRequires: rubygems-devel
BuildArch: noarch
# end specfile generated dependencies

%description
AnonymousLoader resolves Ruby files from paths, gem metadata, or $LOAD_PATH
and evaluates them inside anonymous modules to avoid top-level namespace
collisions.


%package doc
Summary: Documentation for %{name}
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.

%prep
%setup -q -n  %{gem_name}-%{version}

%build
# Create the gem as gem install only works on a gem file
gem build ../%{gem_name}-%{version}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

%files
%dir %{gem_instdir}
%{gem_instdir}/CITATION.cff
%license %{gem_instdir}/LICENSE.md
%{gem_instdir}/certs
%{gem_libdir}
%{gem_instdir}/sig
%exclude %{gem_cache}
%{gem_spec}

%files doc
%doc %{gem_docdir}
%doc %{gem_instdir}/CHANGELOG.md
%doc %{gem_instdir}/CODE_OF_CONDUCT.md
%doc %{gem_instdir}/CONTRIBUTING.md
%doc %{gem_instdir}/FUNDING.md
%doc %{gem_instdir}/README.md
%doc %{gem_instdir}/RUBOCOP.md
%doc %{gem_instdir}/SECURITY.md

%changelog
* Tue Jun 23 2026 Ondřej Gajdušek <ogajduse@redhat.com> 0.1.1-1
- Add rubygem-anonymous_loader generated by gem2rpm using the default template

