# template: default
%global gem_name prometheus-client

Name: rubygem-%{gem_name}
Version: 4.2.5
Release: 1%{?dist}
Summary: A suite of instrumentation metric primitivesthat can be exposed through a web services interface
License: Apache-2.0
URL: https://github.com/prometheus/client_ruby
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

Requires: (rubygem(base64) or ruby-default-gems < 3.4)

# start specfile generated dependencies
Requires: ruby
BuildRequires: ruby
BuildRequires: rubygems-devel
BuildArch: noarch
# end specfile generated dependencies

%description
A suite of instrumentation metric primitivesthat can be exposed through a web
services interface.


%package doc
Summary: Documentation for %{name}
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.

%prep
%setup -q -n  %{gem_name}-%{version}

%gemspec_remove_dep -g base64

%build
# Create the gem as gem install only works on a gem file
gem build ../%{gem_name}-%{version}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

%files
%dir %{gem_instdir}
%license %{gem_instdir}/LICENSE
%{gem_libdir}
%exclude %{gem_cache}
%{gem_spec}

%files doc
%doc %{gem_docdir}
%doc %{gem_instdir}/README.md

%changelog
* Sun Jul 06 2025 Foreman Packaging Automation <packaging@theforeman.org> - 4.2.5-1
- Update to 4.2.5

* Wed Feb 05 2025 Foreman Packaging Automation <packaging@theforeman.org> - 4.2.4-1
- Update to 4.2.4

* Tue Aug 13 2024 Foreman Packaging Automation <packaging@theforeman.org> - 4.2.3-1
- Update to 4.2.3

* Sun Nov 05 2023 Foreman Packaging Automation <packaging@theforeman.org> 4.2.2-1
- Update to 4.2.2

* Fri Aug 11 2023 Foreman Packaging Automation <packaging@theforeman.org> 4.2.1-1
- Update to 4.2.1

* Sun Aug 06 2023 Foreman Packaging Automation <packaging@theforeman.org> 4.2.0-1
- Update to 4.2.0

* Mon Apr 03 2023 Evgeni Golov 4.1.0-1
- Update to 4.1.0

* Thu Mar 11 2021 Eric D. Helms <ericdhelms@gmail.com> - 1.0.0-3
- Rebuild against rh-ruby27

* Wed Apr 08 2020 Zach Huntington-Meath <zhunting@redhat.com> - 1.0.0-2
- Bump to release for EL8

* Wed Dec 04 2019 Lukas Zapletal <lzap@redhat.com> 1.0.0-1
- Update to 1.0.0

* Wed Sep 12 2018 Bryan Kearney <bryan.kearney@gmail.com> - 0.7.1-3
- Use ASL 2.0 instead of Apache 2.0 or Apache-2.0

* Wed Sep 05 2018 Eric D. Helms <ericdhelms@gmail.com> - 0.7.1-2
- Rebuild for Rails 5.2 and Ruby 2.5

* Thu Apr 05 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 0.7.1-1
- Add rubygem-prometheus-client generated by gem2rpm using the scl template

