%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name react-motion

Name: %{?scl_prefix}nodejs-react-motion
Version: 0.5.2
Release: 2%{?dist}
Summary: A spring that solves your animation problems
License: MIT
Group: Development/Libraries
URL: https://github.com/chenglou/react-motion#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
%if 0%{?scl:1}
BuildRequires: %{?scl_prefix_nodejs}npm
%else
BuildRequires: nodejs-packaging
%endif
Requires: %{?scl_prefix}npm(performance-now) >= 2.1.0
Requires: %{?scl_prefix}npm(performance-now) < 3.0.0
Requires: %{?scl_prefix}npm(prop-types) >= 15.5.8
Requires: %{?scl_prefix}npm(prop-types) < 16.0.0
Requires: %{?scl_prefix}npm(raf) >= 3.1.0
Requires: %{?scl_prefix}npm(raf) < 4.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package
# commit 4222c5c61ad4d4e0d8abc71c49bfc4fe1d1efb74
%nodejs_fixdep performance-now '^2.1.0'

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr build %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc AUTHORS
%doc HISTORY.md
%doc README.md

%changelog
* Fri Oct 04 2019 Eric D. Helms <ericdhelms@gmail.com> - 0.5.2-2
- Update specs to handle SCL

* Wed Oct 10 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 0.5.2-1
- Add nodejs-react-motion generated by npm2rpm using the single strategy
