%global npm_name react-motion

Name: nodejs-react-motion
Version: 0.5.2
Release: 1%{?dist}
Summary: A spring that solves your animation problems
License: MIT
Group: Development/Libraries
URL: https://github.com/chenglou/react-motion#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
Requires: npm(performance-now) >= 2.1.0
Requires: npm(performance-now) < 3.0.0
Requires: npm(prop-types) >= 15.5.8
Requires: npm(prop-types) < 16.0.0
Requires: npm(raf) >= 3.1.0
Requires: npm(raf) < 4.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package
# commit 4222c5c61ad4d4e0d8abc71c49bfc4fe1d1efb74
%nodejs_fixdep performance-now '^2.1.0'

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr build %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc AUTHORS
%doc HISTORY.md
%doc README.md

%changelog
* Wed Oct 10 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 0.5.2-1
- Add nodejs-react-motion generated by npm2rpm using the single strategy

