%global npm_name dsmorse-gridster

Name: nodejs-dsmorse-gridster
Version: 0.8.0
Release: 2%{?dist}
Summary: a drag-and-drop multi-column jQuery grid plugin
License: MIT
URL: https://dsmorse.github.io/gridster.js/
Source0: https://registry.npmjs.org/dsmorse-gridster/-/dsmorse-gridster-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 0.8.0-2
- Regenerate spec file

* Fri Jun 13 2025 MariaAga <mariaaga@redhat.com> 0.8.0-1
- Add nodejs-dsmorse-gridster generated by npm2rpm using the single strategy

