%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name dsmorse-gridster

Name: %{?scl_prefix}nodejs-dsmorse-gridster
Version: 0.8.0
Release: 1%{?dist}
Summary: a drag-and-drop multi-column jQuery grid plugin
License: MIT
Group: Development/Libraries
URL: https://dsmorse.github.io/gridster.js/
Source0: https://registry.npmjs.org/dsmorse-gridster/-/dsmorse-gridster-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Fri Jun 13 2025 MariaAga <mariaaga@redhat.com> 0.8.0-1
- Add nodejs-dsmorse-gridster generated by npm2rpm using the single strategy

