# template: default
%global gem_name aws-eventstream

Name: rubygem-%{gem_name}
Version: 1.4.0
Release: 1%{?dist}
Summary: AWS Event Stream Library
License: Apache-2.0
URL: https://github.com/aws/aws-sdk-ruby
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: ruby >= 2.7
BuildRequires: ruby >= 2.7
BuildRequires: rubygems-devel
BuildArch: noarch
# end specfile generated dependencies

%description
Amazon Web Services event stream library. Decodes and encodes binary stream
under `vnd.amazon.event-stream` content-type.


%package doc
Summary: Documentation for %{name}
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.

%prep
%setup -q -n  %{gem_name}-%{version}

%build
# Create the gem as gem install only works on a gem file
gem build ../%{gem_name}-%{version}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

%files
%dir %{gem_instdir}
%license %{gem_instdir}/LICENSE.txt
%{gem_instdir}/VERSION
%{gem_libdir}
%exclude %{gem_cache}
%{gem_spec}

%files doc
%doc %{gem_docdir}
%doc %{gem_instdir}/CHANGELOG.md

%changelog
* Sat Oct 03 2026 Jakub Duchek <jakduch@seznam.cz> 1.4.0-1
- Update to 1.4.0-1

* Tue Jul 28 2026 Zach Huntington-Meath <zhunting@redhat.com> - 1.0.2-3
- Rebuild for EL10

* Tue Apr 06 2021 Eric D. Helms <ericdhelms@gmail.com> - 1.0.2-2
- Rebuild for Ruby 2.7

* Tue Mar 19 2019 Timo Goebel <mail@timogoebel.name> 1.0.2-1
- Add rubygem-aws-eventstream generated by gem2rpm using the scl template
