%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name react-dom

Name: %{?scl_prefix}nodejs-react-dom
Version: 16.8.1
Release: 1%{?dist}
Summary: React package for working with the DOM
License: MIT
Group: Development/Libraries
URL: https://reactjs.org/
Source0: https://registry.npmjs.org/react-dom/-/react-dom-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
Requires: npm(loose-envify) >= 1.1.0
Requires: npm(loose-envify) < 2.0.0
Requires: npm(object-assign) >= 4.1.1
Requires: npm(object-assign) < 5.0.0
Requires: npm(prop-types) >= 15.6.2
Requires: npm(prop-types) < 16.0.0
Requires: npm(scheduler) >= 0.13.1
Requires: npm(scheduler) < 0.14.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr build-info.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr cjs %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr profiling.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr server.browser.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr server.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr server.node.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr test-utils.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr umd %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr unstable-fizz.browser.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr unstable-fizz.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr unstable-fizz.node.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr unstable-native-dependencies.js %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 16.8.1-1
- Add nodejs-react-dom generated by npm2rpm using the single strategy

