# template: default
%global gem_name faraday-cookie_jar

Name: rubygem-%{gem_name}
Version: 0.0.7
Release: 1%{?dist}
Summary: Manages client-side cookie jar for Faraday HTTP client
License: MIT
URL: https://github.com/miyagawa/faraday-cookie_jar
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: ruby
BuildRequires: ruby
BuildRequires: rubygems-devel
BuildArch: noarch
# end specfile generated dependencies

%description
Cookie jar middleware for Faraday.


%package doc
Summary: Documentation for %{name}
Requires: %{name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{name}.

%prep
%setup -q -n  %{gem_name}-%{version}

# Allow http-cookie 1.1.x
%gemspec_remove_dep -g http-cookie "~> 1.0.0"
%gemspec_add_dep -g http-cookie [">= 1.0.0", "< 1.2"]

%build
# Create the gem as gem install only works on a gem file
gem build ../%{gem_name}-%{version}.gemspec

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%gem_install

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

%files
%dir %{gem_instdir}
%exclude %{gem_instdir}/.gitignore
%license %{gem_instdir}/LICENSE.txt
%{gem_libdir}
%exclude %{gem_cache}
%{gem_spec}

%files doc
%doc %{gem_docdir}
%doc %{gem_instdir}/CHANGELOG.md
%{gem_instdir}/Gemfile
%doc %{gem_instdir}/README.md
%{gem_instdir}/Rakefile
%exclude %{gem_instdir}/faraday-cookie_jar.gemspec
%{gem_instdir}/spec

%changelog
* Tue Oct 07 2025 Evgeni Golov - 0.0.7-1
- Update to 0.0.7

* Tue Apr 06 2021 Eric D. Helms <ericdhelms@gmail.com> - 0.0.6-2
- Rebuild for Ruby 2.7

* Mon Oct 07 2019 Aditi Puntambekar <apuntamb@redhat.com> 0.0.6-1
- Add rubygem-faraday-cookie_jar generated by gem2rpm using the scl template

