%global npm_name react-bootstrap-tooltip-button
%global enable_tests 1

Name: nodejs-%{npm_name}
Version: 1.0.6
Release: 2%{?dist}
Summary: React-Bootstrap button with Tooltip when disabled
License: MIT
Group: Development/Libraries
URL: https://github.com/pastaclub/react-bootstrap-tooltip-button#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
Requires: npm(react) >= 15.4.2
Requires: npm(react) < 17.0.0
Requires: npm(react-bootstrap) >= 0.30.8
Requires: npm(react-bootstrap) < 0.33.0
Requires: npm(react-dom) >= 15.4.2
Requires: npm(react-dom) < 17.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package
%nodejs_fixdep react '>= 15.4.2 < 17.0.0'
%nodejs_fixdep react-bootstrap '>= 0.30.8 < 0.33.0'
%nodejs_fixdep react-dom '>= 15.4.2 < 17.0.0'

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%if 0%{?enable_tests}
%check
%{nodejs_symlink_deps} --check
%endif

%files
%{nodejs_sitelib}/%{npm_name}
%doc README.md

%changelog
* Wed May 16 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> - 1.0.6-2
- Loosen dependencies

* Tue May 15 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 1.0.6-1
- Add nodejs-react-bootstrap-tooltip-button generated by npm2rpm using the single strategy

