%global npm_name react-lifecycles-compat

Name: nodejs-react-lifecycles-compat
Version: 3.0.4
Release: 1%{?dist}
Summary: Backwards compatibility polyfill for React class components
License: MIT
Group: Development/Libraries
URL: https://github.com/reactjs/react-lifecycles-compat#readme
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr react-lifecycles-compat.cjs.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr react-lifecycles-compat.es.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr react-lifecycles-compat.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr react-lifecycles-compat.min.js %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc CHANGELOG.md
%doc README.md

%changelog
* Wed Oct 10 2018 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 3.0.4-1
- Add nodejs-react-lifecycles-compat generated by npm2rpm using the single strategy

