%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name jstz

Name: %{?scl_prefix}nodejs-jstz
Version: 1.0.11
Release: 1%{?dist}
Summary: Timezone detection for JavaScript
License: MIT
Group: Development/Libraries
URL: https://github.com/iansinnott/jstz#readme
Source0: https://registry.npmjs.org/jstz/-/jstz-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr LICENCE %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr jstz.main.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr jstz.rules.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr test.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr utilities %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%doc README.md

%changelog
* Wed Jul 23 2025 Foreman Packaging Automation <packaging@theforeman.org> 1.0.11-1
- Update to 1.0.11

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 1.0.7-1
- Add nodejs-jstz generated by npm2rpm using the single strategy

