%global npm_name jstz

Name: nodejs-jstz
Version: 1.0.11
Release: 2%{?dist}
Summary: Timezone detection for JavaScript
License: MIT
URL: https://github.com/iansinnott/jstz#readme
Source0: https://registry.npmjs.org/jstz/-/jstz-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr LICENCE %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr jstz.main.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr jstz.rules.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr test.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr utilities %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 1.0.11-2
- Update to 1.0.11

* Wed Jul 23 2025 Foreman Packaging Automation <packaging@theforeman.org> 1.0.11-1
- Update to 1.0.11

* Thu Jun 19 2025 MariaAga <mariaaga@redhat.com> 1.0.7-1
- Add nodejs-jstz generated by npm2rpm using the single strategy

