%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name graphql-tag

Name: %{?scl_prefix}nodejs-graphql-tag
Version: 2.12.6
Release: 1%{?dist}
Summary: A JavaScript template literal tag that parses GraphQL queries
License: MIT
Group: Development/Libraries
URL: https://github.com/apollographql/graphql-tag#readme
Source0: https://registry.npmjs.org/graphql-tag/-/graphql-tag-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
Requires: npm(tslib) >= 2.1.0
Requires: npm(tslib) < 3.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr loader.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr main.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Sun Sep 10 2023 Foreman Packaging Automation <packaging@theforeman.org> 2.12.6-1
- Update to 2.12.6

* Fri May 21 2021 Ondrej Prazak <oprazak@redhat.com> 2.11.0-1
- Add nodejs-graphql-tag generated by npm2rpm using the single strategy

