%global npm_name graphql-tag

Name: nodejs-graphql-tag
Version: 2.12.7
Release: 2%{?dist}
Summary: A JavaScript template literal tag that parses GraphQL queries
License: MIT
URL: https://github.com/apollographql/graphql-tag#readme
Source0: https://registry.npmjs.org/graphql-tag/-/graphql-tag-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
Requires: npm(tslib) >= 2.1.0
Requires: npm(tslib) < 3.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr loader.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr main.js %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 2.12.7-2
- Update to 2.12.7

* Sun Jun 21 2026 Foreman Packaging Automation <packaging@theforeman.org> 2.12.7-1
- Update to 2.12.7

* Sun Sep 10 2023 Foreman Packaging Automation <packaging@theforeman.org> 2.12.6-1
- Update to 2.12.6

* Fri May 21 2021 Ondrej Prazak <oprazak@redhat.com> 2.11.0-1
- Add nodejs-graphql-tag generated by npm2rpm using the single strategy

