%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name tabbable

Name: %{?scl_prefix}nodejs-tabbable
Version: 6.2.0
Release: 1%{?dist}
Summary: Returns an array of all tabbable DOM nodes within a containing node
License: MIT
Group: Development/Libraries
URL: https://github.com/focus-trap/tabbable#readme
Source0: https://registry.npmjs.org/tabbable/-/tabbable-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md
%doc SECURITY.md

%changelog
* Thu Nov 13 2025 MariaAga <mariaaga@redhat.com> 6.2.0-1
- Add nodejs-tabbable generated by npm2rpm using the single strategy

