%global npm_name @spice-project/spice-html5

Name: nodejs-spice-html5
Version: 0.2.1
Release: 1%{?dist}
Summary: Spice Javascript client
License: LGPL-3.0-or-later
Group: Development/Libraries
URL: https://www.spice-space.org
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr Makefile %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr TODO %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr apache.conf.sample %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json.in %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr spice-html5.spec.in %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr spice.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr spice.html %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr spice_auto.html %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license COPYING
%license COPYING.LESSER
%doc README

%changelog
* Mon Apr 29 2019 Ohad Levy <ohadlevy@gmail.com> 0.2.1-1
- Add nodejs-spice-html5 generated by npm2rpm using the single strategy

