%global npm_name use-deep-compare-effect

Name: nodejs-use-deep-compare-effect
Version: 1.6.1
Release: 3%{?dist}
Summary: It's react's useEffect hook, except using deep comparison on the inputs, not reference equality
License: MIT
Group: Development/Libraries
URL: https://github.com/kentcdodds/use-deep-compare-effect#readme
Source0: https://registry.npmjs.org/@babel/runtime/-/runtime-7.29.7.tgz
Source1: https://registry.npmjs.org/@types/prop-types/-/prop-types-15.7.15.tgz
Source2: https://registry.npmjs.org/@types/react/-/react-17.0.93.tgz
Source3: https://registry.npmjs.org/@types/scheduler/-/scheduler-0.16.8.tgz
Source4: https://registry.npmjs.org/csstype/-/csstype-3.2.3.tgz
Source5: https://registry.npmjs.org/dequal/-/dequal-2.0.3.tgz
Source6: https://registry.npmjs.org/use-deep-compare-effect/-/use-deep-compare-effect-1.6.1.tgz
Source7: nodejs-use-deep-compare-effect-%{version}-package-lock.json
BuildRequires: npm >= 7
BuildRequires: nodejs-packaging
# The prep section runs node directly, so this is needed unconditionally. It
# also works around https://issues.redhat.com/browse/RHEL-137712 on RHEL 10
# before 10.3, where the nodejs major version macro does not resolve without
# node in the buildroot.
BuildRequires: /usr/bin/node
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

Provides: npm(%{npm_name}) = %{version}
Provides: bundled(npm(@babel/runtime)) = 7.29.7
Provides: bundled(npm(@types/prop-types)) = 15.7.15
Provides: bundled(npm(@types/react)) = 17.0.93
Provides: bundled(npm(@types/scheduler)) = 0.16.8
Provides: bundled(npm(csstype)) = 3.2.3
Provides: bundled(npm(dequal)) = 2.0.3
Provides: bundled(npm(use-deep-compare-effect)) = 1.6.1
AutoReq: no
AutoProv: no

%define npm_cache_dir npm_cache_%{name}-%{version}-%{release}

%description
%{summary}

%prep
mkdir -p %{npm_cache_dir}
# npm ci installs the tree recorded in the lockfile: every entry carries a
# resolved URL and an integrity hash, and npm serves the tarballs from the
# cache primed here by content hash. No registry access is needed.
for src in %{sources}; do
  case "$src" in
    *.tgz) npm cache add --cache %{npm_cache_dir} "$src" ;;
    *-package-lock.json) cp "$src" package-lock.json ;;
  esac
done

# Derive package.json from the lockfile so the two cannot disagree.
node -e '
const fs = require("fs");
const lock = JSON.parse(fs.readFileSync("package-lock.json"));
fs.writeFileSync("package.json", JSON.stringify({
  name: lock.name,
  version: lock.version,
  dependencies: lock.packages[""].dependencies
}, null, 2) + "\n");
'

%build
npm ci --legacy-peer-deps --offline --cache %{_builddir}/%{npm_cache_dir} --omit optional

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
# npm creates a scope directory for every scope named in the lockfile, including
# scopes whose packages were all omitted, which leaves empty dirs behind.
# -delete implies -depth, so nested empties go bottom-up in a single pass.
find %{buildroot}%{nodejs_sitelib}/%{npm_name} -type d -empty -delete
cp -pfr node_modules/%{npm_name}/dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr node_modules/%{npm_name}/package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%clean
rm -rf %{buildroot} %{npm_cache_dir}

%files
%{nodejs_sitelib}/%{npm_name}
%license node_modules/%{npm_name}/LICENSE
%doc node_modules/%{npm_name}/CHANGELOG.md
%doc node_modules/%{npm_name}/README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> - 1.6.1-3
- Regenerate with correct npm2rpm strategy

* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 1.6.1-1
- Update to 1.6.1

* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 1.6.1-3
- Update to 1.6.1

* Thu Feb 01 2024 Eric D. Helms <ericdhelms@gmail.com> - 1.6.1-2
- Use --legacy-peer-deps during npm install

* Mon Jul 05 2021 Evgeni Golov 1.6.1-1
- Add nodejs-use-deep-compare-effect generated by npm2rpm using the bundle strategy

