%global npm_name use-deep-compare-effect

Name: nodejs-use-deep-compare-effect
Version: 1.6.1
Release: 3%{?dist}
Summary: It's react's useEffect hook, except using deep comparison on the inputs, not reference equality
License: MIT
URL: https://github.com/kentcdodds/use-deep-compare-effect#readme
Source0: https://registry.npmjs.org/use-deep-compare-effect/-/use-deep-compare-effect-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
Requires: npm(@babel/runtime) >= 7.12.5
Requires: npm(@babel/runtime) < 8.0.0
Requires: npm(@types/react) >= 17.0.0
Requires: npm(@types/react) < 18.0.0
Requires: npm(dequal) >= 2.0.2
Requires: npm(dequal) < 3.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE
%doc CHANGELOG.md
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 1.6.1-3
- Update to 1.6.1

* Thu Feb 01 2024 Eric D. Helms <ericdhelms@gmail.com> - 1.6.1-2
- Use --legacy-peer-deps during npm install

* Mon Jul 05 2021 Evgeni Golov 1.6.1-1
- Add nodejs-use-deep-compare-effect generated by npm2rpm using the bundle strategy

