%global npm_name babel-plugin-syntax-dynamic-import

Name: nodejs-babel-plugin-syntax-dynamic-import
Version: 6.18.0
Release: 1%{?dist}
Summary: Allow parsing of import()
License: MIT
Group: Development/Libraries
URL: https://babeljs.io/docs/en/next/babel-plugin-syntax-dynamic-import.html
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%doc README.md

%changelog
* Wed Jan 09 2019 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 6.18.0-1
- Add nodejs-babel-plugin-syntax-dynamic-import generated by npm2rpm using the single strategy

