%global npm_name @patternfly/patternfly

Name: nodejs-patternfly-patternfly
Version: 5.4.2
Release: 2%{?dist}
Summary: Assets, source, tooling, and content for PatternFly 4
License: MIT
URL: https://github.com/patternfly/patternfly#readme
Source0: https://registry.npmjs.org/@patternfly/patternfly/-/patternfly-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr assets %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr base %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr components %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr icons %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr layouts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-addons.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-addons.scss %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-base-no-globals-theme-dark-unversioned.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-base-no-globals-theme-dark-unversioned.scss %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-base-no-globals.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-base-no-globals.scss %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-base-theme-dark-unversioned.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-base-theme-dark-unversioned.scss %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-base.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-base.scss %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-charts-theme-dark-unversioned.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-charts-theme-dark-unversioned.scss %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-charts-theme-dark.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-charts-theme-dark.scss %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-charts.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-charts.scss %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-no-globals.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-no-globals.scss %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-theme-dark-unversioned.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-theme-dark-unversioned.scss %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-theme-dark.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly-theme-dark.scss %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly.min.css %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly.min.css.map %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr patternfly.scss %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr sass-utilities %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr themes %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr utilities %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%doc CODE_OF_CONDUCT.md
%doc README.md
%doc docs

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 5.4.2-2
- Regenerate spec file

* Mon Jun 16 2025 MariaAga <mariaaga@redhat.com> 5.4.2-1
- Add nodejs-patternfly-patternfly generated by npm2rpm using the single strategy

