%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name @unleash/proxy-client-react

Name: %{?scl_prefix}nodejs-unleash-proxy-client-react
Version: 5.0.0
Release: 1%{?dist}
Summary: React interface for working with unleash
License: Apache-2.0
Group: Development/Libraries
URL: https://github.com/Unleash/unleash-proxy-react#readme
Source0: https://registry.npmjs.org/@unleash/proxy-client-react/-/proxy-client-react-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%doc LICENCE.txt
%doc README.md

%changelog
* Wed Jul 09 2025 root <root> 5.0.0-1
- Add nodejs-unleash-proxy-client-react generated by npm2rpm using the single strategy

