%global npm_name @unleash/proxy-client-react

Name: nodejs-unleash-proxy-client-react
Version: 5.0.1
Release: 2%{?dist}
Summary: React interface for working with unleash
License: Apache-2.0
URL: https://github.com/Unleash/unleash-proxy-react#readme
Source0: https://registry.npmjs.org/@unleash/proxy-client-react/-/proxy-client-react-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712
BuildRequires: /usr/bin/node
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%doc LICENCE.txt
%doc README.md

%changelog
* Sat Jun 06 2026 Ewoud Kohl van Wijngaarden <ewoud@kohlvanwijngaarden.nl> 5.0.1-2
- Regenerate spec file

* Sun Aug 03 2025 Foreman Packaging Automation <packaging@theforeman.org> 5.0.1-1
- Update to 5.0.1

* Wed Jul 09 2025 root <root> 5.0.0-1
- Add nodejs-unleash-proxy-client-react generated by npm2rpm using the single strategy

