%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name redux

Name: %{?scl_prefix}nodejs-redux
Version: 4.2.1
Release: 1%{?dist}
Summary: Predictable state container for JavaScript apps
License: MIT
Group: Development/Libraries
URL: http://redux.js.org
Source0: https://registry.npmjs.org/redux/-/redux-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
Requires: npm(@babel/runtime) >= 7.9.2
Requires: npm(@babel/runtime) < 8.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr es %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}


%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc README.md

%changelog
* Sun Sep 14 2025 Foreman Packaging Automation <packaging@theforeman.org> 4.2.1-1
- Update to 4.2.1

* Thu Jul 03 2025 root <root> 4.0.4-1
- Add nodejs-redux generated by npm2rpm using the single strategy

