%global npm_name redux

Name: nodejs-redux
Version: 4.2.1
Release: 2%{?dist}
Summary: Predictable state container for JavaScript apps
License: MIT
URL: http://redux.js.org
Source0: https://registry.npmjs.org/redux/-/redux-%{version}.tgz
BuildRequires: nodejs-packaging
%if 0%{?rhel} == 10
# https://issues.redhat.com/browse/RHEL-137712 is fixed in RHEL 10.3
BuildRequires: /usr/bin/node
%endif
Requires: npm(@babel/runtime) >= 7.9.2
Requires: npm(@babel/runtime) < 8.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr es %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr index.d.ts %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc README.md

%changelog
* Thu Jul 30 2026 Zach Huntington-Meath <zhunting@redhat.com> 4.2.1-2
- Update to 4.2.1

* Sun Sep 14 2025 Foreman Packaging Automation <packaging@theforeman.org> 4.2.1-1
- Update to 4.2.1

* Thu Jul 03 2025 root <root> 4.0.4-1
- Add nodejs-redux generated by npm2rpm using the single strategy

