# template: scl
%{?scl:%scl_package rubygem-%{gem_name}}
%{!?scl:%global pkg_name %{name}}

%global debug_package %{nil}

%global gem_name grpc
%global gem_require_name %{gem_name}

Name: %{?scl_prefix}rubygem-%{gem_name}
Version: 1.43.1
Release: 1%{?dist}
Summary: GRPC system in Ruby
Group: Development/Languages
License: Apache-2.0
URL: https://github.com/google/grpc/tree/master/src/ruby
Source0: https://rubygems.org/gems/%{gem_name}-%{version}.gem

# start specfile generated dependencies
Requires: %{?scl_prefix_ruby}ruby(release)
Requires: %{?scl_prefix_ruby}ruby >= 2.5.0
Requires: %{?scl_prefix_ruby}ruby(rubygems)
Requires: %{?scl_prefix}rubygem(google-protobuf) >= 3.18
Requires: %{?scl_prefix}rubygem(google-protobuf) < 4
Requires: %{?scl_prefix}rubygem(googleapis-common-protos-types) >= 1.0
Requires: %{?scl_prefix}rubygem(googleapis-common-protos-types) < 2
BuildRequires: %{?scl_prefix_ruby}ruby(release)
BuildRequires: %{?scl_prefix_ruby}ruby-devel >= 2.5.0
BuildRequires: %{?scl_prefix_ruby}rubygems-devel
Provides: %{?scl_prefix}rubygem(%{gem_name}) = %{version}
# end specfile generated dependencies

BuildRequires: libstdc++-static

%description
Send RPCs from Ruby using GRPC.


%package doc
Summary: Documentation for %{pkg_name}
Group: Documentation
Requires: %{?scl_prefix}%{pkg_name} = %{version}-%{release}
BuildArch: noarch

%description doc
Documentation for %{pkg_name}.

%prep
%{?scl:scl enable %{scl} - << \EOF}
gem unpack %{SOURCE0}
%{?scl:EOF}

%setup -q -D -T -n  %{gem_name}-%{version}

%{?scl:scl enable %{scl} - << \EOF}
gem spec %{SOURCE0} -l --ruby > %{gem_name}.gemspec
%{?scl:EOF}

%build
# Create the gem as gem install only works on a gem file
%{?scl:scl enable %{scl} - << \EOF}
gem build %{gem_name}.gemspec
%{?scl:EOF}

# %%gem_install compiles any C extensions and installs the gem into ./%%gem_dir
# by default, so that we can move it into the buildroot in %%install
%{?scl:scl enable %{scl} - << \EOF}
%gem_install
%{?scl:EOF}

%install
mkdir -p %{buildroot}%{gem_dir}
cp -a .%{gem_dir}/* \
        %{buildroot}%{gem_dir}/

mkdir -p %{buildroot}%{gem_extdir_mri}/%{gem_name}
cp -a .%{gem_extdir_mri}/gem.build_complete %{buildroot}%{gem_extdir_mri}/
cp -a .%{gem_extdir_mri}/%{gem_name}/*.so %{buildroot}%{gem_extdir_mri}/%{gem_name}/

%files
%dir %{gem_instdir}
%{gem_extdir_mri}
%{gem_instdir}/etc
%{gem_instdir}/src
%exclude %{gem_cache}
%{gem_spec}
%exclude %{gem_instdir}/.yardopts
%exclude %{gem_instdir}/include
%exclude %{gem_instdir}/third_party
%exclude %{gem_instdir}/Makefile

%files doc
%doc %{gem_docdir}


%changelog
* Tue Feb 22 2022 Evgeni Golov 1.43.1-1
- Add rubygem-grpc generated by gem2rpm using the scl template
