%{?scl:%scl_package nodejs-%{npm_name}}
%{!?scl:%global pkg_name %{name}}

%global npm_name zxcvbn

Name: %{?scl_prefix}nodejs-zxcvbn
Version: 4.4.2
Release: 1%{?dist}
Summary: realistic password strength estimation
License: MIT
Group: Development/Libraries
URL: https://github.com/dropbox/zxcvbn#readme
Source0: https://registry.npmjs.org/zxcvbn/-/zxcvbn-%{version}.tgz
%if 0%{?!scl:1}
BuildRequires: nodejs-packaging
%endif
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch
Provides: %{?scl_prefix}npm(%{npm_name}) = %{version}

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr dist %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr lib %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr src %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%check
%{nodejs_symlink_deps} --check

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.txt
%doc README.md

%changelog
* Wed Jul 09 2025 root <root> 4.4.2-1
- Add nodejs-zxcvbn generated by npm2rpm using the single strategy

