%global npm_name warning
%global enable_tests 1

Name: nodejs-%{npm_name}
Version: 4.0.1
Release: 1%{?dist}
Summary: A mirror of Facebook's Warning
License: MIT
Group: Development/Libraries
URL: https://github.com/BerkeleyTrue/warning
Source0: https://registry.npmjs.org/%{npm_name}/-/%{npm_name}-%{version}.tgz
BuildRequires: nodejs-packaging
Requires: npm(loose-envify) >= 1.0.0
Requires: npm(loose-envify) < 2.0.0
BuildArch: noarch
ExclusiveArch: %{nodejs_arches} noarch

%description
%{summary}

%prep
%setup -q -n package

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr package.json %{buildroot}%{nodejs_sitelib}/%{npm_name}
cp -pfr warning.js %{buildroot}%{nodejs_sitelib}/%{npm_name}

%nodejs_symlink_deps

%if 0%{?enable_tests}
%check
%{nodejs_symlink_deps} --check
%endif

%files
%{nodejs_sitelib}/%{npm_name}
%license LICENSE.md
%doc CHANGELOG.md
%doc README.md

%changelog
* Mon Jun 11 2018 Eric D. Helms <ericdhelms@gmail.com> 4.0.1-1
- Update to 4.0.1

* Mon Apr 23 2018 Eric D. Helms <ericdhelms@gmail.com> 3.0.0-1
- Add nodejs-warning generated by npm2rpm using the single strategy

